tokiwa-software/fuzion

src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/classfile/ByteCode.java, src/dev/flang/be/jvm/classfile/ClassFile.java, src/dev/flang/be/jvm/classfile/Expr.java
For now this is only implemented for non-empty StackMapTables
Bytecode that uses `StackMapTable.empty` still has a fixed number of stack/locals.
fixes #2176
=> be/jvm: determine max_stack/max_locals programmatically

src/dev/flang/be/c/C.java, src/dev/flang/be/c/CIdent.java, src/dev/flang/be/c/CTypes.java, src/dev/flang/be/c/Intrinsics.java
=> be/c: replace __atomic-builtins by c11 atomics

src/dev/flang/ast/Call.java, src/dev/flang/ast/Partial.java
=> fe: change `typeForInferencing` usage of `type` to `typeForInferencing`

lib/bench.fz, lib/time/nano.fz
before it was using fuzion.std.nano_time directly
=> lib: change `bench` to use `time.nano` effect

src/dev/flang/ast/UnresolvedType.java
`res.resolveDeclarations(outerfeat);` was called twice.
=> fe: remove some unecessary/duplicate code

Makefile, examples/callingJava/Makefile, examples/javaGraphics/Makefile, examples/webserver/Makefile, examples/webserver/webserver2.fz, tests/fileio/Makefile, tests/fz_cmd/Makefile, tests/javaBase/Makefile, tests/sockets/Makefile
default was changed to _on_ some time ago
=> remove now unecessary `-unsafeIntrinsics=on`

src/dev/flang/ast/AbstractBlock.java, src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/If.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/NumLiteral.java, src/dev/flang/ast/Types.java, tests/reg_issue1069/Makefile, tests/reg_issue1069/reg_issue1069.fz, tests/reg_issue1069/reg_issue1069.fz.expected_out
fixes #1069
fixes #2282 
This patch enhances type inference for numbers if they are unified with results from other branches like in arrays, if-else or match-cases.
Examples:
- `a := [0.3, option 3.142, nil, 42]`   # infers that all the numbers to be of type `option f64`
- `if b then 42  else option 3.14`     # infers that all the numbers to be of type `option f64`
=> fe: improve type inference for mixed numeric types

Makefile, src/dev/flang/tools/Tool.java, src/dev/flang/util/ANY.java, src/dev/flang/util/Version.java.in
example:
```
error 1: java.lang.Error: require-condition1 failed: Call.java:1453 "(Errors.any() || calledFeatureKnown() || _pendingError != null);"
at dev.flang.util.ANY.require(ANY.java:97)
at dev.flang.ast.Call.calledFeature(Call.java:1453)
at dev.flang.ast.Feature.dependsOnOuterRef(Feature.java:1444)
at dev.flang.ast.Feature.lambda$closureAccesses$7(Feature.java:1427)
at dev.flang.ast.Expr.visitExpressions(Expr.java:258)
at dev.flang.ast.AbstractCall.visitExpressions(AbstractCall.java:101)
```
=> util: on contract failure try showing expression that led to failure

src/dev/flang/parser/Parser.java
I prefer not to have any special handling for the braces-variant of a feature, so making `is` or `=>` compulsory even for a feature body using `{`..`}`.
Will have to update fuzion-lang.dev tutorial examples in the version that uses braces.
=> parser: Require `is` or `=>` even if feature uses `{`..`}`

src/dev/flang/parser/Parser.java
I thought the tests already succeeded... :-(
Reverts tokiwa-software/fuzion#2655
=> Revert "parser: Require `is` or `=>` even if feature uses `{`..`}`"

src/dev/flang/parser/Parser.java
This permits code like
```
if a=b
then
say "equal"
else
say "not equal"
```
which is also permitted for `do`, `while`, `until` and seems more uniform.
=> parser: Allow `then` to be placed at min indentation

src/dev/flang/ast/Block.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Cond.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/ParsedOperatorCall.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/SourcePosition.java, tests/reg_issue1739_this_type_in_type_feature_choice/issue1739.fz, tests/reg_issue1945_ambiguity_for_lambda_result_neg/issue1945neg.fz.expected_err, tests/reg_issue2492/reg_issue2492.fz.expected_err
A number of changes to simplify handing of parsing a `block` and creation of instances of `dev.flang.ast.Block`:
Removed unused field `Block. _closingBracePos` and changed or removed constructors that set this field.
Improved code that associated a `SourceRange` to a `Block`.
Replaced the special handling of `Numeric` in parentheses by a special handling of operator expressions, which is really what was needed here.
Pre- and Postconditions are now parsed as `block`, no longer as `exprs`.
Added new helper `Lexer.optionalBrackets` that is used for parsing `block` and `match` that both have optional `{`/`}`.
Added helpers `Lexer.sourceRange(pos)` to get the source range of the code parsed from `pos` up to the current location and `Lexer.sourceRange(prevPos, pos, endPos)` that results in …
=> Parser simplify block

src/dev/flang/parser/OpExpr.java, src/dev/flang/parser/Parser.java
Remove special handling of bracket terms that does not seem necessary. 
Avoid using `*` and `+` in ENBF for repetition, use recursion only. 
Renamed `OpExpr.els` as `OpExpr._els`.
=> parser: cleanup for rules `exprInLine`, `opExpr` and `opTail`

include/posix.c, include/win.c, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/SourceFile.java
This led to lots of test failures in the language server.
=> parser: fix require condition when creating source range

tests/fz_cmd/fz_cmd.fz.expected_err
The new `)` got added in #2671 but it was forgotten to update the test outputs.
=> tests/fz_cmd: update expected error

src/dev/flang/fuir/FUIR.java
Now includes arguments and result types for Calls, proper labels for match, constant data for constants.
Also reduced noise by not printing code that is not needed (FUIR.clazzNeedsCode) and noice code block ids.
Here is an exmaple output:
```
> ./build/bin/fz -XdumpFUIR -e "for a := 1, a+1 while a < 10 else say a" | tail -n 30
Code for #loop0(outer universe#0, a i32) unit
l3:	0: Current
1: Call #loop0.a(outer #loop0) i32
2: Const of type i32 00 00 00 04 0a 00 00 00
3: Call infix < i32(outer universe#0, a i32, b i32) bool
4: Match 0=>l1 1=>l2
l1:	0: Current
1: Call #loop0.a(outer #loop0) i32
2: Const of type i32 00 00 00 04 01 00 00 00
3: Call i32.infix +(outer i32, other i32) i32
4: Current
5: Assign to #loop0.a
6: Current
7: Call #loop0.a(outer #loop0) i32
8: Call #loop0(outer …
```
=> fuir: Improved debugging code dump output

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java
Before this, it could happen that a call to a feature `f` that is performed within a precondition of `f` would be treated as a tail call, which is clearly wrong.
=> jvm/C: disable tail recursion optimization within precondition

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/DFA.java
Futile to attempt escape analysis on abstract, intrinsic, field and native, so don't do that.  Also set the default lifetime for native feature to Undefined since there is no instance.
=> dfa: simplify `DFA.lifeTime()` using `super.lifeTime()`

lib/id.fz
This enables partial application for `id(T,x)` to do things like `l.filter id` on a `Sequence bool`.
=> lib: rename `id(T)` as `identity(T)`

src/dev/flang/fuir/FUIR.java
=> fuir: In `dumpCode`, avoid `LF` after label after match unless no code follows

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Env.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/fuir/analysis/dfa/SysArray.java
Add helper function `DFA.wasChanged` to set `_changed` flag that signals to DFA that a fix point has not been reached yet.
Added no changed to the escape analysis results to the DFA termination condition.
=> dfa: add wasChanged, consider changes to escaped values for fix point

src/dev/flang/fuir/FUIR.java, src/dev/flang/util/IntTriplet.java
This call requires about 20% of the DFA analysis time when applied to (AdventOfCode 18 Dec)[https://github.com/fridis/fuzion_aoc/blob/main/2023/18/part2.fz], with caching this is no longer measurable using `-XjavaProf`.
Also made the implementation itself more efficient using a `TreeSet` instead of a `List`, but this change has beome irrelevant with the caching.
=> fuir: Add caching for `FUIR.accessedClazzesDynamic`

src/dev/flang/parser/Parser.java
For code like
```
use_a => _ := a.env
now_to_something_completely_different
```
the position of `a.env` used to be
```
now_to_something_completely_different
----^
```
now it is
```
use_a => _ := a.env
------------------^^^^^
```
=> parser: Better source position for an `t.env` expression

src/dev/flang/fe/LibraryFeature.java
The position used to be unknown resulting in poor error messages related to effects used in modules.
=> fe: lazily load position of `.env` expressions from `.fum` file

lib/Sequence.fz
comment says `infix operand synonym for concat_sequences` but implementation was using infix ++ of as_list
=> lib: change impl of `infix ++`

lib/io/file/read.fz
In the future we will probably have an effect providing a buffer array and then this can be removed.
=> lib: file read, increase bufsize to 4KB

src/dev/flang/air/Clazz.java
This fails for flang.dev's tutorial/examples/tuple_example3.fz.
=> air: relax precondition for for `Clazz.clazzForFieldX` in case of earlier errors

src/dev/flang/ast/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/DFA.java
The code did not set the `msg` field in the error to any value resulting in DFA with higher accuracy (which will come in the next PRs) to fail to find any value here.
This is a first step trying to split up #2743 into several PRs.
=> dfa: Fix error instance modelling as result of Java calls

src/dev/flang/ast/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/ir/IR.java, src/dev/flang/mir/MIR.java
A `site` is an int the identifies an expression in a code block, so it is a more
conveninient way compared ot passing the pair `c`/`i` that is so far used in
FUIR.  Eventually, codeblock indices should be removed completely and replaced
by `site`s only.
This patch adds a convenience method `IR.addCode` that manages the calculation
of `site` and `getExpr` as a temporary convenience method to get an Expr for
given `c`/`i`.
This should be reviewed against #2750, this is part two of my attempt to split up #2743 into several PRs.
=> ir/fuir/mir: Add support for site instead of c/i for codeblock and index

src/dev/flang/ast/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/fuir/analysis/dfa/NumericValue.java, src/dev/flang/fuir/analysis/dfa/RefValue.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/ir/IR.java, src/dev/flang/mir/MIR.java
This replaces the cumbersome `codeblockId` and `codeblockIndesx` pair, but so far there is no semantic change.
This should be reviewed against #2752, this is part three of my attempt to split up https://github.com/tokiwa-software/fuzion/pull/2743 into several PRs.
=>  dfa: include site id in Call and Instance

src/dev/flang/ast/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/Context.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/DfaErrors.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/fuir/analysis/dfa/NumericValue.java, src/dev/flang/fuir/analysis/dfa/RefValue.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/ir/IR.java, src/dev/flang/mir/MIR.java, tests/local_mutate_negative/test_local_mutate_neg.fz.expected_err, tests/reg_issue2273/reg_issue2273.fz.expected_err
Got this error before intrinsics for Java interface during DFA initialized the `msg` field of an `error` result properly and it would have helped to get more detail, which this patch provides.
Also slightly changed the output for missing effect errors and restructured the handling of Contexts.
Removed code related to a HACK that no longer exists.
This should be reviewed against #2753, this is part four of my attempt to split up https://github.com/tokiwa-software/fuzion/pull/2743 into several PRs.
=> dfa: improve error produced for uninitialized field

src/dev/flang/ast/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/Context.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/DfaErrors.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/fuir/analysis/dfa/NumericValue.java, src/dev/flang/fuir/analysis/dfa/RefValue.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/ir/IR.java, src/dev/flang/mir/MIR.java, tests/local_mutate_negative/test_local_mutate_neg.fz.expected_err, tests/reg_issue2273/reg_issue2273.fz.expected_err
This increase the DFA accuracy such that tests like flang.dev's `content/design/examples/monadiclifting_helloabort.fz` no longer produce errors.
The general pattern of code that is improved by are calls that differ by their location, i.e., in the code
```
(io.out p1).go (() -> do_something)
(io.out p2).go (() -> do_something_else)
```
we can now distinguish the two instances of `io.out` such that their print handlers `p1` and `p2` will not be mixed up.
This should be reviewed against #2754, this is part five of my attempt to split up https://github.com/tokiwa-software/fuzion/pull/2743 into several PRs.
=> DFA: Take call site into account when tracing instances and calls

src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/Intrinsics.java, tests/sockets/Makefile
Problem was that the test socket did not use interpreter for starting server. Now it does but had to fix two intrinsics.
Also some unrelated cleanups/improvements that I did not want to add yet another PR for.
=> be/interpreter: fix ClassCastException

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Loop.java
Replace the usage of `Stream` in `ast/Loop.java` by a list based approach. The documented logic has been updated to represent the new version. This depends on #2757. This does not remove `Stream` from the standard library yet, this will happen in a follow-up pull-request.
Marking as a draft for now because there is a single test failure related to the stack map table creation in `tests/reg_issue2376`.
=> ast/Loop: replace streams with a list-based approach

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Env.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/fuir/analysis/dfa/RefValue.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/fuir/analysis/dfa/ValueSet.java
This fixes the fuzion-lang.dev example `content/tutorial/examples/effect3.fz` that requires the distinction of call environments that differ only in the actual effect values.
To avoid explosion of values, the comparison of effects for this had to be relaxed not to include the effect environment.
=> dfa: increase accuracy of comparing Environments: Include effect values

.github/workflows/windows.yml, .github/workflows/windows_c.yml
This is needed when using c backend and linking jvm. The jvm.dll is in the path: $JAVA_HOME/bin/server
=> workflows windows: set $PATH to include $JAVA_HOME/bin/server

src/dev/flang/air/Clazz.java, src/dev/flang/fe/FeatureLookup.java, src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/me/MiddleEnd.java, src/dev/flang/tools/Fuzion.java, tests/reg_issue1109/Makefile
Since errors can not be written to fum file, I needed to add a `Errors.showAndExit()` after `new FrontEnd()`
=> fe/me: always use .fum file as input for middle end

lib/String.fz, lib/array2.fz, lib/array3.fz, lib/container/Set.fz, src/dev/flang/air/Clazz.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AbstractType.java, tests/reg_issue2402/Makefile, tests/reg_issue2402/reg_issue2402.fz, tests/reg_issue2402/reg_issue2402.fz.expected_out
fixes #2402
This failed:
`say $"{3}".dynamic_type`
because under the hood this uses `String.type.concat` which returns an anonymous feature `ref: String` which is defined inside of the type feature `String.type.concat`.
For features inside of type features no type feature was added which led to `AbstractType.typetype()` returning just the type of `Type`. This triggered the error in the later stages.
Now type features are added even for feature defined inside of type features.
I had to change name of `type.concat` to `type.concat1` since type features are now generated for type.concat(0 args) and type.concat(1 arg) leading to "Duplicate feature declaration" since we get type.concat(THIS#TYPE) and type.concat(THIS#TYPE, 1 arg)
Another solutions to the problem would be to disallow calling …
=> fix dynamic_type used on features defined inside of type features

src/dev/flang/ast/Loop.java, tests/loop_scoping/Makefile, tests/loop_scoping/loop_scoping.fz, tests/loop_scoping/loop_scoping.fz.expected_err
previously this worked:
```
for i := 10 do
say i
```
but this does not work:
```
for x in 1..10
i := 10
do
say i
```
This patch changes the semantics of the loop in a way that the first example also results in a feature not found error.
I think this makes loop scoping more intuitive.
We loose the ability to access any non-iterating index variables until the first iterating index variable.
@tokiwa-software/developers Not sure if this change of semantics is desirable but created this PR to get your opinions.
=> ast: change loop scoping semantics

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Excecutor.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/fuir/cfg/CFG.java, src/dev/flang/ir/IR.java
This was only used when setting outer references in the C backend. The implementation of outer references is a backend decision, so this patch removes it from FUIR.
=> fuir: Remove ExprKind.AdrOf

include/posix.c, include/win.c
fixes #2882
This likely also helps with the sockets_test failures we saw sometimes in the past.
=> be/c: fix nanosleep interruption by signal

bin/run_tests.sh, bin/run_tests_parallel.sh
e.g.:
```
/home/not_synced/fuzion (2024-04-10T14-44-08+02-00)130$ make run_tests_parallel
testing JVM backend: 221 tests, running 6 tests in parallel.
.....^C
./build/tests/argumentcount_negative in 539ms: ok
./build/tests/assignment_negative in 648ms: ok
./build/tests/abstractfeatures_negative in 1201ms: ok
./build/tests/basicIntegers_negative in 1035ms: ok
./build/tests/call_with_ambiguous_result_type_negative in 1196ms: ok
```
=> tests: record time

src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/ir/IR.java, src/dev/flang/util/FuzionConstants.java
This avoids the need to handle InlineArray in FUIR.
=> fe/ir/fuir: Split off MirExprKind from IR.ExprKind

src/dev/flang/fuir/analysis/AbstractInterpreter.java
Remove redundant creation of a sequence of `nop()` and `x`, which is the same as just `x`.
=> fuir/analysis: Minor simplification in `AbstractInterpreter.process()` for match

src/dev/flang/be/c/C.java, src/dev/flang/be/c/COptions.java, src/dev/flang/tools/Fuzion.java
added option -CTarget allowing to specify a target for compilation e.g.:
`fz -c -Xgc=off -CTarget=x86_64-pc-linux-musl tests/hello/HelloWorld.fz`
=> be/c: initial work for cross compilation

lib/num/ryu.fz, tests/atomic/test_atomic.fz, tests/reg_issue2376/reg_issue2376.fz
In the else-clause of a loop only variables before any `in` will be accessible (not yet enforced by the compiler). This PR changes the loops in lib/tests that violate this rule.
=> lib/tests: fix code of potentially unitialized access

bin/aspell.dict, src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Excecutor.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java, src/dev/flang/ir/IR.java
The IR no longer contains statements, these are called expressions now.
=> ir/fuir/be: Change `statement` into `expression`

lib/net/channel.fz, lib/net/client.fz, lib/net/request_handler.fz, lib/net/server.fz, tests/sockets/sockets_test.fz, tests/sockets/sockets_test.fz.expected_out
Channel is now a simple_effect and only installed while handling the request. Before it was permanently installed.
Also for reading a buffered.reader is now installed that may be used while handling the request.
=> lib: net request handler

bin/aspell.dict, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/SourceFile.java, src/dev/flang/util/SourcePosition.java
This speeds up building java.base.fum from 1m44s to 27s on my machine.
=> util: Precalculate results of SourceFile.codePointInLine

src/dev/flang/be/interpreter/Layout.java
In my tests yields about 10% performance gain since size() if called very frequently.
=> be/interpreter: Layout, performance

src/dev/flang/parser/Lexer.java
This is an incremental improvement over PR  #2941, only the last commit is new.
Instead of always searching through all keywords, search only those that have
a suitable length.
This speeds up building java.base.fum by about 5% on my machine.
=> lexer: speedup findKeyword by first grouping keyword by length

bin/aspell.dict, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/SourceFile.java, src/dev/flang/util/SourcePosition.java
This is based on PR #2942, only the last commit is added.
=> Speedup lexer.currentNoLimit by returning or using field _curToken directly

bin/aspell.dict, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/SourceFile.java, src/dev/flang/util/SourcePosition.java
This is based on PR #2943, only the last commit is added.
=> Speedup lexer.ignoredTokenAfter by providing fast path for common case

src/dev/flang/ast/ParsedName.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/FuzionConstants.java
This results in not creating the String for the identifier which reduces the time required to build java.base.fum by about 4%.
=> parser: when parsing `name` and the result is dumped. do not create ParsedName

src/dev/flang/parser/Parser.java
This is only needed conditionally so we can delay that fork a little and move it into the condition.
This should increase parser performance slightly.
=> parser: create second fork in skipOneType a little less eagerly

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fe/DFA.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Instance.java, src/dev/flang/ir/IR.java
Remove fields `_fuir`, `_cl`, `_pre` and `_s` from `ProcessExpression` . Had to add `site` parameter to `ProcessExpression.env` and `ProcessExpression.box`. 
Added `@Override` annotations to implementations of `ProcessExpression`. Renamed `codeAtAsPos` as `sitePos`. Removed unused imporant and unused `unbox()` in DFA's `ProcessExpression` implementation.
=> Remove state from abstract interpreter

src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/classfile/Expr.java
without this change this part of the pre-condition may fail:
`v.type()                instanceof PrimitiveType pt && pt == _types.resultType(type) ||`
=> be/jvm: fix issue in precondition of drop

src/dev/flang/tools/Fuzion.java, tests/ctrie_threads/Makefile, tests/fe.mk, tests/fz_cmd/fz_cmd.fz.expected_err, tests/reg_issue118/Makefile
... to actually do what the name implies.
Now:
-no-backend also does the DFA stage while -frontend-only really does only the frontend.
=> tools: add option `-frontend-only` change `-no-backend`

src/dev/flang/parser/Parser.java
Renamed rules for clarity:
actualSp    -> actualSpace
actualsList -> actualSpaces
actualList  -> actualCommas
Replaced `actual` by `operatorExpr`, so the grammar no longer contains a rule that would parse an actual argument as a `type`.
=> parser: cleanup of rules for `actual` arguments

src/dev/flang/ast/Partial.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java
This avoids speculative parsings to distinguish a call `a.b.c` from an env `a.b.env` or a type `a.b.type` and simplifies the parsers.
Since with this change, a call is no longer always an instance of `Call`, added a new rule `pureCall` that returns only a call and is used, e.g., in inherits clauses.
This reduces the time to build java.base.fum by about 10% (from 21s down to 19s on my machine).
=> parser: move parsing of `.env` and `.type` to `callTail`

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/ast/Partial.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java
This builds on top of PR #2979, only the last two commits were added. 
This reduces the parser complexity since there is no longer a need to look ahead up to `this` when parsing `a.b.c.this`, instead we produce an error if `.this` follows an expression or type that is not a simple qualified name.
=> parser. Parse `.this` as part of `callTail` or `typeTail`

src/dev/flang/parser/Parser.java
When a `?` is encountered, we will need a `fork()` and a `tokenSourcePos()`. This patch moves these two calls into an `if` such that they are performed only when actually needed.
This reduces the time to build java.base.fum by about 2% (with some uncertainty since I measured only once...).
=> parser: Minor performance improvement when parsing `operatorExpr`

src/dev/flang/air/Clazz.java
This solves a tricky problem with idim87ex.fz: Here, `effect.is_installed` is called, which is an intrinsic constructor defined in a type feature that results in a bool. Since the type feature's clazz was not marked as instantiated, Clazz.isInstantiated() for `effect.is_installed` also returned `false` and the choice generics TRUE and FALSE of the bool result did hance not get marked as instantiated.
Finally, since in `idiom87ex.fz`, there was no other instantiation of values `TRUE` or `FALSE`, no code was created for any match on the bool result of `isInstantiated`, resulting in the default `exit` effect not being installed.
=> air: Implicitly instantiate type features

src/dev/flang/util/Errors.java
This fixes the repeated output of
```
3 warnings.
3 warnings.
```
in fuzion-lang.dev's `design/examples/arg_intri.fz` example.
=> util: Avoid repeated output of warning statistics

src/dev/flang/parser/Parser.java, tests/free_types_negative/test_free_types_negative.fz.expected_err
This will be needed in a following patch to implement `check` expressions to get hold of the original expression.
=> parser: set source range for `expr`

src/dev/flang/fe/SourceModule.java
Within type features, types that are visible at the original feature are now also visible for the type feature, e.g., in
```
abc is
def is
type.test(x abc.def) is
say x
```
it is no longer required to qualify the type `abc.def`, one can use `def` instead:
```
abc is
def is
type.test(x def) is
say x
```
=> fe: extend type visibility into type features

lib/fuzion/runtime/fault.fz
Apparently I did not test the latest changes I made to the code such that it causes `Used abstract feature` errors.
=> lib: Add missing argument `kind` to dafult `fuzion.runtime.fault` handler

lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/numeric.fz, lib/u128.fz, lib/u16.fz, lib/u32.fz, lib/uint.fz
Also remove `fits_in_u32` since this is then no longer used and re-implemented precondition of `uint.as_u32`.
=> lib: remove `numeric.to_u32`, fix #3021

bin/run_tests.sh, bin/run_tests_parallel.sh
currently failing since date does not support nanosecond resolution on macOS
=> run_tests: add workaround for macOS

lib/io/print_effect.fz
This solves current failures in fuzion-lang.org's examples `design/examples/monadiclifting_hello*.fz`.
=> lib: Make `Print_Handler.println` public

src/dev/flang/ast/AstErrors.java
This removes two subsequent errors that are produces for fuzion-lang.dev's example `design/examples/typ_const2.fz` for type features generated from broken original features.
=> ast: supress subsequent errors for type features

src/dev/flang/air/Clazzes.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Contract.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/SrcModule.java, src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/util/List.java, tests/partial_application_negative/Makefile, tests/reg_issue3027/Makefile, tests/reg_issue3027/test_conflicting_inheritance.fz, tests/reg_issue3027/test_conflicting_inheritance.fz.expected_err, tests/simple_and_negative.mk
Fix #3027, multiple inheritance may result in crash, by first collecting all inherited features and moving the checks for redefinition to `SourceModule.checkDuplicateFeatures`.
This also adds basic infrastructure for pre- and postcondition inheritance, but the code is still disabled.
=> Support to redefine several features, fix #3027.

lib/i32.fz, lib/num/wrap_around.fz
This fixes jenkins failures when running fuzion-lang.dev examples.
=> lib: Add redundant preconditions as workaround for #3051

lib/mutate.fz, lib/mutate/array.fz, tests/reg_issue2273/reg_issue2273.fz.expected_err
This will keep `lib/mutate.fz` readable when stuff like `mutate.array2` and so on (see #2379) are added.
=> lib/mutate: split off array into a separate file

src/dev/flang/ast/AstErrors.java
This removes a subsequent error that now shows up in fuzion-lang.dev's content/design/examples/typ_const2.fz.
=> ast: supress subsequent cannot redefine errors in type features

src/dev/flang/ast/AstErrors.java
This problem occurs in fuzion-lang.dev's design/examples/red_choice.fz example. With this patch, a proper error is produced.
=> ast: fix check-failure if redefinition is a choice

src/dev/flang/tools/fzjava/FZJava.java
It seems the features selected for generating shortHands is not stable.
This is a workaround by not using the `newInstance` short hand but its full name.
=> macOS: fix building java.base.fum

src/dev/flang/be/c/C.java, src/dev/flang/be/c/Intrinsics.java
fixes wrap around multiplication of i16/u16.
I'm all but certain that this is just an issue for i16/u16...
=> be/c: add compiler switch `-ftrapv`

src/dev/flang/fe/SourceModule.java, tests/reg_issue3136/Makefile, tests/reg_issue3136/redef_with_type_pars.fz, tests/reg_issue3136/redef_with_type_pars.fz.expected_out
Since a redefinition has its own type parameters, when checking whether the argument and result types match the redefined feature we need to replace type parameters by those of the redefined version.
Also add a regression test.
=> ast: Support redefinition of feature with type parameters, fix #3136

src/dev/flang/ast/Feature.java
when applying a diff to base lib similar to the one found in #1567 I found that this check is done too early.
This is because it relies on that the inherited features are at least in state RESOLVED_INHERITANCE which is not necessarily true.
=> ast: move choiceTypeCheck from type inf to type check

src/dev/flang/be/c/C.java
see: https://github.com/tokiwa-software/fuzion/actions/runs/9190304838/job/25274227621
some newer clang versions complain about this
=> be/c: fix "use of an empty initializer is a C23 extension"

src/dev/flang/air/Clazz.java
intrinsics may return `String` which will actually be `ConstString` so it would be okay if `String` is instantiad and and abstract is called on it.
=> air: in abstractCalled-check use `isCalled` instead of `isInstantiated`

tests/javaBase/javaHello.fz
different on windows:
```
< error: not_a_valid_file (No such file or directory)
---
> error: not_a_valid_file (The system cannot find the file specified)
```
=> tests: fix unstable exception message

lib/exit.fz
=> lib: change `exit(handler, code)` to return unit

tests/_diff_err.sh, tests/_strip_err.sh, tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
This discards line and column number information and ids from loops and lambdas generated by fz, such that any slight changes in source code positions or internal numbering do not cause tests to fail
=> tests: for simple tests, preprocess err output to avoid common false pos errors

doc/ref_manual/fuzion_reference_manual.adoc, src/dev/flang/ast/Feature.java
The problem is that a choice feature must not have a result type, but here it has and the result field is created early, which is reported as an error but only after a failing postcondition check.
So this patch relaxes the postcondition and adds a corresponding rule for the reference manual.
=> ast: Fix postcondition failure on fuzion-lang.dev's `design/examples/arg_choice.fz`

src/dev/flang/be/c/C.java
newer clang may emit error/warning:
"use of an empty initializer is a C23 extension"
=> be/c: improve c11 compat., no empty initializer

lib/i64.fz, lib/i8.fz
does not add preconditions for `as_u8` since they covered by `fits_in_u8` in numeric.fz once #3051 is fixed
=> lib: add missing preconditions for numerical conversion, fixes #3191

src/dev/flang/be/effects/Effects.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/Context.java, src/dev/flang/fuir/analysis/dfa/DFA.java
Prooblem was that `showWhy` was sometimes called to give details for an error and somtimes to give details for normal output.  Now, the detailed stack trace is printed either to stdout or stderr depending on what it is for.
This was triggerd by fuzion-lang.dev's `design/examples/dec_choice.fz` that prints part of the error output to stdout.
=> dfa: Use `StringBuilder` instead of `say` in `showWhy`

src/dev/flang/air/Clazz.java, src/dev/flang/tools/CheckIntrinsics.java
This is required to properly detect missing implementations of abstract features and fix #3199.
=> air: do not automatically mark ref results from intrinsics as instantiated

lib/mutate/circular_buffer.fz, src/dev/flang/ast/Function.java, src/dev/flang/fe/SourceModule.java, tests/catch_postcondition/catch_postcondition.fz, tests/catch_postcondition/catch_postcondition.fz.expected_err, tests/reg_issue1247/src/b.fz, tests/reg_issue874ff/issue874.fz, tests/sockets/sockets_test.fz, tests/tailrecursion/test_tailrecursion.fz, tests/this_type/test_this_type.fz, tests/type_feature/test_type_feature.fz, tests/valWithDynOuter/valWithDynOuter.fz, tests/visibility_modules_negative/main.fz, tests/visibility_modules_negative/main.fz.expected_err
=> Make use of `redef` mandatory when implementing abstract features

lib/array2.fz, lib/array3.fz, src/dev/flang/parser/Parser.java, tests/reg_issue3168_parsing_tuples/Makefile, tests/reg_issue3168_parsing_tuples/reg_issue3168_parsing_tuples.fz, tests/reg_issue3168_parsing_tuples/reg_issue3168_parsing_tuples.fz.expected_out
tuple used as type parameter caused syntax error if not in  double parentheses
fix #3168
=> Fix issue parsing tuples

include/fz.h, include/shared.c, lib/fuzion/java.fz, src/dev/flang/be/c/C.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java, tests/javaBase/javaHello.fz, tests/reg_issue2740/reg_issue2740.fz
With this change fuzion_lang webserver does not crash anymore when run with c backend but response is empty.
On the terminal the application prints some weird stuff:
`instance[webserver.request_method] 1o2.0rtl.c*`
Probably a zero termination missing somewhere...
=> lib/be: add fuzion.java.create_jvm, allowing to supply custom class path

src/dev/flang/be/interpreter/Interpreter.java
exception was:
```
> Exception in thread "Thread-1" java.lang.NullPointerException: Cannot read field "left" because "r" is null
> 	at java.base/java.util.TreeMap.rotateLeft(TreeMap.java:2578)
> 	at java.base/java.util.TreeMap.fixAfterInsertion(TreeMap.java:2645)
> 	at java.base/java.util.TreeMap.addEntry(TreeMap.java:805)
> 	at java.base/java.util.TreeMap.put(TreeMap.java:863)
> 	at java.base/java.util.TreeMap.put(TreeMap.java:569)
> 	at dev.flang.fuir.FUIR.accessedClazzesDynamic(FUIR.java:1760)
> 	at dev.flang.fuir.FUIR.accessedClazzes(FUIR.java:1786)
> 	at dev.flang.be.interpreter.Executor.ttcc(Executor.java:290)
> 	at dev.flang.be.interpreter.Executor.call(Executor.java:225)
> 	at dev.flang.be.interpreter.Executor.call(Executor.java:49)
> 	at …
```
=> be/int: improve thread safety

tests/floating_point_numbers/floating_point_numbers.fz
=> be/jvm/int: workaround f64 e^1.0 != e

examples/webserver/webserver_java.fz, examples/webserver/webserver_native.fz
This is due to recent changes, that a each expression in a block must result in `unit` and also redef is now always required even when implementing an abstract method.
=> examples: fix webserver examples

doc/ref_manual/fuzion_reference_manual.adoc
The png just happened to be present in my clone of the fuzion repo, which is why I did not see any errors.
=> doc: use svg instead of png image for reference manual

src/dev/flang/parser/Parser.java, tests/reg_issue627/Makefile, tests/reg_issue627/reg_issue627.fz, tests/reg_issue627/reg_issue627.fz.expected_err
fixes #627
we can not remove/replace `set` as a keyword since it used in `set [] :=` as well as `set identifier := ...`
=> parser: improve syntax error on wrong `set` usage.

src/dev/flang/ast/ParsedCall.java, tests/reg_issue3036/Makefile, tests/reg_issue3036/reg_issue3036.fz, tests/reg_issue3036/reg_issue3036.fz.expected_err
Previously every infix feature with one or two args was considered valid as a chained boolean. This is now restricted to only these: <,>,≤,≥,=,<=,>=,!=
fixes #3036
=> ast: fix `8 %% 5 = 3` does not cause an error

src/dev/flang/parser/Lexer.java, tests/reg_issue2386/Makefile, tests/reg_issue2386/reg_issue2386.fz, tests/reg_issue2386/reg_issue2386.fz.expected_err
#2386 is actually two issues. This fixes only the first one.
=> lexer: raise error if num literal is followed by letters.

src/dev/flang/ast/Loop.java
Moved the actual tail recursive loop feature to the impl-block, was in prologSuccessBlock. This should in theory reduce variable shadowing.
Also renamed some fields and made some fields final in an attempt to improve readability.
=> ast: cleanup loop code

lib/numeric.fz
Since preconditions are inherited now implementations of these are needed by all children of numeric. These implementations are missing, e.g., in fraction.
To avoid requiring adding all of these, this patch provides default implementations that are just `true`, so children are supposed to implement operations that are complete and redefine these for partial operations.
This fixes the abstract feature error produces by examples using fractions.
=> lib: Add default implementation of numeric operator preconditions

src/dev/flang/be/c/C.java, src/dev/flang/be/c/CNames.java, src/dev/flang/be/c/CTypes.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Names.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/runtime/Runtime.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java
Significant simplification of fuir, dfa and all the backends since contracts are pure syntax sugar now and do not need any backend support.
=> be: remove precondition handling code

.github/workflows/apple.yml, .github/workflows/apple_c.yml, .github/workflows/apple_int.yml, .github/workflows/apple_jvm.yml, bin/run_tests_parallel.sh
also changed apple to workflows to use run_tests_parallel
=> tests: portable nproc

lib/String.fz, lib/int.fz
also added link to bug on another related NYI
=> lib: remove NYI for `(infix /).this.s`

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh, tests/record_simple_example.sh, tests/record_simple_example_int.sh, tests/record_simple_example_jvm.sh
I believe this might fix this problem (untested though):
```
make[1]: Leaving directory '/Users/runner/work/fuzion/fuzion/build/tests/reg_issue1838'
grep: empty (sub)expression
grep: empty (sub)expression
grep: empty (sub)expression
grep: empty (sub)expression
head: stdout: Broken pipe
grep: empty (sub)expression
grep: empty (sub)expression
grep: empty (sub)expression
grep: empty (sub)expression
grep: empty (sub)expression
head: stdout: Broken pipe
grep: empty (sub)expression
```
=> tests: fix "grep: empty (sub)expression"

src/dev/flang/ast/AbstractCurrent.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/FeatureVisitor.java, src/dev/flang/ast/Impl.java, tests/reg_issue3308/Makefile, tests/reg_issue3308/reg_issue3308.fz, tests/reg_issue3308/reg_issue3308.fz.expected_out
A `Current` that was created for `a.this` before partial application moved the code into a new artifical feature would return the wrong instance, so we need to resolve it again.
Note that the second commit which changes the `outer` argument in call to `p.resolveType` from `outer` to `aft` is actually another bug fix that happened to be necessary to get the test to run: the outer feature in an inherits call must be the inheriting feature, not some random feature that happens to use the type of the inheriting feature in as an argument type.
Also note that the fourth commit fixes an issue with formal argument types inferred from actual argument values since the original code might use the wrong (original) outer class for resolving the actual arguments. 
This still contains an commented-out …
=> ast: Re-resolve Current if used as partial function, improve #3308

src/dev/flang/air/Clazz.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Destructure.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/ast/Resolution.java, tests/reg_issue3308/reg_issue3308.fz, tests/reg_issue3308/reg_issue3308.fz.expected_out
The type resolution has top be repeated for actual arguments in a lambda, lazy or partial call since the outer feature has changed. 
For this to work, the code that assigns the initial value to a field must be created later, i.e, not during `resolveTypes` but in phase `syntaxSugar1`. 
The issue from #3315 is no longer commented out in tests/reg_issue3308 and an even simpler example was added as well. This PR also adds new test cases with outer feature being a function and not a constructor. This includes a commented-out version of the example in #3324, which does not work yet.
=> ast/tests: Repeat type resolution for arguments in lambda to fix #3315 and fix #3308

lib/String.fz, lib/numeric.fz, lib/property/equatable.fz, lib/universe.fz
Also move `element_of` and `not_element_of` from `String` and `numeric` to `property.equatable`.  This results in `a ∈ s` and `a ∉ s` to work for all `equatable` types, which is required for a `Set` anyway.
=> lib: move `infix ∈` and `infix ∉` to `property.equatable`

src/dev/flang/ast/AstErrors.java
I was confused when I got this error since I was unsure which feature it was talking about, so I made this show the feature's source.
=> ast: Show declared feature in case of wrong number of actual arguments

Makefile, src/dev/flang/misc/logo/FuzionLogo.java
was broken due to adding of `modules-info.java`
I did not want to add jfree.svg to main `modules-info.java` so I created a second classes dir only for the logo class(es).
=> misc: fix building of logo

src/dev/flang/ast/SrcModule.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fe/SourceModule.java, tests/reg_issue3337/Makefile, tests/reg_issue3337/reg_issue3337.fz, tests/reg_issue3337/reg_issue3337.fz.expected_err
An ambiguous type in a feature signature should be reported as a bug, and not turned silently into a free type.
Also added a test for different uses of ambiguous types due to type parameters.
=> ast/tests: Do not turn ambiguous type into a free type, fix #3337

Makefile, src/dev/flang/lsp/FuzionLanguageServer.java, src/dev/flang/lsp/FuzionTextDocumentService.java, src/dev/flang/lsp/FuzionWorkspaceService.java, src/dev/flang/lsp/IO.java, src/dev/flang/lsp/Main.java, src/dev/flang/lsp/enums/Transport.java
Does nothing useful at the moment, functionality will be added in further PRs.
`make lsp/compile` compiles the language server code.
`make lsp/debug/stdio` starts the language server in debug mode with transport mode stdio
=> lsp: initial infrastructure for language server

src/dev/flang/ast/UnresolvedType.java
Avoid redundant checks `_resolved == null`. Remove check for`fo == FeatureAndOuter.ERROR` which is always `false` since `lookupType` was instructed to ignore errors.
Avoid `return` in the middle of a method.
For easiest review, use split `split diff` and `Hide whitespace`.
=> ast: Cleanup in UnresolvedType.tryResolve

bin/add_simple_test.fz
```
/home/not_synced/fuzion/bin/add_simple_test.fz:62:28: error 1: Ambiguous targets found for call to 'test'
override NAME = {test}
Found several possible call targets within the current feature at different levels of outer features:
in 'add_simple_test.fun.call.makefile_body' found 'add_simple_test.fun.call.makefile_body.test' defined at /home/not_synced/fuzion/bin/add_simple_test.fz:60:23:
makefile_body(test String) =>
and in 'add_simple_test.fun.call' found 'add_simple_test.fun.call.test' defined at /home/not_synced/fuzion/bin/add_simple_test.fz:32:7:
test String =>
To solve this, you may qualify the feature using 'add_simple_test.fun.call.makefile_body.this.test' or 'add_simple_test.fun.call.this.test'.
...
```
=> tools: add_simple_test.fz, fix ambiguity error

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
First problem is the reason that linux tests are not running currently. Shellcheck complains about printf with direct variable substitution.
```
In tests/check_simple_example_jvm.sh line 47:
printf "RUN $2 "
^-------^ SC2059 (info): Don't use variables in the printf format string. Use printf '..%s..' "$foo".
```
Second problem is the reason that windows tests are not running currently. NULL-characters and similar make windows-workaround using iconv fail:
```
RUN base64url_test.fz make[1]: Leaving directory '/d/a/fuzion/fuzion/build/tests/base64url'
iconv: base64url_test.fz.expected_out:27:0: cannot convert
```
=> tests: fix two problems in check_example scripts

lib/io/buffered/writer.fz
also used length instead of count, since this is O(1) instead of O(n)
=> lib: writer, change arg-type from array to Sequence

lib/encodings/base16.fz, tests/base16/Makefile, tests/base16/base16_test.fz, tests/base16/base16_test.fz.expected_out
base16 (hexadecimal) as defined in [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648#section-8)
=> lib: add base16 (hex) encoding

src/dev/flang/util/SourcePosition.java, src/dev/flang/util/Terminal.java
Could barely see the underline in my terminal:
with this patch:
=> util: use double underline instead of dotted underline

src/dev/flang/ast/AbstractType.java, tests/reg_issue3362/Makefile, tests/reg_issue3362/reg_issue3362.fz, tests/reg_issue3362/reg_issue3362.fz.expected_err
Since choice types cannot be called, the result of a call to `choice X Y Z` is `void`, which lead to choice types that inherit from choice to be accepted to match any constraint. This patch fixes this by not walking through the parents if the actual type parameter is a choice.
This also adds a regression test with the original code from #3362 and a minimalistic example.
=> ast: When checking actual type par against constraints, do not walk through inh chain of choice Fix #3362

src/dev/flang/ast/Loop.java
error was:
```
/home/not_synced/fuzion/examples/complex/pythagorean_triple.fz:51:15: error 1: Could not find called feature
b := v².imag / f
Feature not found: 'imag' (no arguments)
Target feature: 'num.complex'
In call: 'v².imag'
/home/not_synced/fuzion/examples/complex/pythagorean_triple.fz:49:27: error 2: Could not find called feature
f := v².real.gcd v².imag  # 1 or 2 (if real+imag is even)
Feature not found: 'imag' (no arguments)
Target feature: 'num.complex'
In call: 'v².imag'
2 errors.
```
Problem was that call to `imag` was prefixed for the loop even though the called had a target.
=> ast: fix example pythagorean_triple

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/Html.java
Directory structure now looks like this
```
String+(no+arguments)
├── as_codepoints+(no+arguments)
├── as_java_object+(no+arguments)
├── as_string+(no+arguments)
│ ...
├── type.a_char+(no+arguments)
├── type.cap_a_char+(no+arguments)
├── type.cap_z_char+(no+arguments)
│ ...
```
instead of this
```
String+(no+arguments)
├── as_codepoints+(no+arguments)
├── as_java_object+(no+arguments)
├── as_string+(no+arguments)
│ ...
```
```
String.type+(one+argument)
├── a_char+(no+arguments)
├── cap_a_char+(no+arguments)
├── cap_z_char+(no+arguments)
├── concat1+(one+argument)
│ ...
├── z_char+(no+arguments)
└── zero_char+(no+arguments)
```
I've made the method `typeFeatureOrigin()` public, I don't know if this could cause any problems.
=> generate type feature documentation inside origin feature

src/dev/flang/tools/docs/Html.java
display `ref` in the docs if the feature is a reference
=> docs: add ref keyword to api documentation

src/dev/flang/tools/docs/Html.java, src/dev/flang/tools/docs/Util.java
Add additional category for reference constructors as suggested in #3427
Docs will look like this:
>**Reference Constructors**
>▸ Any ref is
>▸ Cons(A type, B type) ref : Any is
>...
>
>**Value Constructors**
>▸ abort(T type, val abort.T) :  Any is
>...
=> docs: add reference constructor category in api docs

src/dev/flang/tools/docs/Html.java
I'll have to get used to `String` and `Sequence` not being at the top of the list, but generally it's easier to find a name without having to think about capitalization.
=> docs: sort features names in api docs case insensitively

lib/u128.fz, src/dev/flang/parser/Parser.java
Problem was that for `debug: u128.this ≤ i8.max.as_u128` `isFeaturePrefix` is called to test if `debug` might be a feature. This lead to syntax errors being emitted.
```
public fixed as_i8 i8
pre
debug: u128.this ≤ i8.max.as_u128
=>
lo.as_i8
```
fixes #3421
=> parser: fix qualifier `debug:` in combination with `.this`

assets/docs/style.css
This will underline all links in the API documentation on mouseover. E.g. this would illustrate that there are several links in the title of a feature:
```
lock_free.map.type.empty
_________ ___      _____
```
Links for types and parent features in the feature signature are currently underlined (see  #3398), which I think helps a lot to see where a link leads.
I don't have an opinion for the other cases, for consistency it'd probably be good to underline all links, on the other hand I think it's good to avoid unnecessary visual effects. Any thoughts @tokiwa-software/developers?
=> docs: underline all links in api docs on mouseover

tests/record_simple_example_int.sh
`make record_int` now creates
```
mytest.fz.expected_out_int
mytest.fz.expected_err_int
```
instead of
```
mytest.fz.expected_out
mytest.fz.expected_err
```
=> tests: change filenames for 'record_int'

src/dev/flang/ast/FeatureName.java, src/dev/flang/tools/docs/Html.java
The "type." prefix for type features is now rendered as a keyword. It appears only in front of features which are actual type features from user perspective.
Fixes issue of type appearing twice.
previously
> lock_free.#type.type.map.#type.type.empty
now
> lock_free.map.type.empty
=> docs: improve representation of type features

src/dev/flang/tools/docs/Html.java
Include the prefix/keyword "type." in the link. Even though the type is not part of the feature name, I think from a user perspective it is weird that clicking it does not open the feature page. The different colors should be a good indicator already.
I can also remove the bold formatting from "type" if that is preffered
=> docs: make type in summary list clickable

src/dev/flang/ast/ResolvedNormalType.java
This reduces the time to run
> time ./build/bin/fz tests/catch_postcondition/catch_postcondition.fz
by about 1s or 4% on my machine (24.517s instead of 25.472s).
=> ast: cache result of `ResolvedNormalType.isRef()`

lib/effect.fz
The type parameter was always set to `effect.this`, so there is not point to have it.
=> lib: remove type parameter from `effect.type.unsafe_get`

src/dev/flang/be/jvm/JVM.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/tools/Fuzion.java, src/dev/flang/tools/FuzionHome.java, src/dev/flang/tools/Tool.java, src/dev/flang/util/FuzionOptions.java, src/dev/flang/util/Terminal.java
Special internal settings such as debugging output can now be enabled via env vars in addition to Java properties (using `_` instead of `.` since `.` is not permitted in env vars).
Remaining calls to System.getProperty for `user.dir`, `java.home`, `os.name` have not been changed.
=> util/tools: Move handling of properties to FuzionOptions, add env var support

src/dev/flang/util/Terminal.java
This was set the wrong way around.
=> util: Fix handling of env var `FUZION_DISABLE_ANSI_ESCAPSE`

src/dev/flang/util/SourcePosition.java
fix #3406
Fixes the issue with minimal changes. The surrounding code could possibly be improved.
=> util: fix ArrayIndexOutOfBoundsException when creating error message

assets/docs/style.css, src/dev/flang/fe/Module.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/Html.java
Include inherited features in the API documentation. Now all features that a feature provides can be found on one page, inherited features are annotated with their parent.
Current version uses the square brackets (second line)
Any suggestions for the design? Like bigger/smaller font, drop the square brackets, different color...
=> docs: include inherited features in the docs

lib/Any.fz, lib/Type.fz, src/dev/flang/air/Clazz.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/DotType.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/Types.java, tests/modules/src/test_modules.fz, tests/modules/src_a/a.fz, tests/reg_issue1158_type_of_type_parameters/test_type_of.fz
This removes the old-style type-feature `Types`.  The only inner feature. `get`, unfortunately cannot be moved to `Type.type.get` or any other type feature, see #3431 for details. Instead, `get` gets moved to `universe.type_as_value`.
Also added `Any.type_value` as an alternative. This would be a much better place for `type_as_value`, but it cannot be within a type feature.
In any case, the following three expressions are equivalent
abc.type
type_as_value abc
abc.type_value
the preferred version is the first.
Note that this patch also contains a fix in
`AbstractFeature.existingOrNewTypeFeature` that was triggered by adding a type feature to `Any.fz`.
=> lib: Remove `Types`, move `Types.get` to `type_as_value`, fix #3431

src/dev/flang/ast/NumLiteral.java, tests/reg_issue1158_type_of_type_parameters/test_type_of.fz
If a numliteral did not have a dot and did not fit in i32, i64 was inferred as type. I think this magic does more harm than good. So this PR is proposing to remove this logic.
=> ast: numliteral, remove type inference to i64

doc/ref_manual/fuzion_reference_manual.adoc
Decided to call the outer features of type features `cotype`s to reduce confusion.
Also added cross references between `cotype` and `runtime type` and added definition of `monomorphization`.
=> doc: Addition to ref manual glossary: `cotype`, `original` and `type` `feature`

src/dev/flang/air/Clazz.java, src/dev/flang/air/Clazzes.java, src/dev/flang/air/FeatureAndActuals.java, src/dev/flang/fuir/FUIR.java
This cleanup was forgotten in #3260.  This is no longer needed since we do not have explicit handling of preconditions any longer.
=> air: Remove FeatureAndActuals._preconditionsClazz

src/dev/flang/parser/Lexer.java, src/dev/flang/util/SourceFile.java
this caused a precondition to fail when a syntax error 'unexpected end of file' happened
=> lexer: fix source range for case unexpected end of file

src/dev/flang/air/Clazz.java
This confused me during debugging.
=> air: Clazz.toString created equal strings for a feature and its cotype

Makefile
It is suggested to use `--release` instead of `-source`. Is there anything against it?
```
> make base-only
mkdir -p ./build/classes
javac -encoding UTF8 -source 21 -g -cp ./build/classes -d ./build/classes ./src/dev/flang/fuir/FUIR.java
warning: [options] location of system modules is not set in conjunction with -source 21
not setting the location of system modules may lead to class files that cannot run on JDK 21
--release 21 is recommended instead of -source 21 because it sets the location of system modules automatically
1 warning
.
.
.
```
=> makefile: use javac option `--release` as suggested by warning

Dockerfile
alpine seems to have dropped clang version 14
=> dockerfile: use clang18 instead of clang14

src/dev/flang/fe/SourceModule.java, tests/visibility/visibility.fz
this example was broken previous to this PR
```
ring(r ring) is
last ring := r.last
```
=> fe: fix accessing field of other instance in field init

src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, tests/reg_issue3429/Makefile, tests/reg_issue3429/reg_issue3429.fz, tests/reg_issue3429/skip_int
fixes #3429
Problem was that loop in `array.type.new` was not detected to be eligible for TCO, so we got a stack overflow:
```
internal := fuzion.sys.internal_array_init T length
for x in indices do
internal[x] := init x
```
Reason was that call to `internal_array.setel` (and all other intrinsics) -  and thus also `internal[x] :=` -  were marked as escaping.
I believe it should currently not be possible for an instance to escape via intrinsic, so I just excluded calls to intrinsics from being marked as escaping.
=> dfa: do not record intrinsics as escaping

src/dev/flang/be/c/C.java
this only worked by chance, since
stdbool defines:
```
#define true 1
#define false 0
```
and we use memset(..., 0) to initialize complete effect env to all zero
=> be/c: initialize all envInstalled to false

lib/int.fz, lib/integer.fz, lib/num/wrap_around.fz, lib/uint.fz
Maybe I'm missing something but I thought these two are better redefined in integer instead of wrap_around.
=> lib: move `/!` and `%!` from `wrap_around` to `integer`

src/dev/flang/be/c/C.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/DFA.java
reportErrorInCode is for generating code - or executing in the interpreters case - that stops execution immediately because an illegal state has been reached. Reaching these illegal states should only be possible in case of a bug in the compiler or if safety has been turned off.
=> ai: add method `reportErrorInCode`

src/dev/flang/util/SourcePosition.java
=> util: fix error position at line end not underlined with ansi enabled

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
The original scripts always showed `*** FAILED on out on <test_name>?` which confused me.
Also removed the `(binary)` vs. `(no binary)` output for C backend tests, I needed this a long time ago when implementing the C backend to see what tests actually used the backend.
=> tests: fixed `*** FAILED on err/out on <test_name>` output

src/dev/flang/ast/AstErrors.java
I ran into this while reducing number of effect modes.
=> ast: supress subsequent error on ambiguous choice containing errors

src/dev/flang/ast/Feature.java, src/dev/flang/ast/ParsedCall.java
This fixes two locations that resulted in `fz` throwing runtime exceptions while I was working on effects.
=> ast: front-end robustness: avoid null pointer and index out of bouds

src/dev/flang/ast/AstErrors.java
fix #3563
How it looks now
```
> cat /tmp/impr_err_msg.fz
parent is
func String => abstract
child : parent is
redef func => "not working because ref keyword missing"
main(x parent) =>
say (x.func)
main child
> FUZION_DISABLE_ANSI_ESCAPES=true fz /tmp/impr_err_msg.fz
/tmp/impr_err_msg.fz:11:6: error 1: Incompatible types when passing argument in a call
main child
-----^^^^^
Actual type for argument #1 'x' does not match expected type.
In call to          : 'main'
expected formal type: 'parent'
actual type found   : 'child'
assignable to       : 'child'
for value assigned  : 'child'
To solve this you could:
• make  'parent' a reference by adding the 'ref' keyword, so all its heirs can be used in place of it
• change the type of the target 'x' to 'child'
• convert the type of the assigned …
```
=> ast: improve error message when inheritance is used without `ref`

lib/exit.fz
PR#3574 broke this by not providing a lambda to be executed in case of an abort.
=> lib: fix exit effect

lib/cache.fz, lib/handles.fz, lib/handles2.fz, lib/oneway_monad.fz, lib/state.fz
PR#3574 broke this removing the effect mode. This is required to be able to create oneway monads that are either classic monads that wrap function results or effects in the environment.
=> lib: fix oneway monads

Makefile
This causes problems with the Jenkins/Dockerfile build that are otherwise hard to work around.
=> Makefile: do not run EBNF script with `all` target

src/dev/flang/ast/AstErrors.java, tests/dot_type_call_ambiguity/dot_type_call_ambiguity.fz.expected_err
I was once confused since I did not see which features were meant.
Added a helper method `AstErrors.s_feat_and_pos` to output a feature with it delcaration position.
=> ast: For ambiguous calls, show the position of the feature declarations

src/dev/flang/be/c/C.java, src/dev/flang/be/c/CFile.java
I was confused then using `-verbose` and `-XkeepGeneratedCode=on` and I could not find the C files anymore.
With this patch, `-XkeepGeneratedCode=on` will cause not to use temp files at all but generate C files using the main clazz name.
=> C: When `-XkeepGeneratedCode=on` is set, do not use `File.createTempFile`

src/dev/flang/be/jvm/Intrinsix.java
For a unit type. we must pass `null` to `Runtime.effect_instate`. This special handling was missing for `instate0` while it was already there for `default0` and `replace0`.
Additionally, we have to explicitly `drop()` the original value in case the evaluation has some side-effect.
=> jvm: Fix code generated for instrinsic `effect.instate0` on a unit type effect

lib/equals.fz, lib/property/equatable.fz
These do not work properly for `ref` types due to #3619.
This change fixes running `idiom119ex.fz` and `idiom232ex.fz`.
=> lib: move `infix ∈` and `infix ∉` from `property.equatable` to `universe`

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, src/dev/flang/fe/LibraryFeature.java, tests/call_with_ambiguous_result_type_negative/call.fz.expected_err, tests/reg_issue3619/Makefile, tests/reg_issue3619/reg_issue3619.fz, tests/reg_issue3619/reg_issue3619.fz.expected_err, tests/reg_issue776/reg_issue776.fz.expected_err
This hopefully somewhat reduces the confusion caused by errors where feature result types depend on `this`-types of outer features while they are called via an outer `ref` type.
=> ast/tests: Improve error message for #3619, add regression test

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
problem:
1) (windows) ulimit: cpu time: cannot modify limit: Invalid argument
2) (linux): increase time for interpreter test, onesCount takes longer than 300sec
=> fix ulimit problems that occur in windows / linux actions

lib/eff/fallible.fz, lib/effect.fz, lib/io/buffered/reader.fz, lib/io/buffered/writer.fz, tests/catch_postcondition/catch_postcondition.fz, tests/catch_postcondition/catch_postcondition.fz.expected_err, tests/reg_issue2231/reg_issue2231.fz, tests/reg_issue2231/reg_issue2231.fz.expected_err
`effect.abort` must be a type feature to support aborting a `ref` effect whose type may be different than the effect value`s type, as shown in #3634.
This also contains cleanup to remove `effect.run` and `simple_effect` that should no longer be used.
=> effect: Made `effect.abort` a type feature and removed `effect.run`, fix #3634

lib/effect.fz
There is no `effect.this` value in a type feature of `effect`.
[no ci]
=> lib: Fix comment for `effect.type.abort` without arguments

src/dev/flang/ast/Call.java
Just to avoid confusing at the target handling code that is already sufficiently complex.
=> ast: cleanup Set `Call._targetOf` earlier

src/dev/flang/util/Errors.java
I often added Thread.dumpStackTrace() for debugging where an error comes from, so this helps me.
=> util: env var / property to Enable stack trace printing on error reporting

src/dev/flang/ast/Constant.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/NumLiteral.java
Reverts tokiwa-software/fuzion#3662
=> Revert "ast: Move call to  `NumLiteral.checkRange` to the CHECK_TYPES phase"

src/dev/flang/fuir/FUIR.java
example output:
```
process b(0 args) at 805306375: Assign Type to b.#result stack is [aload 0->invokeStatic fzC__Bb.fzBox->invokeStatic fzC_1u.fzRoutine, aload 0]
```
=> fuir: change output of `codeAtAsString` for `Assign`

lib/id.fz
`ignore xyz` or `xyz |> ignore` are maybe a nicer alternatives to `_ := xyz`.
=> lib: Add `ignore(T type, x T) unit` to drop a value

src/dev/flang/ast/AstErrors.java, src/dev/flang/fe/SourceModule.java
fix #3312
example
```
FUZION_DISABLE_ANSI_ESCAPES=true fz -sourceDirs=/tmp/ /tmp/3312_child.fz
/tmp/3312_child.fz:2:9: error 1: Feature declared using modifier 'redef' does not redefine another feature
redef get => "I'm child"
--------^^^
Redefining feature: 'child.get'
To solve this, check spelling and argument count against the feature you want to redefine and make sure the feature to be redefined is visible where it is redefined or remove 'redef' modifier in the declaration of 'child.get'.
one error.
```
=> ast: improve error message when redefining hidden feature

src/dev/flang/tools/docs/Html.java
=> docs: annotate redefined features

tests/visibility_negative/visibility_negative.fz
error was:
```
Expression produces result of type 'visibility_negative.this.visi2.this.use' but result is not used.
To solve this, use the result, explicitly ignore the result '_ := <expression>' or change 'visibility_negative.visi2.use' from constructor to routine by replacing'is' by '=>'.
```
=> tests: fix "result is not used" error

src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/interpreter/TailCallException.java, tests/catch_postcondition/catch_postcondition.fz.expected_err, tests/reg_issue1588/skip_int, tests/reg_issue2194/reg_issue2194.fz.expected_err, tests/reg_issue3429/skip_int, tests/tail_call_optimization/Makefile, tests/tail_call_optimization/tail_call_optimization.fz, tests/tail_call_optimization/tail_call_optimization.fz.expected_out
Adds TCO to the interpreter via simple exception throwing and a while loop. The exceptions payload being the next target+args.
=> be/int: add tail call optimization

src/dev/flang/ast/AstErrors.java, tests/reg_issue3691/Makefile, tests/reg_issue3691/reg_issue3691.fz, tests/reg_issue3691/reg_issue3691.fz.expected_err
=> ast: suppress subsequent error of generated feature `λ.call`

src/dev/flang/ast/AbstractType.java
Problem was the feature() was called on parametric type.
=> ast: fix precondition failure, AbstractType.asString

src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/runtime/Runtime.java, tests/reg_issue3734/Makefile, tests/reg_issue3734/reg_issue3734.fz, tests/reg_issue3734/reg_issue3734.fz.expected_out
`null` was also used to represent not installed effect, which caused the bug.
=> jvm: Use special value instead of `null` for unit type effect to fix #3734

src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/Module.java
see also Current:
```
public Current(SourcePosition pos, AbstractFeature f)
{
super(f.thisType());
...
}
```
I found this bug while trying to persist the main application to fum-file then reload it from there.
Also some typos, a precondition and modifier restricitions.
=> fe: library feature current, use thisType of selfType

src/dev/flang/fuir/analysis/dfa/Env.java
was debugging some code and came across this, same effect in the env twice:
```
equals#3 u32 a0=u32:1 a1=u32:0 => *** VOID *** ENV: 'try_unit, try_unit'
```
=> dfa: Env, fix logic bug in env merging code

lib/composition.fz
Also added a link to Haskell's data.aviary.birds
=> lib: Added composition operations O/B3 (owl and becard)

src/dev/flang/be/jvm/JVM.java
Otherwise, I see this
> make run_tests_jar
rm -rf build/tests
mkdir -p build
cp -rf ./tests build/tests
chmod +x build/tests/*.sh
Exception in thread "Fuzion thread" java.lang.NoClassDefFoundError: dev/flang/util/FuzionOptions
at dev.flang.util.Errors.<clinit>(Errors.java:63)
at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:116)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: dev.flang.util.FuzionOptions
=> jvm: add FuzionOptions to jar file when using `-jar` target

src/dev/flang/ast/AbstractFeature.java
Only `Any.type` should implicitly inherit `Type`. Doing this whenever the `inh` list is empty due to other errors would result in confusing errors.
=> ast: Don't let co-type inherit from `Type` in case of earlier errors

src/dev/flang/be/jvm/runtime/Runtime.java
This would previously cause errors such as
```
error 1: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because the return value of "dev.flang.be.jvm.runtime.Runtime.getException()" is null
at fzC_fuzion__java__5call_virtual_Java_java_lang_Object.fzRoutine($MODULE/fuzion/java.fz:155)
[...]
```
=> be/jvm/runtime: handle `null` message in `getException`

src/dev/flang/be/interpreter/Intrinsics.java
Not doing this results in the thread terminating and the original error might get lost as in [this test run](https://github.com/tokiwa-software/fuzion/actions/runs/10970505275/job/30466861407).
=> int: Add error handling to exit after an exception in a spawned thread

src/dev/flang/be/c/C.java, src/dev/flang/be/c/Intrinsics.java
This can be done fully be the backend, no need to have this in FUIR.  And the FUIR implementation always returned `true`, so it did not work well anyway.
Note that this patch does not remove `FUIR.isIntrinsicUsed`. I want to do this as part of PR #3820 and avoid merge conflicts that would result from changing FUIR now.
=> c: remove uses of `FUIR.isIntrinsicUsed`

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java
Makes this easier to read for clazz names like `a`.
=> c/jvm: in error created in the backends, output clazz names in quotes

src/dev/flang/ast/Box.java, src/dev/flang/ast/Expr.java, src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java
Makes the code a little less confusing and, in a next step, having the type in the `.fum` file should help getting rid for `Clazzes.propagateExpectedClazz`.
=> ast/fe: Simplify `Expr.box`, add box result type to `.fum` file

tests/reg_issue929/Makefile, tests/reg_issue929/reg_issue929.fz, tests/reg_issue929/reg_issue929.fz.expected_err
fixes #929
(there is no _confusing_ error message anymore.)
=> tests: add reg test #929

src/dev/flang/ast/Call.java, tests/inference_choice_generics/Makefile, tests/inference_choice_generics/inference_choice_generics.fz, tests/inference_choice_generics/inference_choice_generics.fz.expected_out
example that now works:
```
tree(T type) : choice nil T (Branch T) is
Branch(T type, left, right tree T) ref is
tree := (Branch
(Branch
(Branch $"A" "B")
(Branch $"C" "D"))
(Branch
(Branch $"E" "F")
(Branch $"G" nil)))
```
=> ast: improve type inference via choice generics

src/dev/flang/tools/docs/Html.java
functionality to hide arguments is no longer needed since the dedicated section for types has been removed
=> docs: cleanup: remove unused wrapper methods

src/dev/flang/tools/docs/Docs.java
This shows features, that `Type` inherits from `Any` **and** redefines, in the  type feature section. They were not shown before because of the name collision. Does not solve the problem of type features inherited from Any which are never redefined.
I'm not quite sure whether this might have any side effects.
related to #3716
=> docs: show type features inherited by and redefined in `Type`

src/dev/flang/tools/docs/Html.java
Follow up of #3808, only show constructors in the navigation panel. Remove "Types" and "Constructors" annotations.
fix #3837
=> docs: reorganize content of navigation panel on the left side

src/dev/flang/tools/docs/Html.java
=> docs: hide non public arguments in section 'Fields'

src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/Names.java, src/dev/flang/fuir/AirFUIR.java, src/dev/flang/fuir/FUIR.java
This hack will no longer work any longer with GeneratingFUIR, see branch `fum_to_fuir`.
=> fuir/jvm: remove hard-coded Java name for `fuzion.java.Java_Object.Java_Ref`

lib/Type.fz
=> lib/docs: redef `prefix $` in type, to distinguish normal from type feature

lib/String.fz, lib/concur/thread_pool.fz, lib/container/mutable_tree_map/Entry.fz, lib/container/ordered_map.fz, lib/interval.fz, lib/option.fz, modules/lock_free/src/lock_free/stack.fz
`bind` is almost the same thing but more powerful, with the  caveat that type inference is not strong enough to infer the type parameter. But this will change in the future.
=> lib: remove `map_to_option`

src/dev/flang/be/c/Intrinsics.java
This was hard-coded to internal arrays of element type `u8`, which might be different and worked only by accident.
=> c: Fix lookup for fields of internal array

src/dev/flang/fuir/analysis/dfa/DFA.java
This reads the field `fuzion.sys.internal_array.length`, so it needs to look it up which marks it as needed.
=> dfa: Fix DFA for intrinsic fuzion.java.array_to_java_object0

src/dev/flang/parser/Parser.java, tests/reg_issue3761/Makefile, tests/reg_issue3761/reg_issue3761.fz, tests/reg_issue3761/reg_issue3761.fz.expected_out
fix #3761
Example
```
for i := if true then "string" else "strong", "strung"
j in 1..3
do
say "$j: $i"
```
```
1: string
2: strung
3: strung
```
=> parser: end expr at comma 

lib/String.fz
I think this could be useful sometimes, e.g. to format some output.
```
> fz -e 'say ("abababababab".chunk 2)'
[ab, ab, ab, ab, ab, ab]
> fz -e 'say ("abababababab".chunk 3)'
[aba, bab, aba, bab]
> fz -e 'say ("abababababab".chunk 5)'
[ababa, babab, ab]
> fz -e 'say ((u64 42).bin(64).chunk(8).as_string "_")'
00000000_00000000_00000000_00000000_00000000_00000000_00000000_00101010
```
=> lib: add `String.chunk` to split a string in parts of fixed length

src/dev/flang/fuir/GeneratingFUIR.java
This is required by the interpreter, the missing implementation causes failures in some negative jenkins flang_dev tests.
This is redundant with PR #3994, but at least adds a comment to maybe remove this method altogether.
=> fuir: Implement GeneratingFUIR.declarationPos()

lib/Sequence.fz, lib/interval.fz
I think comparisons with infinite sequences should terminate when it is possible to determine the result, i.e. when one is finite or when infinite ones differ.
Makes the following possible
```
> fz -e 'say ((1..10).as_seq = (1..).as_seq)'
false
> fz -e 'say ((1..).as_seq = (1..10).as_seq)'
false
> fz -e 'say ([0,0].as_seq = (1..10).as_seq)'
false
> fz -e 'say ((1..).as_seq = (2..).as_seq)'
false
```
=> lib: ensure `Sequence.equality` with infinite sequences terminates whenever possible

lib/Sequence.fz
Because of the `zip` in `equals0` in the longer sequence only the first n elements are considered with n being the length of the shorter sequence.
So if for both sequences finite!=true but one sequence turns out to be finite, they might falsely be considered equal if the shorter sequence is prefix of the longer one.
=> lib: fix sequences with finite=unknown to be falsely considered equal if one is prefix of the other

src/dev/flang/fuir/GeneratingFUIR.java
This improves performance of 
```
time ./build/bin/fz -interpreter -e "say (u128.max)"
```
by about 30%.
Also remove synchronization, replace with checks that caching will not occur at run time.
=> fuir: add caching for tag*Clazz, box*Clazz, matchStaticSubject

lib/io/buffered/reader.fz
The default of instate_self is to panic which is probably better than `(_ -> exit 1)`
=> lib: cleanup `buffered.reader.with`

src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/TaggedValue.java, src/dev/flang/fuir/analysis/dfa/Value.java, src/dev/flang/fuir/analysis/dfa/ValueSet.java
dfa: Improve merging of tagged values
Before this, joining two values
```
a[tag:0,val:v1,v2]
a[tag:0,val:v1]
```
created a value set
```
{a[tag:0,val:v1,v2],
a[tag:0,val:v1]}
```
while now the result is
```
a[tag:0,val:v1,v2]
```
=> Dfa better joining of tagged values

lib/Binary.fz, lib/Nullary.fz, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/Types.java, src/dev/flang/ast/UnresolvedType.java, tests/asParsedType/test_asParsedType.fz.expected_out, tests/functions/functions.fz, tests/partial_application/partial_application.fz
`Nullary` as parent of `Lazy` and `Binary` as a child of `Function`
fix #2704
=> lib/ast: add `Nullary` and `Binary` functions

lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/u128.fz, lib/u16.fz, lib/u32.fz, lib/u64.fz, lib/u8.fz
required as long as precondition inheritance is not working, see #3051
=> lib: add temporary preconditions for `/` and `%` in integer types

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java
The code just worked by accident before.
=> be: Added `break` to avoid accidental fall through in switch statements

src/dev/flang/fuir/analysis/dfa/DFA.java
Removed debug code depending on env-var `CLAZZ`, I had forgotten to remove this.
Adjusted verbosity levels to be more useful, added output of all unique values to be able to find duplicates.
=> dfa: Cleanup, debugging

src/dev/flang/fuir/Clazz.java
This would have made my life easier debugging a problem where this happened.
=> fuir: Add precondition for Clazz of `Types.t_ERROR` not to be created.

src/dev/flang/fuir/analysis/dfa/DFA.java
After `lookupDone` was called, some values will be turned into unit type values. This may have the effect that new clazzes are created if these unit types are boxed.
So we run one more iteration before we report the results and check that the result reporting perfomed no more changes to the reached fix point.
=> dfa: Improve the fixpoint loop: run one more iteration after `lookupDone`

include/posix.c, include/win.c
implicit function declaration not allowed for: pthread_mutex_init, etc.
=> includes: fix some clang-tidy warnings

src/dev/flang/util/Errors.java
```
❯ fz -XmaxErrors=0 tests/typeinference_negative/typeinference_negative.fz
<built-in>: warning 1: Maximum error count reached, stop error output.
Maximum error count is 0.
Change this via property 'fuzion.maxErrorCount' or command line option '-XmaxErrors'.
41 errors and one warning.
```
fix #4083
=> util: always show total error count with `-XmaxErrors`

lib/io/dir/open.fz, lib/io/dir/use.fz, lib/io/file/delete.fz, lib/io/file/exists.fz, lib/io/file/move.fz, lib/io/file/open.fz, lib/io/file/seek.fz, lib/io/file/stat.fz, lib/io/file/use.fz, lib/io/file/write.fz, tests/lib_io_file/fileiotests.fz
Inheritance can instead be used to distinguish several files. Thus in fileiotests
`f => io.file` becomes `f : io.file is`
Also moved exists/write to own files.
=> lib: io.file/dir remove parameter T, used for distinguishing

src/dev/flang/be/c/C.java, src/dev/flang/be/c/COptions.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/JVMOptions.java, src/dev/flang/tools/Fuzion.java
It is no longer possible to run a backend without first performing DFA, so we do not need this option any more.
=> dfa/be: remove `fz` option `-Xdfa=on/off`

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Env.java
Improve #4028: This might bring a significant speedup by reducing the number of calls sites the DFA checks. Calls to constructors need more accuracy since the resulting values may be used later and, e.g., become instated effects where different calls sites may results in losing accuracy, e.g., about the installed effects. 
This reduces the time required to build the Fuzion webserver by 29%: From 1:46.54 down to 1:16.59 elapsed  time when running
```
time ./build/bin/fz -jar -o=fzweb -verbose=0 -unsafeIntrinsics=on -modules=lock_free,java.base,java.desktop,java.datatransfer,java.xml,java.logging,java.security.sasl,webserver -sourceDirs=/home/fridi/fuzion/work/fzweb/src run
```
as benchmark
=> dfa: Site-insensitive analysis for non-constructors, improve #4028

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/Env.java
`Call.toString` could result in endless recursion if debug output calling this is added in code reachable from `Call.result`. To aovoid this, this patch adds a check for recursion and stop it.
Also improve the error message if an aborted effect is not found.
Both these changes helpd me woking in #4148.
=> dfa: catch endless recursion in Call.toString, better env debug output

src/dev/flang/ast/AstErrors.java, tests/choice_negative/choice_negative.fz.expected_err, tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err, tests/visibility_negative/visibility_negative.fz.expected_err
Types that are `t_ERROR`, `t_UNDEFINED` or `Impl` that is `Impl.ERROR` in combination with previous errors reuslt in this suppression.
=> ast: Supress follow-up errors in jenkin's `man_or_boy2` and `tya_field` tests

src/dev/flang/fuir/GeneratingFUIR.java
In a profile created when building `fzweb` into a jar, this method uses 7% or the time, the performance went down from 1:24.56 to 1:17.66 elapsed time.
=> fuir: cache result of `GeneratingFUIR.constClazz`

src/dev/flang/ast/Resolution.java, src/dev/flang/util/ANY.java
for HelloWorld it looks like this:
```
resolve inheritance: public universe ***not yet known*** is Routine
resolve declarations: public universe ***not yet known*** is Routine
resolve inheritance: private HelloWorld ***not yet known*** : Any 🤝 is Routine
resolve declarations: private HelloWorld ***not yet known*** : Any 🤝 is Routine
resolve types: public universe ***not yet known*** is Routine
resolve types: private HelloWorld ***not yet known*** : Any 🤝 is Routine
resolve syntax sugar 1: public universe universe is Routine
resolve syntax sugar 1: private HelloWorld HelloWorld : Any 🤝 is Routine
resolve inheritance: private type.HelloWorld(private THIS#TYPE ***not yet known*** : Any is TypeParameter) ***not yet known*** : Any.#type (HelloWorld.this.type (in type feature)) is Routine …
```
=> ast: add debug option to Resolution

src/dev/flang/tools/Fuzion.java, src/dev/flang/tools/Tool.java
fix #4156
examples
```
❯ fz -XmaxErrors -e 'say "ok"' 
ok
❯ fz -XmaxErrors=twenty -e 'say "ok"'
error 1: 'twenty' is not a valid argument to option '-XmaxErrors'. Please provide a integer value or use the option without an argument for unlimited errors.
Usage: /home/simon/fuzion/build/bin/fz [-h|--help|-version]  --or--
/home/simon/fuzion/build/bin/fz [-c|-classes|-dfa|-effects|-frontend-only|-interpreter|-jar|-java|-jvm|-llvm|-no-backend|-saveLib=<file>] [-h|--help|-version] [<backend specific options>]  --or--
/home/simon/fuzion/build/bin/fz -pretty [-noANSI] [-verbose[=<n>]]  ({<file>} | - | -e <code> | -execute <code>)  --or--
/home/simon/fuzion/build/bin/fz -latex [-noANSI] [-verbose[=<n>]]   --or--
/home/simon/fuzion/build/bin/fz -acemode [-noANSI] [-verbose[=<n>]]   --or--
*** …
```
=> fz_cmd: check for invalid values in provided options

src/dev/flang/util/Errors.java
examples
```
❯ fz -XmaxErrors=0 -XmaxWarnings=0 tests/visibility_negative/visibility_negative.fz
452 errors and one warning.
❯ fz -XmaxErrors=0 -XmaxWarnings=1 tests/visibility_negative/visibility_negative.fz
<built-in>: warning 0: Maximum warning count reached, suppressing further warnings
Maximum warning count is 1.
Change this via property 'fuzion.maxWarningCount' or command line option '-XmaxWarnings'.
452 errors and one warning.
```
=> fz_cmd: show total warning count when output of warnings is limited

src/dev/flang/tools/Tool.java
=> fz_cmd: don't consider option value when checking for duplicate options

src/dev/flang/fuir/analysis/dfa/DFA.java
This provides one central place for operations lik to initialize outer ref, which is currently not done.
=> dfa: minor cleanup: add method to allocate `fuzion.java.Java_Object`

src/dev/flang/util/Errors.java
Also, do not create or add any new warnings once `_shutting_down_` is set. This is required to avoid race conditions when warning and error statistics haven been reported alredy by one thread while other threads may still run and, e.g., cause the compilation of some new code and reporting of new errors or warnings.
=> util: start numbering of warnings with 1, not 0. fix #4214, fix #4188

src/dev/flang/fuir/GeneratingFUIR.java
This improves the time required to build the fzweb jar by about 2.5% (38.195s instead of 39.203s).
=> fuir: cache results of `clazzResultClazz`, `clazzArgClazz` and `clazzArgCount`

src/dev/flang/tools/Tool.java
The file name was forgotten when the profiler was started.
Also fixed formatting to conform to our / GNU style guides.
fix #4201.
=> tools: Fix handling for `file` argument to of `-XjavaProf=` option.

src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Value.java
A field that is removed may result in the outer feature to become a unit type, which caused an error before this patch.
=> dfa: allow set field in UNIT value if field remove or of unit type, fix 4216

src/dev/flang/fuir/analysis/dfa/DFA.java
```
error 1: java.lang.ArrayIndexOutOfBoundsException: Index 6912 out of bounds for length 6912
at dev.flang.fuir.GeneratingFUIR.clazzResultClazz(GeneratingFUIR.java:676)
at dev.flang.fuir.FUIR.codeAtAsString(FUIR.java:1182)
at dev.flang.be.c.C$CodeGen.expressionHeader(C.java:98)
at dev.flang.be.c.C$CodeGen.expressionHeader(C.java:64)
```
occurs in branch:
turn-`env`-into-a-simple-call
=> fuir/be/c: fix Index out of bounds

bin/fz, bin/fzjava
shellcheck wants $FUZION_JAVA_ADDITIONAL_OPTIONS to be quoted to prevent globbing and word splitting. But we want to split on spaces and currently do not want to use an array, so I added a `shellcheck disable`
=> fix shellcheck issues

.github/workflows/windows.yml
This will not be sufficient to fix windows builds.
For c backend we need to link fuzion.dll but this will be another PR.
=> win: fix build issue, patch not installed

src/dev/flang/ast/Contract.java
This occurred in jenkins runs:
```
error 1: java.lang.Error: check-condition failed: Call.java:375
at dev.flang.util.ANY.check(ANY.java:440)
at dev.flang.ast.Call.<init>(Call.java:375)
at dev.flang.ast.Contract.callPostCondition(Contract.java:571)
```
A constructors post condition feature does not have generics anymore since it was changed to be an inner feature.
=> ast: fix  check-condition in callPostCondition

Makefile
`javac` option `--enable-preview` can not be used if installed java version is newer than what is specified in `--release`
```
❯ make base-only
mkdir -p ./build/classes
javac -encoding UTF8 --release 21 --enable-preview -d ./build/classes ./src/dev/flang/util/ANY.java ./src/dev/flang/util/BiGraph.java ./src/dev/flang/util/BoolArray.java ./src/dev/flang/util/Callable.java ./src/dev/flang/util/DataOut.java ./src/dev/flang/util/Errors.java ./src/dev/flang/util/FatalError.java ./src/dev/flang/util/FuzionConstants.java ./src/dev/flang/util/FuzionOptions.java ./src/dev/flang/util/Graph.java ./src/dev/flang/util/HasSourcePosition.java ./src/dev/flang/util/HexDump.java ./src/dev/flang/util/IntArray.java ./src/dev/flang/util/Intervals.java ./src/dev/flang/util/IntMap.java …
```
=> makefile: use installed java version

src/dev/flang/ast/Block.java, src/dev/flang/parser/Parser.java, tests/choice_negative/choice_negative.fz.expected_err, tests/indentation_negative/indentation_negative.fz.expected_err, tests/reg_issue2371/reg_issue2371.fz.expected_err, tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err, tests/reg_issue3406/reg_issue3406.fz.expected_err, tests/reg_issue3493/reg_issue3493.fz.expected_err, tests/reg_issue3754/reg_issue3754.fz.expected_err, tests/reg_issue4272/Makefile, tests/reg_issue4272/reg_issue4272.fz, tests/reg_issue4272/reg_issue4272.fz.expected_err, tests/reg_issue627/reg_issue627.fz.expected_err
=> ast/parser: fix scoping for blocks in braces

src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/classfile/ClassFileConstants.java, src/dev/flang/be/jvm/classfile/Expr.java, src/dev/flang/be/jvm/runtime/FuzionThread.java, src/dev/flang/be/jvm/runtime/Runtime.java
fixes #4270,
now output looks like this:
```
error 1: java.lang.Error: No effect of random instated.
at fzC_ex.fzRoutine(/home/sam/playground/test.fz:3)
at fzC_universe.fz_run(--builtin--)
at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$1(FuzionThread.java:120)
at dev.flang.util.Errors.runAndExit(Errors.java:903)
at dev.flang.be.jvm.runtime.FuzionThread.lambda$new$2(FuzionThread.java:132)
at java.base/java.lang.Thread.run(Thread.java:1583)
```
=> be/jvm: no effect of <str> instated

src/dev/flang/fuir/Clazz.java, tests/choice_negative2/choice_negative.fz.expected_err
The original error was confusing when I dubugged a cyclic layout via the `#result` field of a routine, so I added more detail.
=> fuir: better error output in case of cyclic value fields

src/dev/flang/ast/AbstractFeature.java
If this is called on something that we do not inherit from, this is the caller's fault, so it should be checked in the precondition, not only in the postcondition.
=> ast: petter precondition for `AbstractFeature.findInheritanceChain`

modules/base/src/container/mutable_tree_map.fz
add `replace` that returns the old value in places where there is a `put` and change the `put` to return nothing.
fix #3124
=> lib: add `replace` returning old value, change `put` to return nothing

modules/base/src/net/connection.fz
The dependency on `net.connections` made `net.connection` essentially useless in multi-threaded environments. This pull request shifts the onus of keeping track of connections on the caller. This is not intended to be a long-term solution but rather a quick fix for making progress with the webserver.
=> base/net/connection: do not depend on `net.connections` effect

src/dev/flang/ast/Feature.java, src/dev/flang/util/FuzionConstants.java
When debugging, I had run into calls like
```
call.this.#^b.λ.call.#^b.λ.t.call
```
which now look like this
```
call.this.#^<b.λ.call>.#^<b.λ>.t.call
```
So it is easier to see that the `.t.call` is not part of a outer ref name.
=> ast: change outer ref names from `#^x.y` to `#^<x.y>`, fix #4316

src/dev/flang/ast/Call.java, src/dev/flang/ast/ParsedCall.java
The following gives the smalles example I found that caused this problem:
```
b (t Lazy nil) => b (b t)
```
The problem is that the call to `t` is resolved repeatedly hence gets converted in `t.call` and `t.call.call` repeatedly resulting in require-conditions to fail in `fz`.
This patch uses a flag `_pushImplicitImmediateCall` to avoid repeated application of immediate call syntax sugar.
=> ast: avoid repeated immediate function call if resolveTypes called repeatedly

modules/base/src/Sequence.fz
`partially_orderable` does not seem to make any sense sense, what should be the postcondition of the ordered result?
Also adding a post-conditions for this, which requires a repeated type constraint due to #4346.
=> lib: `Sequence.sort` should require elements to be `orderable`

src/dev/flang/be/interpreter/ValueWithClazz.java, src/dev/flang/be/interpreter/i16Value.java, src/dev/flang/be/interpreter/i8Value.java, src/dev/flang/be/interpreter/u16Value.java, src/dev/flang/be/interpreter/u8Value.java
Otherwise these would not match the FunctionDescriptor of the native code.
=> be/int: fix toNative for i8/i16/u8/u16

include/fz.h
long is not used in the header file anyway and this assertion breaks windows tests.
[ci skip]
=> be/c: fix windows build

Makefile
Did not work on first run if folder `build/debugdocs` does not exist.
=> makefile: fix target debug_api_docs not working on first run

bin/aspell.dict, src/dev/flang/ast/Call.java, src/dev/flang/ast/Constant.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/StrConst.java, src/dev/flang/ast/Types.java, src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java
Removed t_Const_String from frontend. Backends decide how they want to implement constant strings.
=> cleanup: type remove `typeOfConstant`

src/dev/flang/be/c/C.java, tests/reg_issue1777/Makefile, tests/reg_issue1777/reg_issue1777.fz
fixes #1777
the offending code:
```c
fzT_1i32 fzC_my_u_loop_R_Hanonymous0__1r(fzT_my_u_loop_R_Hanonymous0* fzouter, fzT__RCurry* arg0)
{
start:
{
// cur does not escape, alloc on stack
fzT_my_u_loop_R_Hanonymous0__1r fzCur;
fzE_memset(&fzCur,0,sizeof fzCur);
// assignment to unused field `my_loop.#anonymous0.r#1.#^<my_loop.anonymous.r>`
fzCur.fzF_0_x = (fzT__RCurry*)arg0;
// 805306384: Current
// 805306385: Call my_loop.#anonymous0.r#1.x(outer my_loop.#anonymous0.r#1) Curry
// 805306386: Current
// 805306387: Call my_loop.#anonymous0.r#1.x(outer my_loop.#anonymous0.r#1) Curry
// 805306388: Call Curry.r#1(outer Curry, x Curry) i32
// tail recursion with changed target
fzouter = (fzT_my_u_loop_R_Hanonymous0*)fzCur.fzF_0_x;
arg0 = (fzT__RCurry*)fzCur.fzF_0_x;
goto start;
fprintf(stderr,"*** …
```
=> be/c: fix parameter 'fzouter' set but not used

src/dev/flang/ast/ParsedCall.java, tests/reg_issue4386/Makefile, tests/reg_issue4386/reg_issue4386.fz, tests/reg_issue4386/reg_issue4386.fz.expected_out
Do not push call if called features result type already is an open generic.
fixes #4386
=> ast: fix nested tuples

src/dev/flang/ast/AbstractCall.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Resolution.java
store usage state inside the Feature instead of using one big set with references of all used fields
=> ast: optimize recording of used fields

src/dev/flang/ir/IR.java
This patch originiates in my confusiong that CLAZZ_END and SITE_END where unused.
=> ir: programmatically calc CLAZZ_END, SITE_BASE, etc.

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
When we persist FUIR we do not want to implement these methods twice.
=> fuir: move some abstract from GeneratingFUIR to FUIR

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/Partial.java
isFunctionTypeExcludingLazy is only applicable when handling partial application
=> ast: replace isFunctionTypeExcludingLazy by isFunctionType

src/dev/flang/be/jvm/classfile/Expr.java
=> jvm: add Expr.trace() emitting stacktrace as comment

src/dev/flang/ast/ParsedName.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/jvm/runtime/Runtime.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/util/SourceFile.java
=> cleanup: fix javadoc errors not recognized by linter

src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/Tag.java, src/dev/flang/be/interpreter/Instance.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/fuir/GeneratingFUIR.java
split up into isAssignableFromWithoutTagging and isAssignableFromWithoutBoxing
In check types phase not even tagging should be necessary anymore.
=> ast: refine isAssignableFrom checks

src/dev/flang/ast/Partial.java, tests/reg_issue4420/Makefile, tests/reg_issue4420/reg_issue4420.fz, tests/reg_issue4420/reg_issue4420.fz.expected_err
=> ast: return null for `asType` of partialargs

src/dev/flang/be/c/CNames.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/be/jvm/Names.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
now unneeded since pointers are passed down to intrinsics.
=> cleanup: remove isJavaRef, instanceToJavaObject

modules/base/src/io/log.fz
The `log` feature conflicts with other definitions of a `log` feature, which is particularly annoying if you are implementing an application in Fuzion and want a `log` short-hand with custom behavior.
`redef` will only help in cases where the short-hand is to be defined in the universe, if it is defined in another feature, then fully qualifying the call would be necessary without this change.
It has been previously proposed to remove the `log` feature entirely, but this proposed change is a different viable option.
=> base: rename `log` feature as `io.log`

src/dev/flang/fuir/Clazz.java
This will also make it easier to remove fuir.fieldindex in the future.
=> fuir: cleanup, difference between _fields and fields()

Makefile
I ran into a problme building fuzion.ebnf, but strangely, running `make` again did not show any error since it was happy with the empty `fuzion.ebnf` created by the failed make.
This should delete targets if the rules failed, so we cannot just continue by running make again.
If the original behaviour is desired, you can do
```
> make
*** fails for fuzion.ebnf ***
> touch build/fuzion.ebnf
> make
--- will run to completion now, leaving the empty fuzion.ebnf untouched
```
=> make: add .DELETE_ON_ERROR

modules/base/src/Sequence.fz
These convert a sequence into a sequence of tuples and into a single tuple, respectively.
=> lib: Add `Sequence.as_*tuple[s]`, fix #4501

modules/base/src/fuzion/sys/fileio.fz, tests/lib_fileio_mmap/mmap_test.fz, tests/lib_fileio_mmap/mmap_test.fz.expected_out
Discovered this while investigating the windows test failure. Also changed mmap_test slightly, to detect file deletion failure early.
=> lib: correct result type of fzE_file_close

src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
was only needed by interpreter.
=> fuir: remove declarationPos

modules/base/src/Sequence.fz, modules/base/src/String.fz, modules/base/src/list.fz
This improves the performance of the first two test cases of #4505 significantly
and avoids the quadratic execution time:
> time ./build/bin/fz -e 'say (["1"," "].cycle.take 1000 .as_string "" .split " ").count'
501
real	0m1,528s
user	0m9,265s
sys	0m0,374s
> time ./build/bin/fz -e 'say (["1"," "].cycle.take 2000 .as_string "" .split " ").count'
1001
real	0m1,799s
user	0m10,254s
sys	0m0,550s
However, this does not improve the second example in #4505.
=> lib: Add `foldr*` to `list` and `Sequence`, use `foldr` in `String.type.join`

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
matchCaseIndex is only used in Interpreter. Moving this to FUIR will make it easier to persist FUIR and implement a _LibraryFUIR_
=> fuir: move matchCaseIndex to FUIR

bin/fz, bin/fzjava, bin/run_tests.sh, bin/windows_install_boehm_gc.sh, tests/_cur_dir.sh, tests/_diff_err.sh, tests/_strip_err.sh
- `#!/usr/bin/env bash` => `#!/usr/bin/env sh`
- not all scripts are changed since some scripts use bash features
- note that shellcheck automatically detects shell of script and lints accordingly
=> scripts: use any POSIX shell instead of bash

bin/fz, bin/fzjava
`$'\n'` works only in bash. I tried multiple options including: $(printf '%b' '\n') but this one seems to be the only one that works...
=> scripts: fix line.separator

Makefile
This improves #4559 by allowing to build Fuzion in a different directory than the source dir, but it is not a fix for the the cleanup requested in that issue.
=> makefile: Fix path to src directory for javadoc

src/dev/flang/fuir/FUIR.java
i.e. must not call clazzResultClazz or lookup_... on NO_CLAZZ
=> fuir: improve robustness of clazz_array_u8, etc.

src/dev/flang/be/c/C.java, src/dev/flang/be/c/COptions.java, src/dev/flang/tools/Fuzion.java
adds ability to include and link custom libraries, example:
`C_INCLUDE_PATH=/usr/lib/llvm-16/include/ LIBRARY_PATH=/usr/lib/llvm-16/lib fz -c -CInclude="clang-c/Index.h" -CLink=clang test.fz`
=> be/c: add -CInclude, -CLink options

src/dev/flang/ast/AbstractFeature.java
Ran into this failing while working on #4492, but did not bother creating a test case...
=> ast: relax precondition for `AbstractFeature.cotype`

src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/Layout.java
DFA may not have created this specialclazz, so it may not be available und would lead to creating this clazz at runtime.
=> be/int: Layout, do not use specialclazz pointer

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/opt/Optimizer.java
They are only used in DFA phase and hence should not be part of FUIR but only of GeneratingFUIR
=> fuir: remove methods lookup, recordAbstractMissing

modules/base/src/io/buffered/writer.fz
Same as buffered.reader, writer should not inherit from mutate but use `LM` of `io.buffered`.
=> lib: buffered.writer, use LM of `buffered`

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
can be implemented via clazzActualGeneric
=> fuir: remove inlineArrayElementClazz from GeneratingFUIR

src/dev/flang/ast/Impl.java, tests/reg_issue4549/Makefile, tests/reg_issue4549/reg_issue4549.fz, tests/reg_issue4549/reg_issue4549.fz.expected_err
The called feature may be Error, in this case post condition was not satisfied
fixes #4549
=> ast: fix initialValueFromCall in case of errors

src/dev/flang/ast/Feature.java, tests/reg_issue4540/Makefile, tests/reg_issue4540/reg_issue4540.fz, tests/reg_issue4540/reg_issue4540.fz.expected_err
=> ast: check for duplicate feature when adding type parameter

modules/base/src/String.fz
This avoids the outer ref type `String` being used as a result in a call.
=> modules: Move declaration outsite of `String` as a workaround for #4619

Makefile
=> Makefile: cleanup: replace `find` and `grep` with existing variables

src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/AbstractCurrent.java, src/dev/flang/ast/AbstractLambda.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Assign.java, src/dev/flang/ast/Block.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Cond.java, src/dev/flang/ast/Context.java, src/dev/flang/ast/Destructure.java, src/dev/flang/ast/DotType.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/Generic.java, src/dev/flang/ast/If.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/Match.java, src/dev/flang/ast/NumLiteral.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/ast/Partial.java, src/dev/flang/ast/SrcModule.java, src/dev/flang/ast/Tag.java, src/dev/flang/ast/This.java, src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/GeneratingFUIR.java
fixes #3546
I also changed the visibilities to account for this change.
=> remove uses of ast.Context anywhere but `ast`

modules/base/src/codepoint.fz
=> lib: add features like `codepoint.is_ascii_digit` for existing sets

src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/GeneratingFUIR.java
I discovered some cases where `_classes.get(cl._id) != cl` because the Clazz constructor led to newClazz being called.
These cases do not trigger any bugs currently but enabling `lookupDone` and serializing the FUIR would not work.
=> fuir: fix instability in clazz._id

src/dev/flang/ast/Context.java, tests/reg_issue4628/Makefile, tests/reg_issue4628/reg_issue4628.fz
fixes #4628
There where two issues:
- The exterior for a feature was not correctly set unless _sourceCodeContext was set.
- type parameter comparison did not work since the same type parameter might exist in two different features, the pre-condition feature and the original feature.
=> ast: fix Context.exterior and comparison of type parameters

modules/base/src/Sequence.fz
IMHO feels better like this and should improve performance, but I did not measure thatn.
=> lib: avoid `as_list` in `Sequence.as_array` if array backed

modules/base/src/container/Set.fz, modules/base/src/container/ps_set.fz, modules/base/src/interval.fz, src/dev/flang/fe/SourceModule.java
fixes #4512
Since the changes in checkLegalQualThisType would lead to an error building base.fum, I changed stdlib accordingly.
```
./build/modules/base/src/codepoint.fz:101:15: error 1: Illegal '.this' type: 'container.this.Set u32'
public type.latin_alphabet => A_to_Z ∪ a_to_z
No suitable surrounding feature was found that matches the type.
one error.
```
=> fe: fix soundness issue in checkLegalQualThisType

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch
Instead, if the DFA had found that a `match` would never return, the `AbstractInterpreter` now stop interpreting after that `match`. Since the result of a match by the backend could only be a unit type anyway, this takes the burdern of return `null` in case of an effective `void` result form the backends.
Only uses of the `AbstractInterpreter` that directly return a value for `match`, i.e., the DFA and the interpreter backend, still use `null` to signal no return (DFA), or just never actually return (interpreter).
For `call`, the handling of `alwaysResutlsInVoid` has been moved to the jvm and C backends generalizing the handling of a `void` result type. 
As a bonus, extended the AbstractInterperter debug output for a specific feature to work not only if a regex matches, but also if there …
=> ai: Remove stack cleanup for in `AbstractInterpeter` for expression with `alwaysResultsInVoid`, fix #4662     

src/dev/flang/tools/docs/Html.java
for some reason the third argument in [Binary](https://fuzion-lang.dev/docs/base/Binary+%283+arguments%29/) had the `[Private constructor]` annotation
=> docs: don't show 'Private Constructor' annotation for arguments

modules/base/src/container/expanding_array.fz
The problem was that the array was _always_ re-allocated when `add` or `ensure_capacity` was called since unused and used was mixed up.
=> lib: fix performance issue in `expanding_array`

src/dev/flang/ast/Call.java, src/dev/flang/ast/ParsedCall.java, tests/partial_application/partial_application.fz, tests/partial_application/partial_application.fz.expected_out, tests/partial_application_negative/partial_application_negative.fz.expected_err, tests/reg_issue4549/reg_issue4549.fz.expected_err
Partial application was not done for infix operator if call resultion did not produce a pending error.  Added check for `isPartialInfix` in `ParsedCall.propagateExpectedTypeForPartial` to perform partial application in this case.
Also did some cleanup: Call ot `newNameForPartial` in `Call.partiallyApplicableAlternative` was not needed, so I removed this method altogether.
Added `isPartialInfix` as an alternative to `newNameForPartial` and added the code to actual create the new name as inline code to the only remaining place that needs the name.
Also addes test case for #4687 and updated expected error output since two subsequent errors are no longer produced.
=> Fix partial application when calling infix operator, fix #4687

Makefile
Reverts #4700 which has become obsolete with #4703
#4703 provides visible version/hash information at the bottom of the apidoc pages using functionality already present in Tool.java
=> Revert "makefile: add debugging info to html when generating api docs"

src/dev/flang/ast/Call.java, src/dev/flang/ast/ParsedCall.java, tests/reg_issue197/Makefile, tests/reg_issue197/reg_issue197.fz, tests/reg_issue197/reg_issue197.fz.expected_out
The problem is that a call `(a X).(b Y)` where `a` and `b` are generic needs to apply the actual generics to `b`'s forma result type, and these could come from  the outer type `a X` and from the call `b Y`.  This, unfortunately, was done in the wrong order: It has to be done first taking the formal result type of `b` and replacing type parameters in there by the outer  type `a X`, and then  applying the type parameters given in the call `b Y`.
When done the other way around, i.e., first applying the type parameters given to the call to `b Y` and then those in the outer type `a X`, the result is wrong if the calls is done within `a` and `Y` contains type parameters of `a`.
To be able to do this, the code to determine the call's formal result type, which contained `t.applyTypePars(cf, …
=> ast: Fix #197 by fixing order of `applyTypePars` for call resul type

modules/base/src/Sequence.fz
This makes it easy to use `Sequence`s as keys in maps or similar.
=> lib: Add `Sequence.orderable`

modules/base/src/Sequence.fz, modules/base/src/container/expanding_array.fz, tests/atomic/test_atomic.fz.effect, tests/hello/HelloWorld.fz.effect, tests/i18n_default_test/i18n_default_test.fz.effect, tests/lib_concur_sync/lib_concur_sync.fz.effect, tests/mod_lock_free_Map_threads/ctrie_threads.fz.effect
Concatenating finite sequences where the right sequence is shorter are now performed using `container.expanding_array`.
I see the performance of the test in #4465 improve signficantly:
4194304:	 [1]++l: 5239ms 1249ns/it    0ns/it² | l++[1]: 1869ms  445ns/it    0ns/it² factor: 0
=> lib: Add heuristics to avoid `Sequence.concat` to cause quadratic performance

src/dev/flang/ast/Destructure.java, src/dev/flang/parser/Parser.java, tests/tuple/tupletest.fz, tests/tuple/tupletest.fz.expected_out
forbids this
```
❯ FUZION_DISABLE_ANSI_ESCAPES=true fz -e '(a i32, b i32) := (1, 2); _:=a; _:=b'
command line:1:1: error 1: Failed to infer open type parameter type from actual argument.
(a i32, b i32) := (1, 2); _:=a; _:=b
^
Type of second actual argument could not be inferred at command line:1:2:
(a i32, b i32) := (1, 2); _:=a; _:=b
-^
command line:1:30: error 2: Could not find called feature
(a i32, b i32) := (1, 2); _:=a; _:=b
-----------------------------^
Feature not found: 'a' (no arguments)
Target feature: 'universe'
In call: 'a'
command line:1:36: error 3: Could not find called feature
(a i32, b i32) := (1, 2); _:=a; _:=b
-----------------------------------^
Feature not found: 'b' (no arguments)
Target feature: 'universe'
In call: 'b'
3 errors.
```
=> ast: remove possibility to specify types in tuple destructuring

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/FormalGenerics.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/fe/SourceModule.java, tests/reg_issue4694/Makefile, tests/reg_issue4694/reg_issue4694.fz, tests/reg_issue4694/reg_issue4694.fz.expected_err
fix #4694
I think the remaining subsequent error is justified and should not be suppressed, but correct me if I'm wrong
```
❯ FUZION_DISABLE_ANSI_ESCAPES=true fz -e '0 |> x,y->container.expanding.env.put'
command line:1:6: error 1: Wrong number of arguments in lambda expression
0 |> x,y->container.expanding.env.put
-----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Lambda expression has 2 arguments while the target type expects one argument.
Arguments of lambda expression: 'x', 'y'
Expected function type: Unary --UNDEFINED-- i32
To solve this, remove one argument from the list 'x', 'y' before the '->' of the lambda expression.
command line:1:21: error 2: Wrong number of type parameters
0 |> x,y->container.expanding.env.put
--------------------^^^^^^^^^
Wrong number of actual type parameters in type: …
```
=> ast: suppress subsequent errors for error types

tests/tuple/tupletest.fz
possibility to specify types in destructuring was removed in #4702
fix #4735
=> tests: remove unsupported test cases from `tupletest`

src/dev/flang/ast/Select.java
Solves a failed check condition. Discovered by a test case in `tuple_negative` (so no reg test required).
before
```
❯ FUZION_DISABLE_ANSI_ESCAPES=true fz -e 'one9 := (42); say "one9 is {one9.values.0}"'
error 1: java.lang.Error: require-condition3 failed: AbstractType.java:464 "(this  .isGenericArgument() || this  .feature() != null || Errors.any(), actual.isGenericArgument() || actual.feature() != null || Errors.any(), Errors.any() || this != Types.t_ERROR && actual != Types.t_ERROR);"
at dev.flang.util.ANY.require(ANY.java:136)
at dev.flang.ast.AbstractType.isAssignableFrom(AbstractType.java:464)
at dev.flang.ast.AbstractType.isAssignableFrom(AbstractType.java:352)
at dev.flang.ast.AbstractType.isAssignableFromWithoutTagging(AbstractType.java:381)
at …
```
=> ast: add error for illegal use of select

src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/JVM.java
This is in case of a DFA or backend bug, now should be more efficient in case no code is unreachable and produce a more detailed error in case this code is executed.
=> jvm: better error handling for unreachable code

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, tests/choice_negative/choice_negative.fz.expected_err, tests/generics_negative/generics_negative.fz.expected_err, tests/reg_issue1666/reg_issue1666.fz.expected_err, tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/issue698.fz.expected_err
=> ast: cleanup: use "must not" instead of "cannot" for rules or restrictions

modules/base/src/fuzion/runtime/check_fault.fz, modules/base/src/fuzion/runtime/post_fault.fz, modules/base/src/fuzion/runtime/pre_fault.fz
A bit weird that only for post_fault the type infer does not yet work...
=> lib: small cleanup of NYI and unnecessary parens

modules/base/src/numeric.fz, src/dev/flang/parser/OpExpr.java, tests/reg_issue3081/Makefile, tests/reg_issue3081/reg_issue3081.fz, tests/reg_issue3081/reg_issue3081.fz.expected_out
fixes #3081
principles:
- "no whitespace" always beats any precendence.
- left to right, unless infix operator `^` which is right to left
=> parser: prefix operator precedence over postfix

assets/docs/style.css
=> docs: fix navigation on the left side escaping the frame of the site

Makefile, bin/ebnf.fz
It should be possible to build `fuzion` from any dir using `make -f <fuzion-dir>/Makefile`. This did not work for `fuzion.ebnf` and, what is worse, the error was silently ignored with an empty `fuzion.ebnf` file.
Now, `ebnf.fz` expects the source files that contain ebnf data as arguments. Furthermore, it produces errors in case these arguments are missing or in case the files do not exist.
=> build: Enable building `fuzion.ebnf` in a dir different than the source dir

src/dev/flang/fuir/analysis/dfa/Call.java
`result()` has all sorts of side effects since it tries to determine the result by code analysis.  Since `toString()` is used for debugging, this will change the state of the DFA in a way that makes this debugging harder.
So, I prefer printing no details on the results and not changing the state in `toString()` to not mess up with what I am debugging.
=> dfa: Do not call `result()`in `Call.toString()`.

Dockerfile
[ci skip]
Reason is that alpine does not have antlr package which is now required be `make all`
=> dockerfile: switch from termurin to ubuntu

modules/base/src/bench.fz, modules/base/src/random.fz, modules/base/src/time/duration.fz, modules/base/src/time/instant.fz, modules/base/src/time/nano.fz, modules/base/src/time/stopwatch.fz, tests/atomic/test_atomic.fz, tests/reg_issue1588/reg_issue1588.fz
instant is purely abstract, meaning it can only be used to measure the duration between two moments in time, and instants do not specify any absolute point in time.
=> time: introduce instant, an abstract moment in time

src/dev/flang/fe/LibraryOut.java
We need this for sth. like:
`sqlite3_exec(F type : Function i32 i32 fuzion.sys.Pointer, callback F) i32 => native`
=> fe: LibOut, relax check condition to allow native to have type params

modules/base/src/time/instant.fz
Mark `infix -` as a fixed feature as this is required for types to be compatible. Do the same for `infix +` for consistency.
=> time/instant: add precondition to `infix -`

Makefile
Before:
```
[...]
rm -rf build/include
mkdir -p build
cp -rf ./include build/include
echo " + "build/lib/libfuzion.so
+ build/lib/libfuzion.so
mkdir -p ./build/lib
clang -Wall -Werror -O3 -shared -fPIC \
-DFUZION_ENABLE_THREADS \
-fno-trigraphs -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=c11 \
./build/include/posix.c ./build/include/shared.c -o build/lib/libfuzion.so
[...]
rm -f ./build/modules/fz_cmd.jmod
jmod create --class-path ./build/classes ./build/modules/fz_cmd.jmod
echo " + build/modules/fz_cmd.jmod"
+ build/modules/fz_cmd.jmod
[...]
```
After:
```
[...]
rm -rf build/include
mkdir -p build
cp -rf ./include build/include
+ build/lib/libfuzion.so
mkdir -p ./build/lib
clang -Wall -Werror -O3 -shared -fPIC \
-DFUZION_ENABLE_THREADS \
-fno-trigraphs …
```
=> Makefile: silence some `echo` commands

src/dev/flang/fuir/GeneratingFUIR.java
The logic was flawed previously. When lookupDone, lookupNeeded should never be called. Likewise if inherits(...) is false it does not make sense to do a lookup.
=> fuir: change logic in lookup_

modules/base/src/array.fz
This is sometimes useful, since just `[]` does not specify the type while `(array String).empty` gives us an array of String.
=> lib: add `array.type.empty`

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/fuir/FUIR.java
clazzBaseName includes generics, hence we need to split at space and take only the first part.
We will need generics in native definitions for passing callbacks. Example: `sqlite3_exec(F type : Function i32 fuzion.sys.Pointer i32 fuzion.sys.Pointer fuzion.sys.Pointer, db fuzion.sys.Pointer, sql fuzion.sys.Pointer, callback F, arg fuzion.sys.Pointer, errmsg fuzion.sys.Pointer) i32 => native`
=> fuir: add convenience method, fuir clazzNativeName

modules/base/src/concur/sync.fz, modules/base/src/internal.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/be/interpreter/Value.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/SpecialClazzes.java, src/dev/flang/fuir/analysis/dfa/DFA.java
We have taken `fuzion.sys.Pointer` a bit too far already.
Especially since the DFA creates `SysArray` for allocated memory.
This created problems in my sqlite PR, since then the DFA may try joining a generic `fuzion.sys.Pointer` and a `SysArray`.
This is a start in cleaning this up.
=> lib/be: add `Mutex ref`, `Condition ref`

include/shared.c, modules/base/src/time/date_time.fz, modules/base/src/time/now.fz, tests/lib_time_date_time/lib_time_date_time.fz
Also remove some untested short-hands that for example initialized the month to 0, which is invalid.
=> time/date_time: use month and day arguments instead of day in year

src/dev/flang/fuir/analysis/dfa/Call.java
These args, essentially callbacks, might be called by native code so we need DFA to fake calls here.
=> dfa: native, dummy call function args

.devcontainer/devcontainer.json
Reverts tokiwa-software/fuzion#4882
```
ERR: Feature 'ghcr.io/devcontainers/features/clang:1' could not be processed.  You may not have permission to access this Feature, or may not be logged in.  If the issue persists, report this to the Feature author.
```
=> Revert "devcontainer: preinstall clang"

modules/base/src/container/Mutable_Hash_Map.fz, tests/mutable_hash_map/mutable_hash_map_test.fz
> I don't see much value in having it exposed.
_Originally posted by @michaellilltokiwa in https://github.com/tokiwa-software/fuzion/issues/4873#issuecomment-2702990905_
Also there was no significant difference in performance.
=> lib: remove parameterized constructor from `Mutable_Hash_Map`

src/dev/flang/ast/Feature.java, src/dev/flang/fe/SourceModule.java, tests/function_argument_visibility/Makefile, tests/function_argument_visibility/function_argument_visibility.fz, tests/function_argument_visibility/function_argument_visibility.fz.expected_err
except for `private` this is already forbidden
function arguments are private by default
fix #4886
=> ast: forbid setting argument visibility on non constructor features

modules/nom/src/nom.fz, modules/nom/src/nom/multi.fz, modules/nom/src/nom/sequence.fz
=> cleanup: replace nested `match`es in `nom` with `.bind`

tests/base16/base16_test.fz, tests/base16/base16_test.fz.expected_out, tests/base32/base32_test.fz, tests/base32/base32_test.fz.expected_out, tests/base32hex/base32hex_test.fz, tests/base32hex/base32hex_test.fz.expected_out, tests/base64/base64_test.fz, tests/base64/base64_test.fz.expected_out, tests/base64url/base64url_test.fz, tests/base64url/base64url_test.fz.expected_out
found this old branch that I apparently forgot to merge
=> tests: fix typo and improve output of baseXX encoding tests

src/dev/flang/parser/Lexer.java, tests/reg_issue2685/Makefile, tests/reg_issue2685/reg_issue2685.fz, tests/reg_issue2685/reg_issue2685.fz.expected_err
fix #2685
example:
```
❯ FUZION_DISABLE_ANSI_ESCAPES=true fz -e 'x := 1e3; say x'
command line:1:7: error 1: Broken numeric literal, exponent indicator must be in upper case.
x := 1e3; say x
------^
To fix this change 'e' to 'E'.
one error.
```
=> parser: create helpful error for lowercase exponent indicator in integers

Makefile, src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/DocsOptions.java, src/dev/flang/tools/docs/Html.java
fix #4705
I'm not sure how helpful this is other than for the web server, because for `-api-src=custDir` this would generate links like the following
`custDir/base/abort.fz`
but in the fuzion repo this file is in 
`modules/base/src/abort.fz`
So should the part `base/abort.fz` be also configurable so that `src` could be added?
=> docs: make api sources link configurable

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Feature.java
We have `resultTypeIfPresent` for that.
=> ast: change `resultType` to never return`t_UNDEFINED`

tests/mutable_hash_map/Makefile, tests/mutable_hash_map/skip_int
seems I forgot to check in the Makefile for that test 🙈
=> tests: add missing Makefile for mutable_hash_map_test

src/dev/flang/ast/Call.java
I think, we really need the result type here and want to emit errors if it would not be present.
=> ast: call, resolveFormalArg, use resultType with urgent=true

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
fix #4946
~~This applies to local execution only, timeout in GitHub CI currently looks like [this](https://github.com/tokiwa-software/fuzion/actions/runs/13920912248/job/38953748147).~~
examples
```
❯ make -C ./build/tests/base64url                
make: Entering directory '/home/simon/fuzion/build/tests/base64url'
FUZION_HOME=/home/simon/fuzion/build                             ../check_simple_example_jvm.sh "../../bin/fz " base64url_test.fz || exit 1
RUN base64url_test.fz *** CANCELLED: test base64url_test.fz exceeded cpu time limit of 10 s
make: *** [../simple.mk:68: jvm] Error 1
make: Leaving directory '/home/simon/fuzion/build/tests/base64url'
```
```
❯ make -C ./build/tests/base64url                
make: Entering directory '/home/simon/fuzion/build/tests/base64url' …
```
=> build: show reason if test was cancelled because of timeout or stack limit

src/dev/flang/ast/AbstractBlock.java, src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/If.java
This PR changes the contract of `Expr.type` and the comment.
=> fe: Expr.type never `t_UNDEFINED`

src/dev/flang/ast/Feature.java, src/dev/flang/fe/SourceModule.java, tests/reg_issue4963/Makefile, tests/reg_issue4963/reg_issue4963.fz, tests/reg_issue4963/reg_issue4963.fz.expected_err
fixes #4963
We need this when we have an existing feature with the same name in a module that is not visible outside of the module.
=> fe: allow setting feature name for features with arguments

modules/base/src/Sequence.fz, modules/base/src/encodings/base32.fz, modules/base/src/list.fz, tests/partial_application_negative/partial_application_negative.fz.expected_err
initial argument should come first, like in reduce
fix #4789
=> lib: fix argument order inconsistency in `scan` and `fold` in `Sequence`

modules/base/src/outcome.fz, modules/nom/src/nom.fz, modules/nom/src/nom/multi.fz, modules/nom/src/nom/sequence.fz
=> lib: mark `bind` in `outcome` as fixed, so `parse_result` can reuse the name

tests/process_utf8/Makefile
this way make -C test... executes all target and not compile_unicode_feature
=> tests: process_utf8, move target all to beginning

src/dev/flang/be/jvm/JVM.java
We will need this when we do not just use value layouts but also e.g. grouplayout, structlayout etc.
=> be/jvm: change type of functions descriptor args array

include/fz.h, include/posix.c, include/shared.c, include/win.c, src/dev/flang/be/c/C.java
> memset may be optimized away (under the as-if rules) if the object modified by this function is not accessed again for the rest of its lifetime
fixes #591
=> be/c: zero memory (securely)

tests/native_value/skip_jvm
=> skip native_value test on jvm backend because of #5026

modules/base/src/Type.fz, tests/reg_issue1158_type_of_type_parameters/test_type_of.fz, tests/reg_issue197/reg_issue197.fz, tests/reg_issue4557/reg_issue4557.fz, tests/visibility_scoping/visibility_scoping.fz.expected_err
type inference is now powerful enough to not need type_of_lazy anymore
=> lib: cleanup, remove `type_of_lazy`

bin/ebnf.fz, modules/base/src/container/abstract_array.fz, modules/base/src/io/file/write.fz, modules/base/src/list.fz
This is a workaround for #5036 in the base library and in `bin/ebnf.fz` to use `unit.lm` instead of a local `lm` instance to simplify the DFA analysis.
Without this, the values of the local instances get duplicated for each outer value, resulting in an explosion of the overhead of the DFA analysis.
This patch reduces the runtime of `ebnf.fz` without argument by more than 30% (from 24s down to 15s on my machine), the biggest part is the change in `ebnf.fz` itself, the others add about 0.5-1sec.
=> lib, doc: Workaround to improve DFA performance: Move local instances to `unit`

include/win.c
=> win: fix fzE_dir_read, exclude NULL-byte from length

include/win.c
There is probably a better way to do this...
I added a NYI comment
=> win: fzE_date_time add support for nano seconds

include/win.c, tests/process/test_process.fz, tests/process/test_process.fz.expected_out
added workaround for the issue that _empty_ env still contains HOME and TERM on windows/msys. Not sure why this is the case...
win.c: added last_error thread local like in posix.c to ensure we return the last_error we actually want to.
=> win: fix test process

include/fz.h, include/posix.c, include/win.c, modules/base/src/native.fz
windows GetLastError returns DWORD which is unsigned. So changing this to i64 to be able to contain this.
=> fuzion_rt: change fzE_last_error to i64

tests/uninitialized_field_negative/Makefile, tests/uninitialized_field_negative/uninitialized_field_negative.fz, tests/uninitialized_field_negative/uninitialized_field_negative.fz.expected_err, tests/visibility_scoping/visibility_scoping.fz
`test2` actually works, correctly complains about ambiguity of `b` and if `A.this.` or `C.this.` is added to solve this, correctly complains about uninitialized field in the first case.
`test7` is now issue #5085.
For `test8`, `fz` correctly complains about reading an uninitialized field.
=> tests: cleanup in visibility scoping

modules/base/src/time/calendar_duration.fz
also there was a bug in the logic of `calendar_duration.lteq`
=> fix merge incongruence

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Function.java, src/dev/flang/fe/SourceModule.java
With the null pointer fixed (#5129), the example from #5114 results in two additional errors on the argument count of the redefintion of Function.call not matching, which are just caused because `handDown` could did not operate properly.
Now, `handDown` uses a special empty array as result value in case it failed due to previous errors.
Also made the code in `Function` more robust against subsequent errors in case the argument count of a lambda does not match.
Fixed a missing `".\n"` in error for argument count mismatch in redefinition.
=> fe: suppress subsequent error on argument count in #5114

bin/aspell.dict, include/fz.h, include/posix.c, include/win.c, modules/base/src/envir/vars.fz, modules/base/src/fuzion/sys/env_vars.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java, tests/envir_vars/envir_vars.fz, tests/envir_vars/envir_vars.fz.expected_out
I don't see the point for this anymore, java does not have this either.
When starting a process we can give it a custom map of environment variables.
=> remove (un)setenv

tests/negative.mk
turns this
```
...
printf "RUN negative test reg_issue5095_pre_else_err.fz using jvm backend "; \
cat err.txt  | grep "should.flag.an.error" | sed "s ^.*\#  g" | sort -n | uniq | wc -l | tr -d ' ' | grep ^`cat *.fz | grep "should.flag.an.error"  | sed "s ^.*#  g"| sort -n | uniq | wc -l | tr -d ' '`$ > /dev/null && \
printf "\033[32;1mPASSED\033[0m.\n" || (printf "\033[31;1m*** FAILED ***\033[0m\n" && exit 1)
RUN negative test reg_issue5095_pre_else_err.fz using jvm backend PASSED.
...
```
into 
```
...
RUN negative test reg_issue5095_pre_else_err.fz using jvm backend PASSED.
...
```
=> build: suppress makefile output for cleaner output of negative tests

src/dev/flang/parser/Parser.java, tests/reg_issue5156/Makefile, tests/reg_issue5156/reg_issue5156.fz, tests/reg_issue5156/reg_issue5156.fz.expected_err
Added a test case even though this fix is trivial just because this error is not produced by any of the existing tests.
=> parser: Fix position for `AstErrors.qualifierExpectedForDotThis`, fix #5156

bin/run_tests.fz, modules/base/src/concur/sync.fz, modules/base/src/concur/thread_pool.fz, tests/lib_concur_sync/lib_concur_sync.fz
Appending lines from multiple threads only works on linux/macOS (not sure why/how). On windows opening the file fails like one would expect. So now we synchronize these writes manually.
=> run_tests: run append_line synchronized

bin/run_tests.fz
suggest to re-run or re-record only faild test in run_test script
Before all tests were suggested, see this [test run](https://github.com/tokiwa-software/fuzion/actions/runs/14793379925/job/41535152079?pr=5177)
```
...
549/552 tests passed, 2 skipped, 1 failed in 14m.
...
To re-run all failed tests, use this command:
make jvm -C ./build/tests/argumentcount_negative && make jvm -C ./build/tests/reg_issue1665_nested_lazy && make jvm -C ./build/tests/reg_issue874ff && make jvm -C ./build/tests/reg_issue2304 && make jvm -C ./build/tests/reg_issue2303 && make jvm -C ./build/tests/lib_choice_tag && make jvm -C ./build/tests/reg_issue102 && make jvm -C ./build/tests/reg_issue1572 && make jvm -C ./build/tests/reg_issue3648 && make jvm -C ./build/tests/reg_issue4694 && make jvm -C …
```
=> build: fix suggestion to re-run or re-record tests

include/win.c
=> win: fix heap corruption in build_unicode_args

bin/run_tests.fz
check_simple_example uses `OS` to determine if iconv hack needs to be used. (#2586)
=> run_tests: add `OS` env var to inherited env vars

bin/run_tests.fz
bash script has this, was still missing from run_tests.fz
=> run_tests: add `skip_win` feature

modules/base/src/random.fz
for `random.next_u64 u64.max` value `u64.max` is not possible as a result
=> lib: add features to get random number from full range of datatype

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Match.java, tests/reg_issue5197/Makefile, tests/reg_issue5197/reg_issue5197.fz, tests/reg_issue5197/reg_issue5197.fz.expected_out
both `visit`/`propagateExpectedType` modified field `_subject` resulting in a conflict.
fixes #5197
=> ast: Match, fix conflict in replacing subject field

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Types.java, tests/must_not_call_effect_finally/Makefile, tests/must_not_call_effect_finally/must_not_call_effect_finally.fz, tests/must_not_call_effect_finally/must_not_call_effect_finally.fz.expected_err
This is meant to ensures that `finally` is called exactly once when effect is deinstated.
=> ast: add error when calling effect.finally from user code

Makefile
Without this and an outdated fz_cmd.mod, I get an error due to incompatible module versions between fz_cmd.mod and base.mod.
=> make: Add missing dependency of apidocs on fz_cmd.mod

src/dev/flang/ast/AbstractType.java, tests/reg_issue2111/reg_issue2111.fz.expected_err
toString now emits e.g. just: `list.this` not `list.this list.A`
=> ast: omit generics for this type in toString

src/dev/flang/parser/Lexer.java, tests/reg_issue2386/reg_issue2386.fz.expected_err, tests/reg_issue5199_float_base_prefix/Makefile, tests/reg_issue5199_float_base_prefix/reg_issue5199_float_base_prefix.fz, tests/reg_issue5199_float_base_prefix/reg_issue5199_float_base_prefix.fz.expected_err
=> parser: require base prefix to be repeated after dot in float literals

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Box.java, src/dev/flang/ast/BuiltInType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/FreeType.java, src/dev/flang/ast/ParsedType.java, src/dev/flang/ast/QualThisType.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/ResolvedParametricType.java, src/dev/flang/ast/ResolvedType.java, src/dev/flang/ast/TypeMode.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fe/GenericType.java, src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fe/NormalType.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/lsp/shared/TypeTool.java, src/dev/flang/util/FuzionConstants.java, tests/reg_issue3648/reg_issue3648.fz.expected_err
`mode` of a type is one of `ThisType`, `RefType`, `ValueType`.
`AbstractType.mode` replaces the methods `isRef` and `isThisType`.
For an unresolved type ValueType is returned by mode().
=> ast: AbstractType replace refOrVal by mode

include/win.c
```
./build/include/win.c:159:74: error: passing 'int8_t *' (aka 'signed char *') to parameter of type 'LPSTR' (aka 'char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Werror,-Wpointer-sign]
159 |     int len = WideCharToMultiByte(CP_UTF8, 0, d->findData.cFileName, -1, result, sizeNeeded, NULL, NULL) - 1;
|                                                                          ^~~~~~
D:/a/_temp/msys64/ucrt64/include/stringapiset.h:42:121: note: passing argument to parameter 'lpMultiByteStr' here
42 |   WINBASEAPI int WINAPI WideCharToMultiByte (UINT CodePage, DWORD dwFlags, LPCWCH lpWideCharStr, int cchWideChar, LPSTR lpMultiByteStr, int cbMultiByte, LPCCH lpDefaultChar, LPBOOL lpUsedDefaultChar);
|             
```
=> fix windows build

modules/base/src/container/ordered_map.fz
Without this it was possible to create a map, that when printed would show
`(1 => one), (2 => two), (3 => drei), (3 => three), (4 => four), (5 => five)
`
=> lib: fix precondition of `container.ordered_map`

assets/docs/style.css, src/dev/flang/tools/docs/Html.java
Avoids strange line breaks, when content does not fit in horizontal space.
Use pilcrow (¶) to generate anchor links.
Changes this
into this
=> docs: api: improve alignment in feature list 

src/dev/flang/tools/docs/Html.java
[skip ci]
This avoids that comments that use indentation for readability get treated as code, e.g.
```
```
=> docs: require leading blank line for code blocks in comments

src/dev/flang/ast/InlineArray.java
sys.calledFeature().selfType() creates `fuzion.this.sys...` but we want `fuzion.sys...`
=> ast: InlineArray, fix target type

src/dev/flang/tools/docs/Html.java
The link of [`String` in module `terminal`](https://fuzion-lang.dev/docs/terminal#String_0) incorrectly points to the [`base` module page of `String`](https://fuzion-lang.dev/docs/base/String+%28no+arguments%29/) but it should point to the [version in `terminal`](https://fuzion-lang.dev/docs/terminal/String+(no+arguments)/) that only lists the features that `terminal` adds to `String`.
=> docs: fix links of base module feature displayed in other modules

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/ResolvedParametricType.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fe/GenericType.java, src/dev/flang/fe/LibraryType.java, src/dev/flang/fe/NormalType.java
removed all Type.visit implementation except for the one in AbstractType and LibraryType, LibraryType being a no-op.
=> fe: cleanup AbstractType.visit

modules/base/src/Functional.fz, modules/base/src/effect.fz, modules/base/src/net/connection.fz
before:
```
(io.buffered LM).reader read_handler 1024 ! ()->
(io.buffered LM).writer write_handler 1024 ! ()->
(net.channel desc) ! ()->
fn.call
```
after:
```
((io.buffered LM).reader read_handler 1024)
.and T _ (io.buffered LM).writer write_handler 1024)
.and (net.channel desc)
.call fn
```
=> lib: add means to compose effects more easily

modules/base/src/container/ordered_map.fz
The changes where done only as a workaround, since this-types did not work properly. Since they now work, we can revert the change.
fixes #3965
=> lib: partially revert #3963

modules/base/src/io/dir/read.fz, modules/base/src/mutate.fz, modules/base/src/time/nano.fz
Found this while working on detecting used effects of features.
e.g. here:
```
public read outcome String ! io.dir.read =>
```
would have correctly been:
```
public read outcome String ! dir.this.read =>
```
so I changed the implementations of the short-hands
=> lib: fix some types

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Feature.java, tests/choice_negative/choice_negative.fz.expected_err
This was done as a side-effect of `AbstractFeature.choiceGenerics()` resulting in the error being produced earlier or later in case `choiceGenerics()` was used in pre- or postconditions or for debugging.
=> ast: Move error checking for choice inheritance to dedicated method, fix #5539

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Case.java, src/dev/flang/ast/Context.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/FormalGenerics.java, src/dev/flang/fe/FeErrors.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/lsp/shared/TypeTool.java
no need to patch FormalGenerics anymore when adding typePar (freetype).
This will hopefully enable fixing all those open free-type bugs...
=> ast: formalgenerics, transparently use type args of feature

modules/base/src/String.fz, tests/check_simple_example.fz
This name is more intuitive and highlights the fact that the feature takes a predicate as an argument.
=> base/String: rename `fields_func` as `split_if`

src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/UnresolvedType.java
This change guarantees that ResolvedNormalTypes are valid in the sense the generics size match the backing feature. Generics in a ResolvedNormalType may still be unresolved though...
=> ast: enable precondition for matching generic sizes

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Case.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/FunctionReturnType.java, src/dev/flang/ast/IncompleteType.java, src/dev/flang/ast/ReturnType.java, src/dev/flang/ast/UnresolvedType.java
partially solves #5585
Before this patch, resultTypeIfPresentUrgent happily returned an incomplete type. This patch solves this by resolving _outer before asking for the functionReturnType.
I successfully ran HelloWorld with patch in #5585 applied with the caveat that I had to comment two features in base.fum. This means there is at least one more bug to solve before solving #5585
=> ast: resultTypeIfPresentUrgent, resolve outer on incomplete type

tests/modules/b.make
Comment was, does it still apply?:
```
When doing a 'run_tests', the paths in the error output contained
'--CURDIR__/../modules', where '/../modules' was redundant and caused an error.
```
=> revert cfe45d7, since this does not work on windows

src/dev/flang/fuir/analysis/dfa/Instance.java, tests/reg_issue5085/Makefile, tests/reg_issue5085/reg_issue5085.fz, tests/reg_issue5085/reg_issue5085.fz.expected_err
fixes #5085 
In the second pass of the DFA, fields are already written, so it can not be detected anymore that they are uninitialized.
=> fix reading uninitialized field

modules/http/src/http/canonical_header_map.fz
This has shown to be very useful when working with the module's API.
=> http: change visibility of `canonical_header_map.map_of`

tests/check_simple_example.fz
It displayed only `out` if `out` was erroneous but it should also show error if error-diff is none empty.
=> check_simple_example: show err/out if not okay

src/dev/flang/fuir/Clazz.java
It seems unnecessary since `_outer` always equal to `outerRef.resultClazz` and _outer being a final field.
=> fuir: cleanup remove `outer()`

src/dev/flang/ast/Feature.java
The original code called `result.resolve` repeatedly, which could result in endless recursion. This was fixed by a workaround in `Feature.typeInference` that also cached the result of `resultTypeIfPresentUrgent`. This PR now fixes the caching and removes the workaround.
View diff with white-space changes switched off since this is much clearer.
=> ast: Fix bug in caching of `Feature.resultTypeIfPresentUrgent`

README.md
=> add missing dependencies for `make all` to README

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fe/SourceModule.java, tests/visibility_modules_negative/main.fz.expected_err
This was a hack that appeared convinient, but it is nicer to have a dedicated constraint feature for type features.
=> fe: Do not abuse feature result as type parameter constraint

tests/check_simple_example.fz
Workaround because we can not setrlimit yet. Goal is to better understand why windows fails frequently.
=> check_simple_example, exit with failure after time limit exceeded

Makefile
fixes 
```
error 1: Incompatible module hashes encountered
Module LibraryModule for 'terminal' references module LibraryModule for 'base'
Expected hash: c410e32f9d9b1c4f01c278180c1f6acd
Actual hash  : ed8d1df504c1657a8ae7bb89c5933223
*** fatal errors encountered, stopping.
one error.
make: *** [Makefile:1152: build/tests] Error 1
```
=> makefile: add dependency to MOD_TERMINAL for target build/tests

bin/run_tests.fz
This is important when stderr output is be larger than pipe buffer size and also needs to be written/read before all stdout has been fully read. Currently a situation like the describe would just lead to blocking.
=> run_tests: record stdout/stderr in parallel instead of sequentially

examples/jitter/jitter.fz
This issue has been fixed in PR #5647
=> examples: Remove workaround for #5636 in examples/jitter

Makefile
=> makefile: don't use slash in phony targets, make `lint-pmd` phony

src/dev/flang/tools/docs/Html.java
e.g. [`monad.join`](https://fuzion-lang.dev/docs_git/base/monad+%282+arguments%29/join+%282+arguments%29/)
```
join(MMA type : monad MA MMA, a MMA) => MA
^^^^^^^^^^^^------------------ Hyperlink to monad
```
=> docs: add hyperlink to constraint of type parameters

modules/base/src/time/Clock.fz
currently Frontend does not show this error becuase #5786 is not merged yet.
examples/jitter/jitter.fz:116:22: error 1: Incompatible type parameter
_ := C.clock.run_periodic start period end run_one_release
---------------------^^^^^^^^^^^^
formal type parameter 'P : time.this.Period' with constraint 'C.Period' actual type parameter 'time.duration'
one error.
=> lib: fix soundness issue

Makefile
I got this error after doing `make clean`
```
❯ make base-only  
rm -rf build/modules/base
mkdir -p build/modules
cp -rf ./modules/base build/modules
./build/bin/fz -sourceDirs=./build/modules/base/src -XloadBaseModule=off -saveModule=build/modules/base.fum -XenableSetKeyword
+ build/modules/base.fum in 5718ms
./build/bin/fz -XXcheckIntrinsics
rm -rf build/modules/terminal
mkdir -p build/modules
cp -rf ./modules/terminal build/modules
./build/bin/fz -sourceDirs=./build/modules/terminal/src -saveModule=build/modules/terminal.fum
+ build/modules/terminal.fum in 631ms
./build/bin/fz -modules=terminal -c -o=build/bin/check_simple_example bin/check_simple_example.fz
clang: error: no such file or directory: '/home/simon/fuzion/build/include/shared.c'
clang: error: no such file or directory: …
```
=> Makefile: fix error caused by missing directory `build/include/`

src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/tools/Fuzion.java
output e.g.
```
Elapsed time for phases: prep 72ms, fe 150ms, createMIR 67ms, ir 7ms, dfa1 1309ms, dfa2 291ms, opt 3ms, be 466ms
```
=> timer: split dfa into dfa1 and dfa2

modules/base/src/container/hash_map.fz, modules/base/src/tuple.fz, tests/reg_issue5850_tuple_comparison/reg_issue5850_tuple_comparison.fz, tests/reg_issue5850_tuple_comparison/reg_issue5850_tuple_comparison.fz.expected_out
Add test cases to `reg_issue5850` using `hash_map` of tuples.
Changes arguments to `container.hash_map` to be `Sequence` not `array` for convenience.
=> base: make `tuple` inherit `property.hashable`

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/ArrayData.java, src/dev/flang/be/interpreter/ChoiceIdAsRef.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/SpecialClazzes.java
Array has a type parameter, so this is now wrong since there could be many different `c_Array` clazzes. This is the reason that #5881 currently fails.
=> fuir: remove special clazz `c_Array`

src/dev/flang/ast/AbstractCall.java, src/dev/flang/ast/Call.java
The original code was using `whenResolvedTypes` which was useless since in case the formal argument type was not resolved yet, the result of the delayed call to `resolveFormalArg` would have been lost (stored in `result[0]` after we had returned from `resolveFormalArgumentTypes`).
Now, I added a check that the types are actually resolved already and removed the `whenResolvedTypes` call.
This is  a first step for #5895.
=> ast: do not use `whenResolvedTypes` in `resolveFormalArgumentTypes`

src/dev/flang/ast/Feature.java
I had a really hard time reading this code...
Also used backticks instead of double quotes.
=> ast: cleanup: fix comment with outdated Fuzion lambda syntax

modules/base/src/container/abstract_array.fz
redefining `drop` is then unnecessary
=> lib: fix slice of slice by redefining slice in arrayslice

Dockerfile
This is a best practice with Docker [1].
[1]: https://docs.docker.com/build/building/best-practices/#apt-get
=> Dockerfile: run `apt-get` in a single line again

modules/base/src/String.fz
looks like a merge broke the repo due to this.
=> base: fix calls to `as_codepoints` which must be `codepoints`

bin/run_tests.fz
more useful than log-scale histogram
```
---  jvm  ---                                 
count
64  |   ▉▉  |       |       |       |       |       |       |       |       |
32  |  ▉▉▉▉▉▉▉▉▉▉   |       |       |       |       |       |       |       |
16 _|__▉▉▉▉▉▉▉▉▉▉▉▉_|_______|_______|_______|_______|_______|_______|_      |
8  |  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉      |       |       |       |       |       |       |
4  |  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉   |       |       |       |       |       |       |
2  |▉ ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ ▉    ▉  |       |       |       |       |       |
1 _|▉_▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉___▉▉__|_▉__▉__|______▉|_______|_▉_____▉_      |
|       |       |       |       |       |       |       |       |       |
1138ms   10s     19s     28s     37s     46s     55s     64s     74s      >
average | …
```
=> run_tests: histogram, add arg max_recorded

bin/ebnf.fz, modules/base/src/Sequence/equatable.fz, modules/base/src/interval.fz, modules/base/src/io/buffered/reader.fz, modules/base/src/option.fz, tests/lib_property_equatable/lib_property_equatable.fz, tests/lib_property_equatable/lib_property_equatable.fz.expected_out, tests/strings/stringstest.fz
Doing this similar to the way it is done for `tuple` with `compile_time_panic` in case the underlying type `T` is not `orderable` or `hashable`, respectively.
=> base: make `option` `orderable` and `hashable`
