- src/dev/flang/parser/OpExpr.java
makes the following example work without needing braces for the fractions:
if 1⁄1 > 1⁄2
say "yes"
> add precedence definition for the fraction operator: ⁄

- Makefile
- src/dev/flang/fe/FrontEnd.java
- javac, force utf8 encoding of source files
- workaround for error when calling fzjava from Makefile
- changed algorithm for finding fuzion home dir via FrontEnd.class file
> FIX build on windows (mingw)

- src/dev/flang/tools/Pretty.java
- src/dev/flang/util/SourceFile.java
fixes pretty printing of files with utf8-chars like this one: ∘
> Pretty.print(): iterate source file by codepoints not by bytes

- src/dev/flang/tools/fzjava/ForClass.java
- was broken since and because of renaming List to Sequence
- error was: Type 'List' was not found, no corresponding feature nor formal generic argument exists
> fzjava: fix generation of fuzion features for java modules ()

- bin/ebnf.sh
- src/dev/flang/parser/Lexer.java
- add some missing lexer grammar rules
- fix antlr warnings: `non-fragment lexer rule ... can match the empty string`
> ebnf.sh: move parser before lexer rules

- lib/Sequence.fz
- reused existing function lists.empty<T> for implementation
> lib/Sequence: simplified Sequences.empty

- lib/string.fz
foundation for idiom 283:
https://www.programming-idioms.org/idiom/283/split-with-a-custom-string-separator
> stdlib: string added feature split at string

- src/dev/flang/ast/Box.java
- in the special case the formaltype of the expression is a generic argument
- closes #194 
with fix below example in #194 results in:
```
/home/sam/Downloads/asdf.fz:16:19: error 1: Incompatible types in assignment
b.map<T>(m -> m)
------------------^
assignment to field : 'ex.a.#fun0.call.result'
expected formal type: 'ex.a.T'
actual type found   : 'Monoid<ex.a.T>'
assignable to       : 'Monoid<ex.a.T>'
for value assigned  : '{
box(call.this.m)
}'
To solve this, you could change the type of the target 'ex.a.#fun0.call.result' to 'Monoid<ex.a.T>' or convert the type of the assigned value to 'ex.a.T'.
one error.
```
> ast: Fix precondition when boxing a value

- src/dev/flang/fe/FrontEndOptions.java
- if main feature ends with (fz, fu, ...) assume it must be a file and error if it does not exist
- this is in contrast to previous behaviour where the current dir was then searched for a feature with given name
> fe: error if main_feature.fz does not exist

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/NumLiteral.java
- only when float is given in a base which is a multiple of 2
Example output:
```
/home/not_synced/openvscode-server-fuzion/vscode-fuzion/fuzion-lsp-server/fuzion/asdf7.fz:111:35: error 1: Loss of precision for: -0x0.1P-146
say "{(f32 -0x0.2P-146) == (f32 -0x0.1P-146)}"
----------------------------------^
Expected number given in base 16 to fit into f32 without loss of precision.
```
> ast: error on loss of precision for floating point numbers

- lib/codepoints.fz
I'm unsure if this is a good way to do it.
I mapped the u32 sequence to a codepoint sequence because this seemed more useful to me?
Maybe it also makes sense to make it lazy via list?
> lib/codepoints: added definitions for latin alphabet and arabic numeral

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Type.java
This is used by both the fuziondoc and the language server.
> ast: type change visibility of name() to public

- lib/f32.fz
- lib/f64.fz
- lib/float.fz
from_i64 does not require an instance.
I think it was a mistake to have added it to float instead of floats.
> lib/float: move from_i64 from float to floats, added comments

- lib/list.fz
This avoids creating the tail of the list after the last taken element.
> lib/list: take n, avoid creating tail

- src/dev/flang/tools/AceMode.java
- numeric literals are now coloured
before:
after:
> acemode: improvements for syntax hightlighting

- src/dev/flang/fuir/FUIR.java
this example triggers the post condition:
```
ex =>
e is
b is
l choice<i32,b> := b
d(c ref e) is
match c.l
aa i32 => say aa
bb b => say bb
call =>
d e.this
e.call
```
> fuir: ensure matchCaseTags is not empty

- src/dev/flang/util/SourceFile.java
- src/dev/flang/util/SourcePosition.java
@fridis: This fix may have some performance implications since `codePointInLine()` is called in the Lexer quite often. 
Put differently, I'm open to suggestions to fix this bug in a better way.
> util: SourceFile.codePointInLine erroneously returned byte-Index

- src/dev/flang/util/SourceFile.java
The PR yesterday introduced a minor bug that hit me when running the tests of the language server. Turns out `line` can take the special value 0. Then lineStartPos() crashes with an out of index exception.
> util: fix ArrayIndexOutOfBoundsException for empty source files

- lib/mapOf.fz
example usage: mapOf [(key1, value1), (key2, value2)]
> lib/mapof: init map with array of key value tuples:

- lib/fuzion/std/in.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
return -1 at end of file, -2 for any other error
> lib/stdin: refine error codes of `nextByte`

- lib/array2.fz
- lib/array3.fz
- lib/string.fz
```
ex =>
cnt := mut 0
get => cnt <- cnt.get + 1; cnt.get
say (array2 3 2 ((_,_) -> get))
say "=="
say (array3 6 3 2 ((_,_,_) -> get))
```
output:
```
[
[1,2],
[3,4],
[5,6]
]
==
[
[
[7,8],
[9,10],
[11,12]
],
[
[13,14],
[15,16],
[17,18]
],
[
[19,20],
[21,22],
[23,24]
],
[
[25,26],
[27,28],
[29,30]
],
[
[31,32],
[33,34],
[35,36]
],
[
[37,38],
[39,40],
[41,42]
]
]
```
> lib/array[n]: change asString to improve readability

- src/dev/flang/ast/Call.java
this fixes a null pointer exception for the following - broken - code:
```
private CNode<CTK: hasHash<CTK>,CTV>(bmp u32, array array<Branch<CTK,CTV>>) is
private CTrie<CTK: hasHash<CTK>, CTV>(root choice<INode<CTK,CTV>, RDCSS_Descriptor>, read_only bool) ref : map<CTK, CTV>
is
private compress(cn CNode<CTK,CTV>, lev u32, gen i32) =>
narr := cn.array.map<Branch<CTK,CTV>> (n -> match n
m INode =>
match m.GCAS_READ(CTrie.this).data
// resurrect
tn TNode<CTK,CTV> => tn.sn
* => m
sn SNode => sn
)
contract (CNode CTK CTV> cn.bmp narr) lev gen
#------------------>       <-------------------------- the issue, missing < triggers the issue
```
> ast: call.splitOffTypeArgs, add only none null types to generics list.

- lib/stream.fz
- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
I'm sure there is a better way to do this! :-)
So I don't expect this PR to be merged but to be a starting point to fix stream.asString.
Without the fix the compiler would run into an infinite loop, creating clazzes like:
```
ref list<u8>.ref asStream.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.map<string>.ref @726549.fromStream.ref @730058.head
```
`ref @726549` is the arg f given to map.
> air: fix an issue that resulted in a cycle when creating clazzes.

- src/dev/flang/ast/AbstractType.java
when building base.fum the check condition fails in the following cases:
```
Expression : function FEATURE: INVISIBLE  call(LOCAL i32 i) : Object{
"  ".infix +(box(deref(deref(call.this.#^array2.asString.#fun4.call.#^array2.asString.#fun4).#^array2.asString).slice(call.this.i.infix *(deref(deref(call.this.#^array2.asString.#fun4.call.#^array2.asString.#fun4).#^array2.asString).length1), call.this.i.infix +(1).infix *(deref(deref(call.this.#^array2.asString.#fun4.call.#^array2.asString.#fun4).#^array2.asString).length1))))
}
Type: Function<string, i32>
===
Expression : function FEATURE: INVISIBLE  call(LOCAL i32 i) : Object{
deref(call.this.#^array3.asString.#fun5.call.#^array3.asString.#fun5).dim_1(call.this.i)
}
Type: Function<string, i32>
===
Expression : function FEATURE: INVISIBLE …
```
> ast: isAssignableFrom remove failing check condition

- lib/cache.fz
```
ex is
say (cache string (() -> say "creating result1"; "the result"))
say (cache string (() -> say "creating result2"; "the result"))
#
```
> lib: cache feature, enabling some kind of global state

- src/dev/flang/ast/FormalGenerics.java
Example result:
```
In call to 'tya_field.foo2', no actual generic parameters are given and inference of the generic parameters failed.
Expected generic parameters: 'S, T'
Type inference failed for 2 generic arguments 'S', 'T'
```
> ast: formal generics update toString to new-style generics.

- lib/envir/args.fz
this makes args easier to consume.
> lib/args: inherit from searchable list instead of array.

- src/dev/flang/parser/Parser.java
this led to a warning during build
> parser: fix spelling issue in antlr grammar

- lib/fuzion/std/fileio.fz
- src/dev/flang/be/interpreter/Intrinsics.java
fuzion.std.fileio.move now returns an outcome unit in case of success and error in case of failure
> adding error handling to the fileio.move/rename feature

- lib/fuzion/std/fileio.fz
- lib/io/file/read.fz
fuzion.std.fileio.get_file_size is now wrapped in an outcome i64 to handle errors
fileio.read now uses a match statement to handle the errors generated by the get_file_size used to allocate the array representing the file content.
> Fileio/stat adding error handling to the get_file_size feature

- lib/fuzion/std/fileio.fz
- src/dev/flang/be/interpreter/Intrinsics.java
fuzion.std.fileio.create_dir now returns outcome unit
in case of successful creation a unit type will be returned and in case of failure an error will be the outcome
> adding error handling to fileio.create_dir

- lib/int.fz
"...using modifier 'redef'"
the underlying reason for this error is that in numeric `infix !=` is no longer abstract
> fix compilation "Redefinition must be declared..."

- lib/string.fz
@fridis I think this should also prevent quadratic performance when concatenating strings since in the end two lists are lazily being concatenated. This fix does not really explain why the previous code for concatenation failed. I suspect there is an issue in marray.add but I did not investigate thoroughly yet.
> lib/string: fix string concat

- lib/io/stdin.fz
This broke when string.asCodepoints was changed to return a list instead of a stream
> lib: fix stdin.read

- lib/Sequence.fz
example:
```
ex =>
say (["one","two", "three"]
.indexed
.mapSequence (x ->
(idx, str) := x
"$idx $str"
))
```
result:
`[0 one,1 two,2 three]`
> lib: sequence add feature `indexed`

- lib/int.fz
- lib/string.fz
- lib/uint.fz
Simple measurements suggest that for large numbers this make asString roughly 10 times faster:
```
ex is
a := (int 3)**(int 247)
say (bench (() -> say a) 10000)
```
> lib: uint.asString improved performance

- bin/run_tests.sh
- bin/run_tests_parallel.sh
example:
```
sam@debian /home/not_synced/fuzion (main)130$ make run_tests
testing interpreter: ...^C
./build/tests/abstractfeatures_negative/: ok
./build/tests/argumentcount_negative/: ok
./build/tests/assignment_negative/: ok
make: [Makefile:415: run_tests_int] Error 130 (ignored)
```
> interrupting test run leads to printing of intermediate results.

- tests/modules/Makefile
- tests/modules/b.make
- tests/modules/src/test_modules.fz.expected_err
- tests/modules/src/test_modules.fz.expected_err_c
This is using a separate makefile 'b.make' that itself uses 'simple.mk' to compare output with expected output.  Expected output is an error.
> tests: Add modules/b to make sure indirectly imported features are not visible, fix #484

- lib/fuzion/std/args.fz
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/tools/Fuzion.java
- src/dev/flang/util/FuzionOptions.java
Make the `envir.args` effect work with the interpreter backend. Arguments can be passed as follows:
```
fz feature.fz -- arg1 arg2 arg3...
```
Fixes #468.
> be/interpreter: implement fuzion.std.args.* intrinsics

- bin/ebnf.sh
- bin/fz
- bin/fzjava
- bin/run_tests.sh
- bin/run_tests_parallel.sh
- tests/_cur_dir.sh
- tests/check_simple_example.sh
- tests/check_simple_example_c.sh
- tests/record_simple_example.sh
- tests/record_simple_example_c.sh
> Running a command through /usr/bin/env has the benefit of looking for whatever the default version of the program is in your current environment.
> 
> This way, you don't have to look for it in a specific place on the system, as those paths may be in different locations on different systems. As long as it's in your path, it will find it.
> 
> One downside is that you will be unable to pass more than one argument (e.g. you will be unable to write /usr/bin/env awk -f) if you wish to support Linux, as [POSIX is vague](https://unix.stackexchange.com/a/399702/6252) on how the line is to be interpreted, and Linux interprets everything after the first space to denote a single argument. You can use /usr/bin/env -S on some versions of env to get around this, but then the script will become even …
> scripts: use /usr/bin/env bash; set -euo pipefail

- tests/modules/b.make
When doing a 'run_tests', the paths in the error output contained '--CURDIR__/../modules', where '/../modules' was redundant and caused an error.
> tests: fixed path problems sub-makefile

- src/dev/flang/parser/Lexer.java
> parser: fix validation of uppercase letters in numeric constants

- examples/webserver/webserver.fz
The webserver can be started with:
```
fz -unsafeIntrinsics=on -modules=java.base examples/webserver/webserver.fz
```
> examples/webserver: fix some syntax errors

- bin/run_tests.sh
Before this change, when no tests failed, grepping for failed in the results would return 0 and exit with status 1. This would cause the Makefile report an error when there is none.
> tests: fix the case when no tests fail

- lib/outcome.fz
Resolves part of #504. Tests (more or less from Rust docs mentioned in #504):
```
test_outcome_and is
a outcome u32 := u32 2
b outcome string := error "late error"
match (a.and b)
e error => say e
s string => say s
c outcome u32 := error "early error"
d outcome string := "foo"
match (c.and d)
e error => say e
s string => say s
e outcome u32 := error "not a 2"
f outcome string := error "late error"
match (e.and f)
e error => say e
s string => say s
g outcome u32 := u32 2
h outcome string := "different result type"
match (g.and h)
e error => say e
s string => say s
```
```
test_outcome_and is
a outcome u32 := u32 2
b outcome u32 := error "late error"
match (a.or b)
e error => say e
s u32 => say s
c outcome u32 := error "early error"
d outcome u32 := u32 2
match (c.or d)
e error => say e
s …
```
> lib/outcome: add and and or

- src/dev/flang/be/interpreter/Interpreter.java
I think it is not the case (anymore) that result might be null in case getField() is used on choice type.
> int: remove postcondition, result of choice must not be null (anymore)

- src/dev/flang/ast/Resolution.java
```
ex =>
ident : choice unit nil is
redef asString =>
match another_ident.this
* =>
```
> ast: fix ensure condition failure

- Makefile
- bin/fzjava
- src/dev/flang/fe/FrontEnd.java
- src/dev/flang/tools/Fuzion.java
- src/dev/flang/tools/FuzionHome.java
- src/dev/flang/tools/fzjava/FZJava.java
- src/dev/flang/tools/fzjava/FZJavaOptions.java
- src/dev/flang/tools/fzjava/ForClass.java
My current working state of a fix for issue #463. It works already, hence the 'rm's have been removed from the Makefile, except for one:
```bash
rm -f $(BUILD_DIR)/modules/java.desktop/Java/java/awt_pkg.fz
```
It seems that this file does not even get generated without this change. Perhaps it's just wrong copy and paste from java.datatransfer?
Fixes #463.
> fzjava: do not generate duplicate features

- lib/Type.fz
- lib/equals.fz
- lib/string.fz
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/be/interpreter/Interpreter.java
- src/dev/flang/util/FuzionConstants.java
- tests/equals/Makefile
- tests/equals/test_equals.fz
- tests/equals/test_equals.fz.expected_out
The type feature f.type of a feature f now inherits from Type_STATIC and f's non-static type feature, which itself inherits from all of f's parents' type features:
```
f : g, h
```
then
```
Type
A
|
Object.type (dyn)
A  A
|  |
+----------+  +---------+            Type_STATIC
|                       |               A
g.type (dyn)            h.type(dyn)        |
A                       A               |
|                       |               |
+--------+   +----------+               |
|   |                          |
f.type (dyn)                     |
A                            |
|                            |
+-------+  +-----------------+
|  |
f.type (static)
```
Not shown are g.type (static) and h.type (static) that inherit from g.type (dyn) / h.type (dyn), resp., and Type_STATIC …
> fe/lib: Add Type_STATIC as direct parent of type features

- lib/concur/thread.fz
- lib/envir/vars.fz
- lib/exit.fz
- lib/io/err.fz
- lib/io/out.fz
- lib/io/printEffect.fz
- lib/io/stdin.fz
- lib/panic.fz
- lib/random.fz
- lib/time/nano.fz
Use the new `Upper_Case` style. This does not rename the notable ref types map, string, and stream.
For `simple_random`, `time_seeded_random`, and `Exit_Handler`, `flang_dev` needs to be adapted.
> lib: rename ref types

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/If.java
- tests/typeinference_negative/typeinference_negative.fz
Before, tail recursion flag was set explicitly for loops that are known to be tail recursive.  Now, this is detected automagically.
> fe: Add automatic detection of tail recursive calls

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Loop.java
This flag is not needed any longer and the check that uses it never failed when running tests, examples and idioms.
A saved part of the comment for this flag since that might be useful to understand how type inference for tail recurive features works.
> ast: remove Call._isTailRecursive

- src/dev/flang/ast/Call.java
- tests/equals/test_equals.fz
- tests/equals/test_equals.fz.expected_out
For an infix, prefix or postfix operator call of the form
```
a ⨁ b     -- or --
⨁ a       -- or --
a ⨁
```   
that was not found within the target 'a', try to find this operator in 'this' or any outer feature.  If found in X.Y.Z.this, then convert this call into
```
X.Y.Z.this.infix  ⨁ a b     -- or --
X.Y.Z.this.prefix ⨁ a       -- or --
X.Y.Z.this.postix ⨁ a       ,
```
> fe: for operator calls, look for called feature in outer features

- src/dev/flang/ast/Call.java
- tests/equals/test_equals.fz
- tests/equals/test_equals.fz.expected_out
Permit chained boolean expressions for infix operators with 2 arguments
This enables chained booleans for infix operators declared in outer features
such as
```
infix ≟(T type, a, b T) => equals T a b
```
defined in the universe.
> Chained bool for infix with two args

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Function.java
- src/dev/flang/fe/LibraryOut.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/OpExpr.java
Also made code `AbstractFeature.typeFeaturesNonStaticParent()` robust against previous compilation errors.
> Add underscore to fields in Call

- tests/equals_negative/Makefile
- tests/equals_negative/equals_test_negative.fz
Should flag an error when 'equality' is not provided, but 'equals' is used.
> tests: Add negative test for equality

- lib/bitset.fz
If one of the arguments is the empty bitset, then highest will be nil, and hence the bind operator in the definition of h will make the result nil as well. However, this does not mean that both bitsets are empty. Add the missing check for this case.
Fixes #638.
> lib/bitset: fix equality when one of the arguments is empty

- lib/envir/vars.fz
- lib/fuzion/sys/env_vars.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
- tests/envir_vars/Makefile
- tests/envir_vars/envir_vars.fz
- tests/envir_vars/envir_vars.fz.expected_out
Addresses #609 
There is no implementation in Java as Java does not provide a possibility to change the environment variables. Even calling to C code does not help with that as apparently the environment is cached when the JVM starts. Subsequent calls to `System.getenv` would not return the updated value.
> lib/envir/vars: implement set and unset

- src/dev/flang/parser/OpExpr.java
This works:
```
true & a = b
```
Previously however, this did not work:
```
true & a ≟ b
```
Instead it was necessary to mark the precedence of the equality check manually. Hence we adjust the precedence of ≟ to be the same as =.
Fixes #647.
> parser/OpExpr: adjust precedence for ≟

- src/dev/flang/ast/Call.java
This change is necessary/useful for the language server.
> ast: Call.findOperatorOnOuter. reset to oldTarget if not found

- src/dev/flang/ast/Tag.java
example that failed:
```
towers is
numOrNil i32|nil := nil
s
pre
match numOrNil
nil => true
num i32 => num.
is
```
> ast: Tag, relax precondition in case of errors

- lib/try.fz
Remove a semicolon that was probably forgotten when moving from the old code style to the modern code style.
> lib/try: remove a leftover semicolon

- Makefile
This allows passing FUZION_BIN_BASH=/path/to/bin/bash to make in the case that /bin/bash does not exist, such as on NixOS.
> Makefile: do not hardcode /bin/bash

- src/dev/flang/be/c/C.java
__thread is a non-standard GCC extension. It caused problems when building Fuzion programs on Windows, see #661. Use _Thread_local from the C11 standard instead. According to a Stack Overflow post [1], this should work.
**Note:** this seems to not break anything on Linux, but I have not tested it on Windows.
[1]: https://stackoverflow.com/questions/32245103/how-does-the-gcc-thread-work
> be/c: use _Thread_local instead of __thread

- lib/has_equality.fz
- lib/string.fz
- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
- src/dev/flang/fe/Module.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/FuzionConstants.java
This adds a new feature 'has_equality' that onle defines a type feature 'has_equality.type.equality2'.  This feature uses the type itself via the type parameter 'THIS_TYPE'.
'string' now inherits 'has_equality' and 'string.type' redefines 'equality2'. Any feature inheriting 'has_equality' can make the type feature 'equality2' available.
For this to work, type features now have a type parameter 'THIS_TYPE' that presents the actual type. This type parameter can be used in type features.
To do:
- make all features that provide type.equality inherit from has_equality
- add some syntax for 'THIS_TYPE', e.g. 'this.type' or similar
- make 'THIS_TYPE' an internal name '#THIS_TYPE'
- add support for types with with parameters, e.g., 'option T'
> fe/air: Add support for inheriting features defined in type features

- lib/Type.fz
- lib/bitset.fz
- lib/bool.fz
- lib/equals.fz
- lib/f32.fz
- lib/f64.fz
- lib/has_equality.fz
- lib/i16.fz
- lib/i32.fz
- lib/i64.fz
- lib/i8.fz
- lib/int.fz
- lib/partiallyOrdered.fz
- lib/string.fz
- lib/u128.fz
- lib/u16.fz
- lib/u32.fz
- lib/u64.fz
- lib/uint.fz
- tests/equals/test_equals.fz
- tests/equals_negative/equals_test_negative.fz
Added parent `has_equality` to features that provide `type.equality`.
Renames `has_equality.type.equality2` as `has_equalty.type.equality`. Removed `equals2' and 'infix ≟≟`, move the code to `equals` and `infix ≟`.
In declarations
```
abc ... is
...
abc.type.equality(a, b abc) => ...'
```
removed the redundant 'abc.', such that they are
```
abc ... is
...
type.equality(a, b abc) => ...'
```
Updated tests. Luckily, this change improves the error message location in tests/equals_negative.
> lib/tests: Replaced Type_STATIC.equality by has_equality.type.equality

- src/dev/flang/tools/fzjava/FZJava.java
- src/dev/flang/tools/fzjava/FeatureWriter.java
Previously, fzjava would put the Fuzion features for all given modules in a single directory. Now, if more than one module is given, we put the Fuzion features for a Java module x into dest/x, for a Java module y into dest/y, and so on, where dest is the destination directory given by the -to command line argument.
We do not address the case where the given modules may depend on each other, and hence might contain duplicate features afterwards. In this case, building the first module as a single module, then compiling it into a fum file, and then loading the fum file with -modules is still necessary to avoid duplicate features.
Closes #599.
> tools/fzjava: when building multiple modules, separate them

- lib/Sequence.fz
- lib/list.fz
Previously it was unclear which elements would actually be filtered.
> Sequence, list: clarify documentation for filter

- lib/Sequence.fz
this will also help when we want an index of a type other than i32
> lib: Sequence.indexed, add variant allowing choose start_idx

- src/dev/flang/ast/AstErrors.java
> ast: remove `set` suggestion in error when using result as feature name

- lib/i32.fz
- lib/numeric.fz
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Consts.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/Parser.java
A type feature declared as 'dyn' will be added to the non-static type feature, i.e., all type features of heir features will inherit it even if it is not abstract.
This permits implementing something like 'numerics.from_u32' in 'numeric.type.from_u32'.  However, this does not work yet since 'numeric.T' is incompatible with 'numeric.type.THIS_TYPE', so operations are not possible yet.
This is one small step towards solving #706.
> lib/fe: Add 'dyn' keyword for non-static type features

- src/dev/flang/ast/Consts.java
- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/Parser.java
This is the opposite of 'dyn', maybe gonna drop 'dyn' later.
> parser: add 'fixed' moidifier for methods

- src/dev/flang/fe/FrontEnd.java
- src/dev/flang/fe/LibraryFeature.java
- src/dev/flang/fe/LibraryModule.java
LibraryFeature.compareTo compared the local indices, which are not unique in case there are several module files.
This patch introduces code to convert local indices in module files into global indices and uses these global indices for LibraryFeature.compareTo.
A large offset is added to global indices such that accidental use of the wrong index type will very likely result in an illegal index.
> fe: Fix LibraryFeature.compareTo to work with several modules

- lib/unit.fz
This feature implements a Monoid of unit that essentially does not do anything, however it can be used when a `Monoid unit` type is expected, such as in some calls to `fold`.
Fixes #686.
> lib/unit: provide a unit.type.monoid feature

- tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/issue698.fz.expected_err
Pull request #699 introduced this test which depends on the error message that was changed in #702. Fix the test by re-recording it with the new error message.
> tests/reg_issue698: fix failure caused by merging conflicting PRs

- lib/list.fz
When the mapping function returned an empty sequence, list.flatMap would consider the list as terminated rather than continuing with other, possibly non-empty elements.
Fixes #733.
> lib/list: fix flatMap handling of empty sequences

- lib/effect.fz
'mode' in the old code always resulted in 'plain' or 'repl', causing 'use0' to always fail on its precondition.  The idea is that 'use0' is used on an effect that was just created but not installed when created, i.e., 'new'.
> lib: Fix precondition of effect.use0

- lib/string.fz
- lib/uint.fz
This makes it clear that we are working on a codepoint level rather than the byte level here.
> string: rename pad_start to pad_codepoint_start

- lib/marray.fz
There are only few places left where streams are present in the std lib:
- array, asStream could be deleted because it also implements asList
- hasInterval, would need re implementation using list
- integer, #734 would change this
- stdin, #567 would change this
- Sequence,  ~4-5 features would need change of implementation
The biggest blocker for removing streams is actually `Loop.java` which uses stream quite extensively.
> lib/marray: implement sequence via asList instead of asStream

- src/dev/flang/ast/AbstractFeature.java
Would cause NullPointerException since findInheritanceChain can return null.
> ast: Make AbstractFeature.handDown robust against previous errors

- src/dev/flang/ast/Unbox.java
There was special handling for choice types that was never used, while some special handling for this type is needed when accessing outer refs (even though this might be done in a nicer way).
> ast: Cleanup complex code in Unbox.box, fix #738

- lib/list.fz
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Type.java
You cannot inherit from a choice type anyways, so 'this.type' of a choice type is just that choice type.
> lib/fe: Make 'this.type' for choice type c equal to c, fix #736

- src/dev/flang/ast/This.java
For some reason, there are still cases where the constructor for Type has revert a this.type into the plain type, need to check why.
> fe: In a.b.c.this, do not create `this.type` for `a.b`, improve #737

- bin/run_tests.sh
- bin/run_tests_parallel.sh
This avoids printing previous and maybe outdated failure output repeatedly.
> scripts: Remove run_tests.failures files

- lib/Sequence.fz
- lib/list.fz
- lib/sum.fz
It is equivalent to `head.get`.
Fixes #679.
> lib/list: remove forceHead

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/Consts.java
- src/dev/flang/ast/This.java
- src/dev/flang/fe/LibraryFeature.java
- src/dev/flang/fe/LibraryModule.java
- src/dev/flang/fe/LibraryOut.java
- src/dev/flang/fe/Module.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/Parser.java
- src/dev/flang/util/FuzionConstants.java
- tests/this_type/skip_int
- tests/this_type/test_this_type.fz
- tests/this_type/test_this_type.fz.expected_out
- tests/this_type_negative/Makefile
- tests/this_type_negative/test_this_type_negative.fz
The parser method for rule 'qualThis' has been modified to procude a 'List<String>' or 'Type' depending on where it is used.
Type 'a.this.type' is can be used in an inner feature of 'a' only for assginments from any value that is also 'a.this.type' or that is 'a.this'. In an heir feature 'b' that inherits from 'a', redefinitions must replace 'a.this.type' by 'b.this.type'.
Modifier 'fixed' can be used to mark a feature that will not be inherited by heirs.  This is useful in 'b' that inherits from 'a' to provide an implementation of an inherited feature with argument or result type 'a.this.type' since this type can then be replaced by 'b'.
Fixed equal value for dev.flang.ast.Const.MODIFIER_FIXED and MODIFIER_DYN. Added MODIFIER_FIXED to module file.
test/thisType now checks more cases: …
> fe: Support 'a.this.type' as type for args/results with covariant redefinition, add 'fixed' features

- src/dev/flang/be/c/Intrinsics.java
We do have file I/O intrinsics implemented now, so this is no longer relevant.
> be/c: remove noFileIo placeholder intrinsic

- lib/Type.fz
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/SrcModule.java
- src/dev/flang/fe/Module.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/FuzionConstants.java
Fix 'fixed' features, the inheritance structure of type features can be simplified since 'fixed' no longer need to be part of the static type feature, there is no need for these any more.
This avoids a lot of special handling for static vs. nonStatic type features.
> lib/fe: remove TYPE_STATIC

- lib/list.fz
`prepend_to_all` adds an element `sep` in front of every element of a list, `intersperse` adds an element `sep` only in between elements of a list.
> lib/list: add prepend_to_all and intersperse features

- src/dev/flang/tools/docs/Html.java
- src/dev/flang/tools/docs/Util.java
A block of code is being detected in a comment when there is a continous block of lines that are indented five spaces from the # (or four spaces from where the text begins, when you separate the # and the text with a single space). The code is then inserted into a runcode wrapper which will be displayed on flang.dev as a box containing executable and modifiable code.
Currently, this is only useful when the docs generated by fzdocs are being included on flang.dev, as the necessary CSS and JavaScript stuff is missing otherwise.
Link: https://git.tokiwa.software/tokiwa/flang_dev/issues/110
> docs: detect code in comments and convert it to runcode box

- src/dev/flang/parser/Parser.java
- tests/reg_issue440_incomplete_else_block_confusing_error_message/Makefile
- tests/reg_issue440_incomplete_else_block_confusing_error_message/issue440.fz
> parser: do not use empty blocks as else blocks.

- Makefile
If `build/tests/` already existed when this target was run, `cp` would create a second folder `build/tests/tests` inside it. Now, the folder is completely removed first, so that any leftover files are removed and all tests get updated.
> Makefile: actually replace build/tests directory

- src/dev/flang/air/Clazz.java
- src/dev/flang/be/interpreter/Instance.java
- src/dev/flang/be/interpreter/Interpreter.java
Since isAssignableFrom has been marked as deprecated and these are the only two places where it was used, we also remove the isAssignableFrom method in Clazz.
> be/int: replace isAssignableFrom with isDirectlyAssignableFrom

- lib/searchableSequence.fz
- lib/searchablelist.fz
- lib/string.fz
Given a limit, replace will only replace the first n occurrences of the sub-list to be replaced. Also, we add the same variants to the replace features of searchableSequence and string.
> lib/searchablelist: add a variant of replace with a limit

- Makefile
I use `make without-java-modules` almost exclusively. That is why I want to suggest this shorter label for the target.
> Makefile: rename target without-java-modules to no-java

- src/dev/flang/fe/LibraryModule.java
- src/dev/flang/fe/ModuleRef.java
Stacktrace:
```
dev.flang.fe.LibraryModule.libraryFeature(LibraryModule.java:323)
dev.flang.fe.LibraryModule.type(LibraryModule.java:447)
dev.flang.fe.LibraryFeature.resultType(LibraryFeature.java:464)
dev.flang.shared.FeatureTool.IsInternal(FeatureTool.java:236)
dev.flang.shared.CallTool.lambda$static$0(CallTool.java:54)
```
> fe: LibraryModule fix NP-Exception, in case of missing fum-file

- src/dev/flang/ast/AbstractFeature.java
I was investigating #824 a NP-Exception because outer() is null. The relevant code has meanwhile already been changed but
I stumbled upon `outer() == null || outer().isUniverse()` in `existingOrNewTypeFeature()`. The `outer() == null` seems wrong or unnecessary since further down `outer().isUniverse()` is used without any null check.
> ast: enhance precondition in typeFeature to exclude universe

- src/dev/flang/air/Clazzes.java
This change was the result of a merge conflict.
> air: rename 'generics' as 'actualTypeParameters()'

- src/dev/flang/air/AirErrors.java
- src/dev/flang/air/Clazz.java
Since a fixed feature is not inherited, it basically behaves like an abstract feature, so we report a correpsonding error message if an implementation is missing.
> air: Add proper error message if fixed feature is called via heir feature

- src/dev/flang/air/Clazz.java
This is not only about performance, but it the following patches it will be essential to use the already created type clazzes when they are accessed later since creation of clazzes during later phases is not allowed.
> air: Add caching for type clazz

- src/dev/flang/fuir/FUIR.java
This may only occur as a consequence of earlier errors and a bug that would result in a pre- or postcondition failure.
However, when pre/postconditios are disabled, generating C code for the error clazz is always confusing, so we better do not try to work with it at all.
> fuir: Check that Clazzes.error.get() is not part for the clazzes in FUIR

- lib/Type.fz
- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/DotType.java
- src/dev/flang/ast/Types.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/me/MiddleEnd.java
- tests/covariance/test_covariance.fz
- tests/covariance/test_covariance.fz.expected_out
This enables accessing the actual type of an outer 'this' instance and allows calling features redefined for a specific type.
This is expected to make the generic parameter in features like 'numeric' obsolete, this parameter can be replaced by 'numeric.this.type'.
Extended tests/covariance with test cases that check different levels of outer this.types being accessed and redefined.
> lib/fe/air/tests: 'a.this.type' to get actual type of outer feature a

- lib/Type.fz
- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/DotType.java
- src/dev/flang/ast/Types.java
- src/dev/flang/me/MiddleEnd.java
These two features are redundant, the only difference is that getOuterType was always called with a this.type. We can hence simplify the code and use only Types.get.
> lib/fe/air: repalces Types.getOuterType by Types.get

- src/dev/flang/util/FuzionConstants.java
`THIS_TYPE` has been replaced by `abc.this.type` and is no longer used in any example or library code.  So it can be renamed to an internal name to avoid name conflicts.
> util: Add `#` prefix before `THIS_TYPE` type parameter of type features

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
Added check()s that illegal type parameter index only occurs if errors where reported and made sure that error clazz is touched only in case of previous errors.
> air: Made code more robust against earlier errors

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Generic.java
- src/dev/flang/ast/Type.java
- src/dev/flang/fe/LibraryFeature.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/FuzionConstants.java
- tests/type_feature/Makefile
- tests/type_feature/test_type_feature.fz
- tests/type_feature/test_type_feature.fz.expected_out
Type features now have copies of the type parameters of their underlying
original features in addition to THIS#TYPE.  As an example, the type feature
option.type, where
option(T type)
has one type parameters, has two:
option.type(THIS#TYPE type, T type)
An the type of, e.g.
option (list i32)
is
option.type (option (list i32)) (list i32)
i.e., 'THIS#TYPE' is 'option (list i32)', while 'T' is 'list i32'
Special handling was needed for the case when actual type parameters are
inferred from actual arguments in a call. In this case, the type feature's does
not have the actual types ready when it is created, so a call-back is installed
to add this information when it becomes available.
Also, a special handling is needed for types that are cloned for use in type
features.  The clone will use its …
> Support for type parameters in type features

- src/dev/flang/parser/Parser.java
This rule exands to `name` only, so `nameOrType` can be replaced by `name`.
> parser: Remove rule for nameOrType from EBNF syntax

- src/dev/flang/ast/InlineArray.java
the example that triggered the require condition failure:
```
main =>
counts := mapOf string u64 [] []
stdin.
```
> ast: fix require condition failure when errors present

- src/dev/flang/fuir/analysis/Escape.java
This fixes the second test in #874.
> fuir/analysis: Make sure Unbox does not try to pop a unit value

- src/dev/flang/air/Clazz.java
This may happen as a result of missing an implementation of a abstract feature, which will result in an error later.
> air: Make findOuter robust against not finding outer. fix #885, enhance #874

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
The example of #886 created constants of type `u8` without performing any calculations that produces an `u8`. Since the constants did falsely not mark clazz `u8` as instantiated, the middle end assumed there were no instances and hence no features could be called on `u8` resulting in this error when DFA analysed a call to `u8.infix <`.
Now, the presence of a constant ensures that the clazz of the constant is marked as instantiated.
> air: Mark clazzes of constants as instantiated, fix #886, enhance #874

- src/dev/flang/air/Clazz.java
The actual outer clazz may have changed form value to ref or vice versa.
fix #890 and fix #891.
> air: clazzes for result type x.this.type should stay refs or values

- src/dev/flang/ast/AbstractBlock.java
- src/dev/flang/ast/AbstractCurrent.java
- src/dev/flang/ast/AbstractMatch.java
- src/dev/flang/ast/Block.java
- src/dev/flang/ast/BoolConst.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Env.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/NumLiteral.java
- src/dev/flang/ast/StrConst.java
- src/dev/flang/ast/Tag.java
- src/dev/flang/ast/This.java
- src/dev/flang/ast/Unbox.java
- src/dev/flang/ast/Universe.java
The naming of these methods was confusing and their use was inconsistent.  This patch does
- split up `typeForFeatureResultTypeInferencing` into two methods: `typeIfKnown` and `inferredType`.
- `typeIfKnown` is used only in `Expr` instances created by the parser and gives the type of an expression or `null` if it is unkown.  This must be redefined by all parsed expressions, but it is usually not called, `inferredType` is used for this.
- `inferredType` provides the result of `typeIfKnown`, but it provides a means to post-process the type, which will become necessary for handling this.type.
- `Expr.type()` internally uses `typeIfKnown()`. Any `Expr` created from a library file must redefine `Expr.type` to give the type.
- `Expr.typeForGenericsTypeInfereing` (sic!) was removed, this could …
> ast: rename and clean up `Expr.type` and `Expr.typeForFeatureResultTypeInferencing`

- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Unbox.java
This also requires possibliy unboxing the value, so need to relax the precondition of Unbox.
> ast: change result type of outer ref to be this.type, fix #904

- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Expr.java
A thisType whose underlying feature is a ref is always treated like a ref type, so value types in heirs are boxed.
> ast: box expr passed to a ref thisType, fix #904

- lib/String.fz
- src/dev/flang/ast/AbstractBlock.java
- src/dev/flang/ast/AbstractCurrent.java
- src/dev/flang/ast/AbstractMatch.java
- src/dev/flang/ast/Block.java
- src/dev/flang/ast/BoolConst.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Env.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/NumLiteral.java
- src/dev/flang/ast/StrConst.java
- src/dev/flang/ast/Tag.java
- src/dev/flang/ast/This.java
- src/dev/flang/ast/Unbox.java
- src/dev/flang/ast/Universe.java
- tests/reg_issue874ff/Makefile
- tests/reg_issue874ff/issue874.fz
- tests/reg_issue874ff/issue874.fz.expected_out
Removed post-processing of type for type inference, this turned out not to work in all cases in the new test added in this patch.  Expr.inferredType() has been removed, Expr.typeIfKnown can be used directly instead.
Whenever type inference is used with `this`, the type is now the corresponding `this.type`. This required changes in `String.fz` that used `String.this` for type inference resulting in a type incompatible with `String`.
Added tests/reg_issue874ff that contains a collection of test cases related to type inference and this.type.
> lib/ast/tests: cleanup and add tests of type inference using this, fix #874

- src/dev/flang/air/Clazz.java
- tests/reg_issue874ff/issue874.fz
- tests/reg_issue874ff/issue874.fz.expected_out
To find the clazz, outer refs are followed. Fields, however, do not have outer refs, so we start in the surrounding feature instead.
Also extended tests/reg_issu874ff with four variants of the examples from #923.
> air: To find result clazz for this.type field, start at _outer, fix #923

- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/Parser.java
- src/dev/flang/util/Errors.java
- tests/ternary/Makefile
- tests/ternary/test_ternary.fz
- tests/ternary/test_ternary.fz.expected_out
We can now write
```
x := a ? b : c
```
or
```
x := a ? b
: c
```
or
```
x := a ? TRUE => b | FALSE => c
```
or
```
x := a ? TRUE  => b
| FALSE => c
```
Added test for this syntax.
> parser/tests: Fix and unify parsing of ternary operator and inline match

- src/dev/flang/tools/docs/Html.java
- src/dev/flang/tools/docs/Util.java
Partially reverts a previous change of mine. At the time I did not realize that the comments where already HTML and did not need encoding anymore.
> docs: fix comment html encoding

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
This is experimental: Clazz.actualGenerics() could replace `a.this.type` by the actual outer type. This would avoid special handling in Clazzes.clazz(Expr e, Clazz outerClazz). However, this is currently disabled since it has the side-effect of marking some clazzes as instantiated that are actually not (in tests/reg_issues874ff), need to check why.
> air: add expermimental code to eargerly replace 'a.this.type'

- .github/workflows/windows_c.yml
- src/dev/flang/be/c/C.java
fixes #696
This then leaves two failing tests on windows:
```
./build/tests/envir_vars/: failed
./build/tests/fileio/: failed
make[1]: Entering directory '/d/a/fuzion/fuzion/build/tests/envir_vars'
../check_simple_example_c.sh "../../bin/fz " envir_vars.fz || exit 1
RUN envir_vars.fz 1,2d0
< setting FUZION_ENVIR_VARS_TEST_SET to world successful
< unsetting FUZION_ENVIR_VARS_TEST_SET successful
0a1,16
make: *** [Makefile:1014: run_tests_c] Error 1
> testbin.c:16441:7: error: call to undeclared function 'setenv'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
>   if (setenv((char*)arg0,(char*)arg1,1)==0)
>       ^
> testbin.c:16441:7: note: did you mean 'getenv'?
> D:/a/_temp/msys64/mingw64/include/stdlib.h:447:17: note: 'getenv' …
```
> windows: (re)-open stdout/err in binary mode

- src/dev/flang/ast/Actual.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/Loop.java
- src/dev/flang/parser/OpExpr.java
- src/dev/flang/parser/Parser.java
An Actual that cannot be parsed as Expr but only as Type would cause precondition and postconditions failures when passed to a non-type argument that requires a value.
This patch adds special handling an a better error message in this case.
> ast: Handle type passed as value argument Fix #961

- lib/String.fz
This implementation avoids a problem where uninitialized loop variables could be accessed, causing a runtime error, see #764.
> strings.join: use list.intersperse

- lib/fuzion/sys/fileio.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
Previously, get_file_size was implemented as an intrinsic which, in the C backend, called to stat. So does the stats intrinsic, therefore we can actually move to using that.
Also mark get_file_size private for now. It uses the stats intrinsic, but without using the stat effect. We might want to change this. Keep it private until a decision is made.
> lib: io: implement get_file_size as a fuzion feature

- lib/uint.fz
In case of a shift greater than 32 some u32 where dropped from the reversed sequence. It was missing to re-reverse the sequence after dropping some u32s.
> lib/uint: fix right shift for case shift>32

- src/dev/flang/ast/Call.java
For calls created for lambdas, there might be a time when _name and _calledFeature are both null, so toString() should deal with this.
> ast: Make Cal.toString() more robust

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractAssign.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/SrcModule.java
- src/dev/flang/fe/SourceModule.java
Internal features added for, e.g., lambda expressions do not show up in the set od declared or inherited features of the children of their outer features.  This is why a lookup would fail and we avoid this here.
This fix might need to be revisted when working on #932, for now this is just a workaround.
> fe/air: Don't lookup internal features that were added late, fix #978

- src/dev/flang/fuir/analysis/Escape.java
- tests/local_mutate/skip_c
There is no point continuing after a call returned `void` since we cannot possible reach the code follwing this call, and the stack does not contain any value the following code may expect (since void is assignment compatible to every other type).
This fixes the empty stack exception since void left no value to be consumed.
Also added a DEBUG-mode to Escape analysis that can be enabled running `fz` with
```
FUZION_JAVA_OPTIONS=-Ddev.flang.fuir.analysis.Escape.DEBUG=true
```
Also enabled tests/local_mutate to run with C backend since this should work now.
> fuir/analysis: Stop escape analysis on `void` value, fix #977

- lib/local_mutate.fz
- tests/local_mutate/test_local_mutate.fz
- tests/local_mutate/test_local_mutate.fz.expected_out
`mget` has to be used while a mutable value is still mutable, while `get` can only be used when it is closed.  `get` can easily be analysed statically not to require a local_mutate effect to be present.
Also added possible syntax to create alias for types.
Updated tests/local_mutate to use mget.
> lib/tests: Add `local_mutate.mget` and suggested syntax for effect in signature

- lib/local_mutate.fz
- src/dev/flang/air/Clazz.java
- tests/local_mutate/test_local_mutate.fz
Using `a.this.type.env` automatically results in accessing the effect of a child of the effect `a`.
This change actually adds support for `this.type` to all uses of Clazz.actualClazz, but this seems to be only relevant to `this.type.env` for now.
Updated base lib's `local_mutate` to no longer use a type parameter, but use `local_mutate.this.type` instead.
Changed tests/local_mutate to no longer use these type parameters.
> air/lib/tests: Support this.type.env to access effect in environment

- lib/fuzion/sys/fileio.fz
- lib/io/file/stat.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
For the C backend, return the error number directly in case of a failure. For the interpreter backend, match the possible exceptions returned by Files.readAttributes to similar C error numbers.
> lib: io: improve error handling for stat/lstat

- lib/String.fz
These features are similar to the eponymous ones found in the Go standard library [1]. They are however, not fully identical.
[1]: https://pkg.go.dev/strings
Reference: #697
> lib/string: add split_n, split_after, split_after_n features

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
This field was just an ugly workaround to obtain the name of a type, this is available through the type's first type parameter (THIS#TYPE) now.
> air: Remove field Clazz._typeType, this information is available now

- lib/array.fz
- lib/effect.fz
- lib/local_mutate.fz
- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Type.java
- src/dev/flang/fe/SourceModule.java
Disallow ambiguous types names even if they are not used as types: Constructors with the same name and number of formal arguments will cause an error now.
Fixed duplicate type names in the base lib (`array.arrayCons` and `effect`).
For all features that declare a type, the corresponding type feature is not created by default, independent of whether it is used or not. This avoids a lot of problems and workarounds when creating them on demand only. Disadvantage is that library files are slightly larger now.
`f.this.type` now work in a library module since the type features for all children of `f` will be created.
local_mutate now prints the actual `local_mutate.this.type` in `panic`-messages.
This fixes #461 without actually changing the format of the .fum file, but by adding all the type …
> ast: Make AbstractFeature.qualifiedName() robust for early calls, fix #461

- src/dev/flang/ast/FeatureName.java
- src/dev/flang/tools/docs/Docs.java
- src/dev/flang/tools/docs/DocsOptions.java
- src/dev/flang/tools/docs/Html.java
If the docs are built using the new `-ignoreVisibility` option, they will include features whose visibility is limited in the again. However, this documentation is hidden by default and can be toggled by pressing a button. This is intended to be used to generate developer docs.
Fixes #974
> docs: add option to show features with limited visibility

- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/FeatureName.java
- src/dev/flang/fe/LibraryOut.java
- src/dev/flang/tools/docs/Docs.java
Here, internal features are those generated by the Fuzion compiler, which use a name that is inaccessible from outside code, because it starts with the same character that starts a comment.
> ast: add a method to determine whether a feature is internal

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Feature.java
- tests/reg_issue170_distinct_arg_names/issue170.fz.expected_err
This error was helpful when working on type features where I ran into a problem due to repeated arguments.  But I needed more information to understand the problem, so this patch.
Moved the check for this error to the end of the Feature constructor such that all fields in feature needed by the error are initialized.
> ast: Improve error created when arguments have equal names

- tests/local_mutate/test_local_mutate.fz
- tests/local_mutate/test_local_mutate.fz.expected_out
`go` works now including returning a result. Also the crash when using `cell.this` is gone.
quicksort0 did not use local_mutate effect.
> test/local_mutate: use `go` instead of `use`, remove quicksort0, remove `me`

- lib/local_mutate.fz
- src/dev/flang/parser/Parser.java
Use `! type1, type2, type2` after the feature result to describe the effects.
Currently, the effects are parsed, but irgnored otherwise.
> parser/lib: Add syntax for effects in a feature declaration

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Type.java
The problem was that there are two representation of `this.type`: Within type features, a type parameter contains the corresponding `this.type`, while usually a Type instance of kind `RefOrVal.ThisType` is used. In the examle of #1007, these two types get assigned resulting in the assignment compatibility check to fail.
This patch fixes this be converting the type parameter variant back to the usual `RefOrVal.ThisType` version.
This patch also adds documentation and an example to `replace_THIS_TYPE`, the original documentation was confusing.
Also, the occasionally added `<>` after types are fixed by this patch, empty generics must use Type.NONE, which was not the case at one place.
Finally, the toString-output for a type has been changed to include `(in type feature)` for a `this.type` …
> ast: Fix assignment checks for `this.type` in type features, fix #1007

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
Split up AbstractType.replace_THIS_TYPE into a part done inline in Call.java and the rest renamed as `replace_type_parameter_used_for_this_Type_in_type_feature` using `applyToGenericsAndOunter`.
Fixed bug in `remove_type_parameter_used_for_this_type_in_type_feature`, forgot to assign `applyToGenericsAndOuter` to result.
> ast: cleanup and fix related to handling of `this.type` in type features, #1007

- src/dev/flang/air/AirErrors.java
- src/dev/flang/ast/AstErrors.java
In the first line of the error, highlight the missing feature and add the feature that should provide an implementation.
Also fixed a double space after a comma in another error message.
> air/ast: Improve error for missing implementation of abstract feature

- src/dev/flang/be/c/C.java
error was: 
> ex.c:39792:1: error: all paths through this function will call itself [-Werror,-Winfinite-recursion]
> {
> ^
> 1 error generated.
> 
> error 1: C backend: C compiler failed
> C compiler call 'clang -Wall -Werror -Wno-gnu-empty-struct -Wno-unused-variable -Wno-unused-label -Wno-unused-but-set-variable -Wno-unused-function -O3 -lm -lpthread -o ex ex.c' failed with exit code '1'
> 
> one error.
>
> be/c: fix compilation with dfa=off by allowing infinite recursions

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractType.java
Avoid special handling for the result of `Types.get` for this type.
> air: Replace `this.type` early during creation of clazzes. fix #949

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Function.java
- src/dev/flang/parser/Parser.java
- tests/reg_issue1013_parentheses_ignored_in_operator_calls/Makefile
- tests/reg_issue1013_parentheses_ignored_in_operator_calls/issue1013.fz
- tests/reg_issue1013_parentheses_ignored_in_operator_calls/issue1013.fz.expected_out
- reason was that parentheses were not represented in AST
- this resulted in Call.loadCalledFeature() to try and find (and erroneously succeed in this case) a chain booleans before trying to find the operator on outer.
- fixes  #1013
> ast: type inference failed for operator calls

- lib/fuzion/sys/misc.fz
- lib/mutate.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
This intrinsic enables adding a unique number to identify instances.  This is used to make sure the mutable variables are mutated with exactly the same effect they were created with.
> lib/be: Add intrinsic `fuzion.sys.misc.unique_id`, use it in mutate effect

- lib/String.fz
Instead of single utf8 bytes, the whole strings were checked for equality.
> lib: String.lteq was always true for strings with same prefix

- lib/sorted_array.fz
Even though I prefer `/=` for esthetic reasons, let us use `!=` for now instead of missing both variants.
> lib: replace remaining `/=` by `!=`

- src/dev/flang/ast/Call.java
If type inference resulted in incompatible types, we better set the inferred type to `t_ERROR` to avoid reporting any further problems related to this type.
This reduces the number of errors produced by the example of #1051 from 4 to 2.
> ast: Avoid redundant errors reported in #1051

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/NumLiteral.java
Numeric literals are now used as a second-class source of type information. Only if type inference is not possible otherwise, the default type of a numeric literal will be used.
This has the effect that in an expression `x = y`, where one side is a numeric literal, the type parameter will be inferred from the other side.
> ast: Improve type inference for type parameters and numeric literals, fix #1050

- lib/codepoint.fz
This fixes idiom 159 and provides a much more efficient handling of codepoints in an ordered data structure.
> lib: Add `codepoint.type.equality` and `codepoint.type.lteq`

- src/dev/flang/ast/Call.java
This avoids problems, e.g., in some idioms where `String` and `codepoint` are otherwise conflicting type parameters.
> ast: Use `AbstractType.union` to join types for inference of type parameters

- src/dev/flang/fe/FeErrors.java
- src/dev/flang/fe/LibraryModule.java
Any .fum file now checks the version of all the .fum files it depends on. An error is produced in case a version does not match.
> fe: Check version number of fum file dependencies, fix #1048

- lib/ordered_map.fz
Remove the hack using a ref to the ordered_map.
Closes #1044.
> move entry back to ordered_map.entry

- src/dev/flang/parser/Parser.java
- tests/reg_issue952/Makefile
- tests/reg_issue952/issue952.fz
- tests/reg_issue952/issue952.fz.expected_err
> parser: improve error when only type is missing in feature definition

- src/dev/flang/fe/FrontEnd.java
This fallback is no longer needed since modules are sufficiently stable.
> fe: Remove fallback for modules to load source files instead of .fum

- src/dev/flang/fuir/FUIR.java
- src/dev/flang/tools/Fuzion.java
- src/dev/flang/util/Map2Int.java
Now dumps code of all routines and all code blocks of each routine, not only the first one. For Match-Statements, it shows the successor code blocks as well.
> Improve -XdumpFUIR output

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Function.java
- src/dev/flang/fe/LibraryCall.java
Without freezing this list, a call to Clazz.actualGenerics() with these generics will result in some of the generics being replaced, so a second call with different actual generics will not use the correct actual generics.
This problem did not manifest for dev.flang.ast.Call since the front end calls AbstractType.actualType on Call.actualTypeParameters, which freezes this list, while the list in LibraryCall was not frozen.
This patch also adds a NYI-comment where Call.actualTypeParameters should freeze the list with a reference why this is not possible yet (due to a hacky way to obtain the result type from a lambda).
Also added one more use of List.setOrClone, just to be safe and removed a wrong comment in LibraryCall (refering to resolveTyps, while resolution is fully done for …
> fe: Freeze LibraryCall.actualTypeParameters(), fix #1098

- src/dev/flang/ast/Type.java
- src/dev/flang/ast/Types.java
Also use List.map instead of ListIterator.set to make sure we properly a Type when its generics() array changes when visiting Types.
This generally should reduce problems due to mutation of Types and Lists of type parameters.
> ast: freeze _generics array of interned Types

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
The problem is that in a type feature of feature f with type parameter A etc., the usage of a value of type f.this.type for type inferencing may result in a type containing f.A, while the type feature has its own copy f.type.A.
This patch replaces these type parameters when inferring type parameters and when determining the result type of a call if that call is performed in a type feature.
> ast: Fix for ordered_map usage in idioms#13 and others

- .github/workflows/linux.yml
reason: docs code broke but was not unnoticed. This will prevent this in the future.
> workflow, linux: add step build all java code

- src/dev/flang/util/SourcePosition.java
> util: fix #1118, column off by one, in case of multibyte symbols

- src/dev/flang/fuir/analysis/dfa/NumericValue.java
joinInstance in numeric value was missing the case that we join with a whole set of numeric values.
This avoids the bug in #1121, but it reveals new problems in the C backend.
> dfa: Fix joining numeric value with ValueSet, #1121

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/fuir/FUIR.java
Added AbstractType.asStringWrapped as coutnerpart to toStringWrapped.
toString does not include `ref` in case of a `ref` type.
> fuir: Use asStringWrapped for type parameters in FUIR.clazzBaseName, fix #1144

- src/dev/flang/air/Clazz.java
- src/dev/flang/be/c/CTypes.java
This results in better output and C code comments using '(' and including 'ref' for type parameters.
> air/C: Uuse Type.asStringWrapped and FUIR.clazzAsStringNew, #1144

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Feature.java
- tests/reg_issue1158_type_of_type_parameters/Makefile
- tests/reg_issue1158_type_of_type_parameters/test_type_of.fz
It is not possible to obtain the type of a type feature. This type is always the base library feature Type, so we cannot run into an endless sequence of type-of-type-of-type...
Also, for routines and fields whose result type is inferred from a type parameter, the type is set to the base library feature 'Type'.
The usage of base lib's 'Type' in these cases results in boxing of type values, which allows them to be passed on (while type values themselves are unit type values and their surrounding feature get specialized for a specific value).
Also added a test checking type values returned by routines or assigned to fields.
> ast/tests: Fix #1158: type inferred from type parameter and type of type

- .github/dependabot.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
These workflows rely on a build tool like gradle/maven. So we would need to add this first even though we have just one little dependency right now...
> openssf: add dependabot, codeql, dependency-review

- Makefile
Added new variables FZ_INT and FZ_C for all dependencies for using fz with interpreter or C backend, resp.
> Makefile: Add missing dependency on $(BUILD_DIR)/include to run_tests_c*

- lib/Type.fz
- tests/reg_issue1158_type_of_type_parameters/test_type_of.fz
`type_of expr` determines the compile-time type of `expr` after evaluating `expr`.
`type_of_lazy ()->expr` determines the compile-time type of `expr` without evaluating `expr`.
Once syntax sugar for lambdas used as lazy values was improved, `type_of` could itself be made lazy and `type_of_lazy` could be removed`.
Also added tests for type_of to test/reg_issue1158_type_of_type_parameters.
> lib/tests: Add new base lib feature type_of to determine compile-time type

- lib/Any.fz
- src/dev/flang/ast/AbstractType.java
Workaround for a NullPointerException when determining the type of type as produced by the example of #1167.
Added `Any.dynamic_type` to obtain the dynamic type of an instance (which was not possible without the previous workaround).
Also added some documentation for `Any.as_string` ans `Any.prefix $`.
> lib/ast: Add `Any.dynamic_type`, fix #1167

- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/Parser.java
Now, type lookup will cause an error when a matching type is found at different outer levels, just the same as a call lookup would cause an error in this case.
For this to work, the special syntax `a : choice of x, y, z` was changed to no longer require lookup of `x, y, z` such that this does not cause an error in case of a conflict (which occured for `effectMode.abort`).
Also, the type lookup in SeouceModule.setOUterANdAddInnerForQualifiedRec had to be fixed not to look for types in outer features unless we look for the first type in a qualified type `a.b.c`.
> fe: Remove the special handling for type lookup wrt outer

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Feature.java
This avoid creating infinetely exploding instances since the instance of a routine contains the implicit result field (which is accessible in postconditions only).
> fe: Do not permit a routine `a` to return `a.this` as result, fix #1186

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractType.java
Avoid some confusing output I saw during debugging.
> ast/air: Wrap some more strings into parentheses or use `asString`

- lib/array.fz
- lib/array2.fz
- lib/array3.fz
- lib/conststring.fz
- lib/fuzion/sys/internal_array.fz
- lib/marray.fz
- lib/ps_map.fz
- lib/stream.fz
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
This is in preparation of being able to create a slice of an `internal_array`.
> lib/internal_array separate allocation of memory from `internal_array`.

- tests/modules/Makefile
This helps in some cases where this test currently fails because an earlier test run did not delete the generated .fum files properly.
> tests: Add dependency from base.fum in modules test

- examples/webserver/webserver.fz
`io` as shortcut for `Java.java.io` is now in conflict with base lib's `io`, so I renamed it as `jio`.
Also had to rename `byteLength` as `byte_length`.
> examples: Fix ambiguous feature name and outdated `byteLength`.

- lib/Sequence.fz
- lib/Set.fz
- lib/String.fz
- lib/bitset.fz
- lib/bool.fz
- lib/ctrie.fz
- lib/equals.fz
- lib/equatable.fz
- lib/has_hash.fz
- lib/has_partial_order.fz
- lib/int.fz
- lib/list.fz
- lib/numeric_sequence.fz
- lib/searchable_list.fz
- lib/searchable_sequence.fz
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- tests/equals/test_equals.fz
- tests/equals_negative/equals_test_negative.fz
- tests/reg_issue309_check_constraints_of_types/issue309.fz
- tests/type_feature/test_type_feature.fz
Swift uses the name `Equatable` as well for its analogon of this feature. Likewise, there is a Dart library called `equatable`.
> rename `has_equality` as `equatable`

- tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz
Issue #88 remains open, but it makes the test compilable again.
> tests: Fix ambiguous type error in tests/mix_inheritance_and_outer, #88

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/Call.java
Types.get is like a special intrinsic that converts a type into an instance of a type feature.  It is used internally whenever a type feature is used in an expression.
> ast/air: fix #282 by deciding not to remove the special handling

- src/dev/flang/ast/Call.java
The first check (select >= 0 in a call to a type parameter) is handled in resolveSelect.
The second check for that the result of gt.resolve() is not null is also redundant since null is no longer used to indicate an error, but Types.t_ERROR is returned in this case.
> ast: Remove redundant checks and throws, fix #283

- .github/workflows/windows.yml
- .github/workflows/windows_c.yml
On windows there are several options of a C standard library. ucrt (Universal C Runtime) seems to be the better choice than cygwin.
For more information see also:
https://www.msys2.org/docs/environments/
> switch from msys (cygwin) to clang64 (ucrt)

- src/dev/flang/ast/FeatureAndOuter.java
- src/dev/flang/fe/FrontEnd.java
Led to problems in language server. Because `Types.f_ERROR` is reset but `FeatureAndOuter.ERROR` holds first instance of `Types.f_ERROR` forever.
> ast: reset statically held FeatureAndOuter.ERROR

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
A lazy value `v` when used is replaced by `v.call`. If this replaced value is then passed to a target type that is lazy, we no longer wrap `v.call` info an instance of `Lazy`, but instead we go back to the original value `v`, avoiding redundant wrapping.
> ast: Fix passing lazy value to lazy argument, fix #1232

- lib/option.fz
This is now possible due to the new syntax sugar for lazy features.
> lib/option: remove lazyGet, make get lazy

- lib/list.fz
A previous PR (#1170) fixes #775, so we can change the base lib code accordingly: `as_string ","` now expands to `list.this.as_string ","`.
> lib: remove redundent `list.this.` in call to `as_string`

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
The detail message for error "Incompatible types found during type inference for type parameters" was partly created in Call.java and did not use the highlighting for the types printed.
Now, the raw data, a list of positions and types, is passed to AstErrors and converted to a String there.  Types are wrapped using `s()`.
> ast: Move detail error message generation from Call to AstErrors

- src/dev/flang/fe/FeErrors.java
Prevent any attempt to mix references to an incompatible .fum file.
`tests/javaBase` no longer crashes with a Java exception, but stops after the module version issue was detected:
```
> make
../check_simple_example.sh "../../bin/fz -unsafeIntrinsics=on -modules=java.base" javaHello.fz || exit 1
RUN javaHello.fz 1,7d0
< Hello Java 🌍!
< Hello Java 🌍!
< Hello Java 🌍!
< Hello Java 🌍!
< Hello Java 🌍!
< string has 16 bytes: [72,101,108,108,111,32,74,97,118,97,32,-16,-97,-116,-115,33]
< Hello Java 🌍!
*** FAILED out on javaHello.fz
0a1,7
> 
> error 1: Incompatible module version encountered
> Module LibraryModule for 'java.base' references module LibraryModule for 'base'
> Expected version: e12a41ca8fe8e13cf9d8152901b2326d
> Actual version  : aa11f2b3054e7dbf1eb469ba7c4f2c7e
> 
> *** fatal …
```
> fe: Make incompatible module version a fatal error, fix #1205

- src/dev/flang/ast/Function.java
Assigning a lambda to a generic type caused a require condition to faile (or worse if preconditions are switched off).  This patch fixes this and also avoids subsequent errors by setting `t` to `Types.t_ERROR` in `Function.propagateexpectedtype2`-
This also fixes #1230.
> ast: Make Function.propagateExpectedType2 work with generic type, fix #1229

- src/dev/flang/ast/AbstractFeature.java
typeFeature() can actually be called on universe in case of a previous error, so permit this.
The example from #1237 now produces errors, but no crashes:
```
> PRECONDITIONS=true POSTCONDITIONS=true ./build/bin/fz ex_1237.fz 
/home/fridi/fuzion/work/ex_1237.fz:1:22: error 1: Syntax error: expected term (lbrace, lparen, lcrochet, fun, string, integer, old, match, or name), found keyword 'type'
socket_type : choice type.stream datagram raw is
---------------------^
While parsing: term, parse stack: term, opTail, opExpr, expr, actual, actualSpace, actualsList, actualArgs, call, callList, skipCallList, skipInherits, skipFeaturePrefix, isFeaturePrefix, stmnt, stmnts, unit
/home/fridi/fuzion/work/ex_1237.fz:1:1: error 2: Could not find called feature
socket_type : choice type.stream datagram …
```
> ast: Make AbstractFeature.typeFeature robust against previous errors, fix #1237

- tests/check_simple_example.sh
- tests/check_simple_example_c.sh
The variant of the `check_simple_example` scripts in the flang.dev repository included some features which were missing here, import them. This is in preparation of removing the now redundant scripts from the flang.dev repository.
> `check_simple_example`: import missing features from flang.dev repo

- lib/Monoid.fz
- lib/Sequence.fz
- lib/String.fz
- lib/bitset.fz
- lib/list.fz
- lib/numeric.fz
- lib/ps_set.fz
- lib/unit.fz
Ideally, the type parameter of `Monoid` should be restricted to `equatable` types, and the monoid property could in the future be checked using that operation. There are few cases where using a different equality operation would be a good idea, and in this case, implementing your own monoid isn't that hard either.
However, we do not yet introduce a type contraint to `equatable`. This is because in some places (`list` and `Sequence`, in particular, which do not have an equality operation), the `Monoid` is (ab)used to implement a nice variant of `fold` whose starting element is the neutral element of the monoid.
> lib/Monoid: remove `Monoid.infix ==` equality operation

- src/dev/flang/parser/Lexer.java
- src/dev/flang/util/Errors.java
- tests/strings_multiline/multiline_strings_test.fz
- tests/strings_multiline/multiline_strings_test.fz.expected_out
- tests/strings_multiline_negative/strings_multiline_negative.fz
- refinded error 'not enough indent' to include hint to \s escape char
- add test case for multiline string including single and double quotes
- add test case for multiline string 'ending' in four quotes.
- added comment on Lexer.StringLexer.escapeChars
> parser: multiline strings, refinements

- src/dev/flang/mir/MIR.java
This improves the performance of examples/callingJava by 43% (1391ms instead of 1992ms) on my laptop.
> mir: Do not create AbstractFeature instances for all library features

- src/dev/flang/parser/Parser.java
The example from #1215
```
unit_result is
a i32 is
b i32 is 42
```
used to produce the error
```
ex_1215.fz:4:3: error 1: Incompatible types in assignment
b i32 is 42
--^
assignment to field : 'unit_result.a.result'
expected formal type: 'i32'
actual type found   : 'unit'
assignable to       : 'unit'
for value assigned  :
{
}
```
now it produces
```
ex_1215.fz:3:11: error 1: Incompatible types in assignment
a i32 is
----------^
assignment to field : 'unit_result.a.result'
expected formal type: 'i32'
actual type found   : 'unit'
assignable to       : 'unit'
for value assigned  :
{
}
```
Using a single line as in
```
unit_result is
a i32 is; b i32 is 42
```
works as expected:
```
ex_1215a.fz:3:11: error 1: Incompatible types in assignment
a i32 is; b i32 is 42
----------^
assignment to …
```
> parser: Set pos of empty block followed by LF to end of previous line, fix #1215

- lib/fuzion/sys/internal_array.fz
- src/dev/flang/ast/InlineArray.java
Re-introduce index checks for inline arrays. This decreases the DFA performance by a factor of approx. two, but at least this is linear so not such a big issue.
> dfa: Remove workaround for #990

- lib/u128.fz
This fixes an issue with the `flang.dev` examples: since `numeric.sign` depends on `numeric.type.zero`, at least `u128.type.zero` needs to be defined. Add `one` for completeness as well.
> lib/u128: introduce `zero` and `one` type features

- src/dev/flang/ast/If.java
- src/dev/flang/parser/Parser.java
The problem was that an `if` statement was parsed as a single statement, not as a block. So if an `else` was followed by a block that happened to start with an `if`, only the `if`-statement was parsed and the remaining statements of that block caused an error due to wrong indentation.
Now, the `else`-part is always parsed as a block.
The following code (from #327 with variations added) is legal now:
```
some_fun bool is
if true
true
else
if true
say "hello"
else
say "hello"
true
some_fun2 bool is
if true
true
else if true
say "hello"
else
say "hello"
say "ok..."
true
some_fun3 bool is
if true
true
else if true
say "hello"
else
say "hello"
say "ok..."
true
```
> parser: Fix parsing of `if` following `else`, fix #327

- src/dev/flang/air/Clazz.java
Clazz.findOuter() did not cover the case where clazz is choice. In this case outer ref is null and thus can not be used for following to find the the clazz we are looking for.
> air: fix `require-condition3 failed: dev.flang.air.Clazz:<init>:325`

- src/dev/flang/ast/OuterType.java
- src/dev/flang/ast/Type.java
- src/dev/flang/parser/Parser.java
When creating type parameters for choice in `a : choice of x, y`, do not set the feature references directly even though they are known, but leave the type resolution for later. This has the effect that the outer type will be set correctly to `outer.this.type`.
This might result in additional errors in case the feature names are ambiguous. But if this is the case, I guess it is better to flag an error anyway.
> parser: be lazier when creating type parameters for `choice of`, fix #1289

- src/dev/flang/parser/Lexer.java
- src/dev/flang/util/Errors.java
- tests/strings_multiline/multiline_strings_test.fz
- tests/strings_multiline/multiline_strings_test.fz.expected_out
The escape character followed by a line feed now causes the newline to be dismissed. This makes it possible to write
```
say """
hello \
world"""
```
to print
```
hello world
```
Closes #1277.
> parser: allow dismissing newlines in multiline strings

- .github/workflows/windows.yml
I broke the windows tests with a previous PR. With this they should work again:
https://github.com/michaellilltokiwa/fuzion/actions/runs/4616432463
> windows, tests: switch msystem to ucrt64

- lib/sum.fz
`sum` is currently broken, but this does not make anything worse.
> lib/sum: simplify the code

- lib/bool.fz
This implements the lazy boolean operations currently handled by the front end in the standard library. This does not remove the special handling in the front end for now, so it is not a solution to #1348.
> lib/bool: implement lazy boolean operations

- src/dev/flang/util/Errors.java
If given a maximum error or warning count of -1, fz will display all the errors or warnings. The value -1 was chosen because while 0 would work for errors, 0 can be used to disable all warnings.
Closes #1329.
> fz: allow specifying -1 as maximum warning/error count for no limit

- lib/String.fz
- lib/ctrie.fz
- lib/i64.fz
- lib/matrix.fz
- lib/time/date_time.fz
- lib/u128.fz
- lib/u64.fz
When the `!=` infix was (temporarily) removed, calls to it had been replaced with calls to infix `=` and prefix `!`. We can undo this change now.
> lib: reintroduce usage of `!=` infix

- lib/bool.fz
- src/dev/flang/ast/Consts.java
- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/Parser.java
The `lazy` keyword did not do anything, therefore it can be removed. An issue that remains is that the boolean ternary operator can't be changed to accept `Lazy` values due to a type inference issue. However, it seems there is no special handling to make the ternary operator lazy, so this should not behave differently.
> parser: remove the `lazy` keyword

- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/FuzionConstants.java
- tests/this_type/skip_int
> be/c: create binary named `universe` if main feature omitted.

- lib/map_of_total_order.fz
Abstracts implementation of Map with totally ordered keys. This could be done for other data structures as well.
example:
```
ex =>
a := (map_of_total_order i32 String)
.new [1,2,3] ["a", "b", "c"]
say a
map_of_total_order i32 String (ks,vs->
ct := CTrie i32 String
for idx in ks.indices do
ct.add ks[idx] vs[idx]
ct
)
b := (map_of_total_order i32 String)
.new [1,2,3] ["a", "b", "c"]
say b
```
```
(1 => a), (2 => b), (3 => c)
(1 => a), (2 => b), (3 => c)
```
> lib/map_of_total_order: add effect map_of_total_order

- src/dev/flang/parser/Lexer.java
- src/dev/flang/util/SourceFile.java
This fixes an issue where a string literal at the end of file caused an error. The problem is that the string literal is read twice, the second time it accesses the codepoints explicitly, including the character after the closing quote. This did not return an END_OF_FILE codepoint until now, instead causing a precondition failure.
Fixes #1379.
> lexer: use `codePointAt` in `raw` method

- src/dev/flang/be/c/C.java
`sys/fcntl.h` does not exist in all libc, such as musl. This will cause a compiler warning/error when attempting to compile Fuzion code using the C backend.
> be/c: include just `fcntl.h`

- src/dev/flang/tools/Fuzion.java
only frontend is created then shows errors and exits.
This could be used for syntax checking of idioms/examples etc.
> fz: add option `-no-backend`

- lib/effect.fz
There is currently no way to detect an `abort` that occured in a simple_effect. We should probably change this.
Also replaced var name in lambda from `unit` to `_`.
> lib: Add NYI-comment to simple_effect.use

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Impl.java
- src/dev/flang/fe/SourceModule.java
The are no longer needed after the front end, so it is sufficient to have them in `Feature`.
This PR is based on PR#1495 which should be merged first.
> fe: Remove `AbstractFeature.initialValue` and `implKind`

- src/dev/flang/air/Clazz.java
Since the key in the _inner map contains the type pars now, there is no problem caching them as well.
> air: Do not disable caching of inner clazzes with type parameters

- lib/option.fz
The suggested syntax sugar is supported meanwhile.
> lib: remove outdated NYi comment from `infix >>=`

- lib/Function.fz
What can be done using `Functions.compose` is now possible in a nicer way using the `Unary` type and its `infix ∘` operator. It might be nice to allow more arbitrary function composition in the future as documented in the now removed comment, but this is not strictly necessary, at least for now.
> lib/Function: remove `Functions` feature

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
To avoid complete chaos, this batch stops chained boolean conversion when any intermediate value is of error type.
For easier debugging, added `toString` to `Expr.ERROR_VALUE`.
> fe: Fix IndexOutOfBoundsException in chained boolean, fix #1473

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/fe/SourceModule.java
- tests/redef_with_type_parameters/Makefile
- tests/redef_with_type_parameters/redef_test.fz
- tests/redef_with_type_parameters/redef_test.fz.expected_out
This does allow the execution of the example given in #1387.  The example is added to a new test case.
However, the new test case also add three variants that currently do not work yet.  I will add separate issues for those to get fixed.  The main problem is types used in the signature that depend on type parameters of the redefined feature.
> fe: Allow redefinition of feature with type parameters, fix #1387

- src/dev/flang/air/Clazz.java
According to `fz -XjavaProf`, this requires about 10ms or 10% of the time of an HelloWorld example using the interpreter. With this patch, I could measure the execution time going down from 906ms to 868ms (4.2% faster).
> air: Add caching for Clazz.parents

- src/dev/flang/air/Clazz.java
The same is done in `registerAsHeir()` which is called for every clazz anyway.
> air: Remove redundant `_heirs.add(this)`

- lib/memoize.fz
Inspired by idiom 315: https://www.programming-idioms.org/idiom/315/memoization
Would be cool to be able to have this as a subfeature of Unary. So we could do `fn.memoize` to get a memoized version of a Unary.
But the `T` of memoize is constrained while Unary's `T` is not.
> lib: add feature memoize

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
With this change, `AbstractTypes.applyPars(AbstractType)` and `AbstractTypes.applyPars(AbstractFeature, List<AbstractType>)` both modify the type given as `this`.
> fe: replace `this` and `t` in `this.applyTypePars(t)`, fix #1527

- tests/reg_issue270/Makefile
- tests/reg_issue270/issue270.fz.expected_err
- tests/reg_issue270/issue270.fz.expected_err_c
- tests/reg_issue270/skip_c
This cannot be a negative test for the C backend since the error is created only at runtime while negative.mk does not execute the created binary.
> tests/reg_issue270: Make this a simple tests such that it works with C backend

- tests/if_negative/iftest_negative.fz
This fixes a test that brakes after the fix for #1066 and addes two new sub-tests.
> tests/iftest_negative: Fixed to work with unit type propagation for constructor

- tests/loop/looptest.fz
It was decided in #39 to require parentheses or `then` in this case, so I added `then` and removed the comment.
> tests/loop: Remove comment with ref to #39

- tests/reg_issue293_confusion_of_type_and_value_params/issue293.fz
A NYI states this was a bug in the C backend. This bug is apparently gone.
> tests/reg_issue293: Remove no longer needed declaration of abstract feature

- lib/float.fz
- tests/visibility/visibility.fz
Added `float.as_i32` which was used in one commented-out line of the visibility test.
Uncommented and removed NYI-comment from visibility tests using floats.  Added cases to cover the different string conversion results in interpreter and C backends.
Added reference to #1550 to one NYI-comment.
> lib, tests: Removed and updated NYI-comments from tests/visibility

- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/SourceFile.java
- tests/visibility/visibility.fz
Since the lexer and parser inherit from SourceFile we end up with many instances refering to the same file.  This breaks the equality test using `==` and `!=`. This patch introduces a new feature `SourceFile.sameAs` that handles clones as equal.
The enable uncommenting a line of code in tests/visibility that did not compile before.
> util/fe/tests: Fix check if two positions refer to same source file fix #1550

- src/dev/flang/tools/Tool.java
- src/dev/flang/util/Profiler.java
A text file uses the flame graph input format. To create an .svg file, the `flamegraph.pl` script must be in the current $PATH, it is used to create a flame graph from the profileing data.
> tools: Add -XjavaProf=file.txt and -XjavaProf=file.svg to create flame graph

- lib/Sequence.fz
- lib/list.fz
- lib/stream.fz
- where `as_list` is used to use the corresponding list feature we can as well return `list` and not `Sequence`.
> lib, Sequence: remove stream in some features, return list where possible

- src/dev/flang/be/c/CTypes.java
This avoids unused entries in declared structs, e.g., for `panic`, we used to define
```
// for fuzion.std.panic#1
struct fzT_fuzion__std__1panic
{
fzT__RString* fzF_0_msg;
struct { } fzF_1_result;
fzT_fuzion__std* fzF_2__U40__1074231254;
};
```
which is now
```
// for fuzion.std.panic#1
struct fzT_fuzion__std__1panic
{
fzT__RString* fzF_0_msg;
};
```
> C backend: Unit type fields do not need to be included into structs.

- lib/marray.fz
- lib/stream.fz
This avoids other library code having to call Fuzion internals, which we want to avoid.
> lib/marray: add a type feature `new` to create a `marray` without elements

- src/dev/flang/air/FeatureAndActuals.java
- src/dev/flang/util/List.java
The output looked a bit confusing during debugging, now uses space separated parameters that are wrapped in parentheses if needed (used to be comma separation and not wrapped).
> util/air: Improve FeatureAndActuals.toString

- src/dev/flang/ast/AbstractType.java
This change make this method consistent with `AbstractType.actualType`.
> fe: cleanup: In AbstractType.actualTypeType swap `this` and the argument

- lib/float.fz
- lib/integer.fz
- lib/wrapping_integer.fz
These redefinitions were added to work around the problem described in issue #1634. Since issue #1634 is now fixed, we can remove them.
> lib: remove workaround for issue #1634

- src/dev/flang/fuir/analysis/dfa/DFA.java
This code was quite broken, setting the effect to null instead of the new value if it was not set.
This fixes failing flang.dev examples when run with C backend:
content.design.examples.monadiclifting_hello3.fz
content.design.examples.monadiclifting_helloabort.fz
content.design.examples.monadiclifting_hello4.fz
content.design.examples.monadiclifting_hello5.fz
> dfa: Fixed code to replace default effect

- src/dev/flang/ast/AbstractAssign.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/FeatureVisitor.java
- tests/nested_lazy/ex_nested_lazy.fz.expected_err
- tests/reg_issue1665_nested_lazy/Makefile
- tests/reg_issue1665_nested_lazy/test_issue1665.fz
- tests/reg_issue1665_nested_lazy/test_issue1665.fz.expected_out
The problem essentially was that in nested calls, actual arguments of inner calls were mapped before outer calls, which results in wrong outer features for the instances of `Lazy` created.
This patch solves this by
- splitting up `wrapInLazyAndThenPropagateExpectedType` (what was named the wrong way around) into two phases: `propagateExpectedType` and `wrapInLazy`
- changing the order for `wrapInLazy` to process outer calls before actuals in inner calls.
As a bonus, this patch adds support for automatic `wrapInLazy` for assignments to fields such as
```
i Lazy i32 := f x
```
A regression test testing three levels of nested lazy arguments and lazy assignments to fields is also added.
> fe: Add support for nested lazy values, fix #1665

- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/analysis/dfa/EmbeddedValue.java
- tests/reg_issue1610_outer_escapes/test_issue1610.fz
- tests/reg_issue1610_outer_escapes/test_issue1610.fz.expected_out
A call in the inherits clause will store a ref to the target of that call in the heir instance, so we might extend the life time of that target.  This `patch` records this lifetime changes to enforce heap allocation of the target.
Also add a commented out test-case that requires #1642 to be fixed first.
> dfa: record life time of outer ref created in inheritance call, fix #1659

- lib/f32.fz
- lib/f64.fz
- lib/float.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
Previously, f32 and f64 implemented type.equality and type.lteq by using the = and <= intrinsics. This is actually wrong because the = and <= intrinsics compare floating point numbers using IEEE rules, where NaN != NaN, and thus type.equality did not implement a proper equivalence relation.
This reintroduces the comparision infixes local to f32 and f64 that by default shadow the infixes provided by `lib/equals.fz`. If a proper equivalence relation or partial order is still desired, comparisions can still be done using `equals f32 f32.type.NaN f32.type.NaN` or `lteq f64 0.57721 f64.type.NaN`, for example.
The idea for this behavior is from [1].
[1]: https://forums.swift.org/t/comparable-and-floatingpoint-types/16886
> lib: separate IEEE-like and mathematical floating point comparision

- src/dev/flang/fuir/analysis/dfa/Call.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/analysis/dfa/EmbeddedValue.java
- src/dev/flang/fuir/analysis/dfa/Instance.java
- src/dev/flang/fuir/analysis/dfa/NumericValue.java
- src/dev/flang/fuir/analysis/dfa/RefValue.java
- src/dev/flang/fuir/analysis/dfa/SysArray.java
- src/dev/flang/fuir/analysis/dfa/TaggedValue.java
- src/dev/flang/fuir/analysis/dfa/Val.java
- src/dev/flang/fuir/analysis/dfa/Value.java
The original code mixed up values, represented by `Value` and child classes, with lifetime information stored in `EmbeddedValue`.
Now, the AbstractInptereter is instantiated with generic type `Val` that represents both, but all operations performed in values first use method `value()` to extract the `Value` instance. It is hence no more possible to accidentally add instances of `EmbeddedValue` in, e..g, a set of values.
Feature like `EmbeddedValue.readField` could be removed since these are now only defined in `Value`, which `EmbeddedValue` no longer extends.
> dfa: cleanup: Add abstract `Val` as parent of `Value` and `EmbeddedValue`

- tests/check_simple_example_c.sh
Previously, this would only print a warning/information that stderr differed which was not even shown when all other tests passed.
> tests/check_simple_example_c: fail when stderr differs

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/QualThisType.java
- src/dev/flang/ast/This.java
- src/dev/flang/ast/Type.java
- src/dev/flang/parser/Parser.java
The special handling for `qualThis` to create either an Expression or a Type has been removed. `qualThis` now produces a list of strings that is then wrapped into an intance of `This` or `QualThisType`.
`QualThisType.java` is a new class for parsed types of the form `x.y.this.type`. They no longer have any outer types set, but contain the qualified name only that will be used to resolve the feature.
The code in `This.java` to look find `x.y` in an expression `x.y.this` was enhanced to complain about ambiguity and to become usable for `x.y.this.type` as well.
Failure of feature lookup in a `x.y.this` expression now results in `Expr.ERROR_VALUE` such that follow-on errors should be suppressed.
Feature lookup in `Type.resolveFeature` now performs special handling for `x.y.this.type`, where …
> fe: Fix check failure in case `x` is not found in `x.this.type`, fix #1711

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Impl.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/Loop.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/Parser.java
- tests/reg_issue952/issue952.fz.expected_err
- tests/typeinference_for_formal_args_negative/Makefile
- tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz
- tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
NOTE: This is experimental, would like to gain experience and know if this is useful or does harm.
With this patch, formal arguments types in a feature declaration can be omitted provided that the currently compiled module has a call to the formal argument's outer feature that provides an actual argument that permits type inference.
As an example, here is the first example from https://flang.dev/tutorial/feature_decl_fields
```
Point(x, y i32) is
show (Point 3 4 )
show (Point 5 12)
show(p Point) => say "{p.x}, {p.y}"
```
Type inference permits omitting all formal argument types in this example, so we can omit `i32` and `Point` types for `x`, `y` and `p` and write
```
Point(x, y) is
show (Point 3 4 )
show (Point 5 12)
show(p) => say "{p.x}, {p.y}"
```
This looks like magic, but it is in …
> fe, tests: Type inference for formal arguments

- src/dev/flang/ast/Assign.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Destructure.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/ParsedCall.java
- src/dev/flang/ast/ParsedName.java
- src/dev/flang/ast/QualThisType.java
- src/dev/flang/ast/This.java
- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/OpExpr.java
- src/dev/flang/parser/Parser.java
- src/dev/flang/util/List.java
- src/dev/flang/util/SourceFile.java
- src/dev/flang/util/SourcePosition.java
- src/dev/flang/util/SourceRange.java
- tests/contracts_negative/SquareRoot.fz.expected_err
- tests/nested_lazy/ex_nested_lazy.fz.expected_err
- tests/reg_issue19_redef_choice_result/testRedefine.fz.expected_err
- tests/reg_issue270/issue270.fz.expected_err
- tests/reg_issue356_check_condition_failure_in_call_inferGenericsFromArgs/issue356.fz.expected_err
- tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/issue698.fz.expected_err
- tests/reg_issue7_genericConstraint/checkGenericConstraint.fz.expected_err
- tests/reg_issue8_optionFalse/bugOptionFalse.fz.expected_err
- tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
Add new class `SourceRange` that extends `SourcePosition` but covers a range of source code.
Added class `ParsedName` that combines a String parsed for the rule for `name` with a `SourceRange`.  Used this to enhance error messages by marking the exact name in the source code.
> parser, fe: Add source position information for names, fix #1723

- src/dev/flang/ast/Visi.java
- src/dev/flang/parser/Parser.java
This makes it possible to later distinguish if a visibility was explicitly provided or not.
> add visibilty unspecified

- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
> be: use atomic operations in `fuzion.sys.misc.unique_id` intrinsic

- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/This.java
Ideally, I would like to get rid of this visitor altogether and join `UnresolvedType.findGenerics` with `UnresolvedType.resolve`.
> fe: remove unnecessary calls performed by Feature.findGenerics visitor

- .github/workflows/apple.yml
- .github/workflows/syntax_check_fuzion.yml
- .github/workflows/windows.yml
- README.md
also changed to run the tests weekly on apple
on windows, mmap test fails because required stack size is larger than windows default and `list.concat` can not be tail call optimized. this can be reproduced on linux easily by decreasing stack size e.g. `ulimit -s 512`
on apple, floating point test fails probably due to a rounding error.
> add badges of testruns to readme

- src/dev/flang/ast/Feature.java
- src/dev/flang/fe/LibraryOut.java
Write correct argument count to fum file, i.e., include free types that were added.
With this, @maxteufel 's changes to `Sequence.zip` can be sabed to `base.fum` without failing checks, and the example runs.
> fe: Fix .fum file for free types, #1656, modifications forgot in #1774

- src/dev/flang/ast/Expr.java
- src/dev/flang/util/FuzionConstants.java
This changes the name used by `Expr.NO_VALUE` from `**error**` to `**no value**`. This is intended to make `Expr.NO_VALUE` easily distinguishable from `Call.ERROR` in a debugger.
> ast: use a unique name for `Expr.NO_VALUE`

- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
> ast: handle boxing of erroneous and empty values gracefully

- src/dev/flang/ast/Call.java
- src/dev/flang/util/FuzionOptions.java
I did not think of it at the time I made the change but the short circuit of a call in case of errors broke a lot of tests in the language server. So this is my new suggestion to have an option in the visitor to continue/abort visitation of AST-items on known errors.
> feature visitor, option to continue/abort visit on error

- lib/f128.fz
- lib/f16.fz
- lib/f32.fz
- lib/f64.fz
- lib/i128.fz
- lib/i16.fz
- lib/i32.fz
- lib/i64.fz
- lib/i8.fz
- lib/int.fz
- lib/num/minus.fz
- lib/num/plus.fz
- lib/num/sign.fz
- lib/u128.fz
- lib/u16.fz
- lib/u32.fz
- lib/u64.fz
- lib/u8.fz
- lib/uint.fz
In particular, this allows user-supplied code such as
```
i32.factors => 1..val & x -> val %% x
```
to keep working.
> lib: make `val` field of numeric features public

- lib/exit.fz
Just like for `Panic_Handler` and `Print_Handler`, the user might want to specify a custom behavior. This is not possible unless `Exit_Handler` is public (a "Could not find called feature" message is returned otherwise).
> lib/exit: make `Exit_Handler` public

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/fe/Module.java
- src/dev/flang/fe/SourceModule.java
A minimal example,
```
ex_tnf is
foo void is
do
f foo := foo
```
which previously generated the following error:
```
ex_tnf.fz:6:5: error 1: Type not found
f foo := foo
----^^^
Type 'foo' was not found, no corresponding feature nor formal type parameter exists
Type that was not found: 'foo'
in feature: 'ex_tnf.f'
However, one feature has been found that matches the type name but that does not define a type:
'ex_tnf.foo' defined at ex_tnf.fz:3:3:
foo void is
--^^^
To solve this, remove the return type (or replace it by 'ref') of one of these features.
one error.
```
started producing the following error after the visibility changes were introduced:
```
ex_tnf.fz:6:5: error 1: Type not found
f foo := foo
----^^^
Type 'foo' was not found, no corresponding feature nor formal type parameter …
```
> fe: fix search for nontype features that match a type name

- tests/loop_negative/looptest_negative.fz
- tests/visibility_modules/Makefile
- tests/visibility_modules_negative/Makefile
See #473, #481, #1420, #1597 for the reason.
Additionally, fix an error in the `looptest_negative` test that is not in the scope of the test.
> tests: override `NAME` variable in `visibility_modules*` tests

- lib/character_encodings/ascii.fz
these are useful outside of `baselib` hence the change of visibility to public.
> change visibility, `character_encodings.ascii.*`

- src/dev/flang/be/c/CNames.java
- src/dev/flang/fuir/FUIR.java
This avoids some ugly inline constants in the backends.
> fuir/C: Add new method `FUIR.clazzid2num`

- src/dev/flang/fuir/analysis/dfa/Call.java
At least for intrinsics whose result is a simple type, the DFA analysis now continues analysis if the intrinsic was not found.
This simplifies adding new intrinsics.  For intrinsics returning more complex instance, DFA still stops since it has currently no way to model this.
> dfa: continue DFA analysis after unknown intrinsic was found

- src/dev/flang/air/Clazzes.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
This is required by the JVM backen: For an assignment `t.f := v` for a field `f` that is unused, we must still evaluate `t` and `v`.  To do this, FUIR has been extended to obtain the type of the assigned value in case the assigned field is removed.
> fuir/analysis: Evaluate target and value for assginment to unused field.

- lib/fuzion/sys/Pointer.fz
- lib/fuzion/sys/fileio.fz
- src/dev/flang/air/Clazzes.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/dfa/Call.java
This is currently used for internal array data only, but might be used at other places as well.
This will be needed in the JVM backend.
> lib/fuir: Add backend-dependend pointer type fuzion.sys.Pointer

- tests/check_simple_example.sh
- tests/check_simple_example_c.sh
This avoids long output that makes it hard to see the actual error.
Also simplifies the scripts such that they contain the same code to output the restuls.  Aadded support for expected_out_int/expected_err_int to prepare for the interpreter no longer being the default.
> tests: in simple tests, if unexpected error was produced, supress diff on stdout

- Makefile
- uses same approach as for `lib`
- this should allow making changes in `build/tests` if `tests` is kept unchanged.
> makefile: update tests/include on change

- lib/outcome.fz
- this fixes currently broken examples/webserver.fz
> visibility: make `outcome.err` public

- src/dev/flang/be/c/C.java
- src/dev/flang/be/c/CTypes.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
This avoids some special handling in the backend, in particular helps with the upcoming JVM backend.
> fuir/C: FUIR.clazzChoice now returns void clazz instead of -1

- src/dev/flang/ast/Box.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/InlineArray.java
> `checkTypes` use `isDirectlyAssignable`

- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
- src/dev/flang/ir/IR.java
This patch removes the only use of the `Dup` intermediate instruction and removes the instruction as well.  The duplication was not neccessary and resulted in a value left on the stack.
This patch also contains some cleanup:
- Rename `AbstractInterpreter.clazzHasUniqueValue` as `ignoredOnStack`,
- Remove unused handlign of InlinedArray in IR, and
- enhanced some comments.
> fuir: Improve stack cleanup witihin basic block, #1875

- src/dev/flang/fuir/analysis/AbstractInterpreter.java
This is a special handling that was introduced for the C backend where structs for ref types always contain an embedded corresponding value type instance, so accesses to fields are always to the fields of the value type.
This special handling in the AbstractInterpreter is no longer needed for the C backend and it is in the way for the JVM backend that does not create value types for every ref type.  SO this patch removes that special handling.
> fuir/analysis: When setting argument fields, do not force to use value instance

- src/dev/flang/fuir/analysis/AbstractInterpreter.java
This was useful when debugging the stack in FUIR.
> fuir/analysis: Add a check that match() does not return any non-unit value.

- src/dev/flang/fuir/analysis/dfa/DFA.java
This caused a crash in tests/javaBase for the JVM backend since unsupported intrinsics of the Java interface produced Value.UNDEFINED that was not handledproperly when accessed.
> dfa: Fix crash due to Value.UNDEFINED (as a result of missing intrinsics)

- src/dev/flang/fuir/FUIR.java
This is needed by the JVM backend to initialize constant strings. Strange that the C backend could do without this.
> fuir: provide access to clazz fuzion.sys.array.u8

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/Names.java
- src/dev/flang/be/jvm/Runner.java
- src/dev/flang/be/jvm/classfile/ClassFile.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/classfile/Expr.java
- src/dev/flang/be/jvm/runtime/Runtime.java
This is similar to the way the Interpreter impelments abortable effects: An expception `Abort` is thrown and handled by a suitable installed effect handler.
What was alittle tricky for the JVM backend is to permit the callback within effect_abortable.  This is done now a little manually via passing an instance to the clazz and searching for `fzRoutine`. This willt need to be improved for better performance at some point.
Also added some comemnts and support for cpClass constants in class files.
> jvm: add support for abortable effects

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Impl.java
This would make `=>` behave the same as `:=`, both allow but do not require the result type.
A constructor declaration with `is` or `{ .. }` should eventually be required not to define a function result type.
> fe: Allow result type in declaration using `=>`

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/Names.java
- src/dev/flang/be/jvm/runtime/AnyI.java
All the `refs` in a choice type are stored in the same value field. Since the type of these fields could be an interface, they are not assignable to `runtime.Any`, so we use a new interface `runtime.AnyI` that is also implemented by these interfaces.
This fixed the class verify error when running `tests/stdin` using the JVM backend.
> jvm: Add new interface dev.flang.be.jvm.runtime.AnyI and use it for fzVref

- src/dev/flang/be/jvm/Intrinsix.java
This is pretty useless without the other `concur.atomic` intrinsics.
> be/jvm: implement `concur.atomic.racy_accesses_supported` intrinsic

- src/dev/flang/be/jvm/runtime/Runtime.java
Without any extra work, this also provides a stack trace, which due to the name mangling also contains a readable stack trace for the Fuzion part of the code.
> be/jvm/runtime: throw an Error in case of a contract failure

- src/dev/flang/ast/UnresolvedType.java
- tests/reg_issue1943_type_parameter_as_outer_type/Makefile
- tests/reg_issue1943_type_parameter_as_outer_type/issue1943.fz
- tests/reg_issue1943_type_parameter_as_outer_type/issue1943.fz.expected_out
I was unsure when I wrote this code if using a type parameter as an outer type actually makes sense, but it does as shown in the examples of the regression test.
The bug that is patch fixes was that the constraint type of the type parameter was not resolved yet and hence not usable.
> fe: fix #1943: Using type parameter as outer type

- src/dev/flang/ast/ResolvedNormalType.java
The problem was that an argument type ended up being `Function **error**`, while the error is suppressed automatically for `**error**`, i.e. `Types.t_ERROR`.
> fe: Suppress third subsequent error reported in #1945

- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
The value of the `debug`, `debug_level` and `safety` intrinsics is now determined by the values of these options passed to the `fz` tool at build time, rather than hard-coding values in the JVM runtime.
This also fixes problems caused by the DFA and the JVM backend using different values, in case a non-default value was passed to Fuzion at the build time.
> be/jvm: determine values of debug and safety intrinsics at build time

- lib/fuzion/sys/fileio.fz
- lib/io/file/stat.fz
This will avoid accidentally supplying values other than the internal data structure of an array to these features, and thus make it a little bit safer to work on the standard library.
> lib/io: use `fuzion.sys.Pointer` for references to arrays' internal data

- src/dev/flang/be/c/C.java
- src/dev/flang/fuir/analysis/dfa/Call.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
This also changes the semantics of the native features. Native features that used to return `String` will no longer work, they now have to have the more precise result type `Const_String`. Likewise, features that previously accepted an `Any` argument need to be updated to accept an argument of type `fuzion.sys.Pointer`.
> be/c, dfa: clean up handling of native features

- src/dev/flang/be/jvm/classfile/ClassFile.java
`cpFloat`/`cpDouble` used to be called with an `int`/`long` containing the bit representation, which `javac` converts to a `float`/`double` resulting a massively wrong value.
Now, new methods and constructs for the bits representation are added that handle this case correctly and avoid the implicit conversion by `javac`.
> jvm: Avoid implicit conversion from float/double bits to float/double, fix #1985

- lib/Any.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
- tests/functions/functions.fz
Just like equality, the hash_code function should be a type feature and not be defined for Any and inherited.
For hash_code to be useful, the following invariant should hold:
```
(hash_code a != hash_code b) || (a = b)
```
So the semantics of `hash_code` depends on `type.equality`, so `hash_code` should be a type feature as well.
> lib: Remove Any.hash_code

- src/dev/flang/be/jvm/CodeGen.java
Just to make sure that it can be dumped savel.
> jvm: Add a check that the value returned by code for assign is Expr.UNIT

- src/dev/flang/be/jvm/CodeGen.java
For a dynamic call with more than one targets, the resulting code is just an `invokeinterface` to a method performing the actual call. If, however, this call returns a unit type value and that value, the AbstractInterpreter currently throws that code away.
This change makes sure that a unit type value is returned as a RESULT (i.e., code) not as a VALUE to the AbstractInterpreter, so it will not be ignored.
For non-unit type values, the AbstractInterpreter already makes sure that the value is drop()ped properly if it is not used.
> jvm: Do not throw away code for dynamic call with unit type result

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/JVM.java
- src/dev/flang/be/jvm/Types.java
- src/dev/flang/be/jvm/classfile/Expr.java
Previously some methods, such as `getstatic`, accepted a `JavaType` argument, while other methods, such as `putstatic`, accepted type information by passing a `String`. Change the latter to take a `JavaType` argument, to make the usage more consitent.
> be/jvm: Expr: consistently use `JavaType` as an argument

- src/dev/flang/be/jvm/Types.java
The code to filter out unit type values was present for the arguments already, we need this as well for the target that is passed as a first argument and that may be unit type as well.
> JVM: Add support for call target type being unit (Java's void), fix #1902

- src/dev/flang/ast/Call.java
- replace e.g. `u16 7` by just the numliteral 7.
- this is necessary to convert arrays such as `[u16 2, u16 7]` to compile-time constants.
> replace calls to number-primitive by just NumLiteral

- src/dev/flang/fuir/analysis/dfa/DFA.java
the DFA figures out that the field is never read hence `clazzNeedsCode` is false for the result field of the main feature but we need it for assigning result in jvm backend.
fixes #1903
> be/jvm: `fieldExists` should always be true for mains result field.

- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/ArrayConstant.java
- src/dev/flang/ast/FeatureVisitor.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/NumLiteral.java
- src/dev/flang/ast/Types.java
- src/dev/flang/be/c/C.java
- src/dev/flang/be/c/CExpr.java
- src/dev/flang/be/c/CTypes.java
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/ArrayData.java
- src/dev/flang/be/interpreter/Interpreter.java
- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/JVM.java
- src/dev/flang/be/jvm/JVMOptions.java
- src/dev/flang/be/jvm/Names.java
- src/dev/flang/be/jvm/PreallocatedConstant.java
- src/dev/flang/be/jvm/classfile/ClassFile.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/runtime/Runtime.java
- src/dev/flang/fe/LibraryFeature.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
- src/dev/flang/fuir/analysis/dfa/Call.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/analysis/dfa/SysArray.java
- src/dev/flang/me/MiddleEnd.java
- tests/contracts_negative/SquareRoot.fz.expected_err_jvm
- tests/reg_issue270/issue270.fz.expected_err_jvm
This reduces the size of the generated code, in particular for the JVM backend that previously was not able to create bytecode for the tables used for ryu float to string conversion code. 
Now, constant arrays are serialized into an array of bytes that is then processed by the backend to produce code that creates the array.
> Support for constant arrays of numeric element types. 

- src/dev/flang/be/jvm/JVM.java
Removed `if (false &&..)`.
Removed left over debugging code that checks target is not null.
Use result var and a single return.
Add comments.
> jvm: cleanup in JVM.prolog().

- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/Names.java
- src/dev/flang/be/jvm/classfile/ByteCode.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/classfile/Expr.java
For now, these just use a global lock, not java.util.concurrent.Atomic* classes.
Also, value types are not properly supported yet.
Since this patch needs to allocate local var slots for inline intrinsics, I had to add arguments cl and pre to the function that creates the code.
Also add new bytecode LCMP and DUP2_X1, DUP2_X2 (the latter are not used by this patch, but were needed in an intermediate version and may turn out useful anyway).
> jvm: Add intrinsics concur.atomic.read0/write0/compare_and_(set|swap)0

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/JVM.java
- src/dev/flang/be/jvm/classfile/ByteCode.java
- src/dev/flang/be/jvm/classfile/ClassFile.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/classfile/Expr.java
- src/dev/flang/be/jvm/classfile/Label.java
This is required for more complex control flow, in particular for tail recursion where we need a `goto` to the beginning of a method.
The main change is that ByteCode no longer provides a methods `bypeCode` and `bc*` that produce a `byte[]`, but instead there are methods `code(bw, ...)` that write bytecode to a `ByteCodeWriter`.
These `ByteCodeWriters` is an abstract class that will be run three times: first, to get an upper bound estimate for the bytecode size and offsets of labels, next to then freeze this upper bound and fix all labels, and finally to produce the code now that the labels adresses are known.
This infrastructure will also be needed to support bytecode `lookupswitch` and `tableswitch` that have some alignment requirements.
Unfortunately, this patch requires changes in …
> jvm: Add support for labels as branch targets when generating bytecode

- lib/composition.fz
This is not intended to be useful at this point, it is just a first try to collect basic composition features that appear in literature and other languages.
To make this useful, we need to write example code using these and play around with it. Maybe we need to move these into Unary.fz, maybe add Binary.fz, maybe make some operators or add operator aliases, maybe add features or operators to the universe, etc. Maybe we want these in a separate module?
> lib: Add collection of features for function composition, #2046

- tests/positive.mk
This helps understanding the issue when looking at the test run output, in particular for tests `inheritance` and `unicode` when run with the current JVM backend.
> tests: On failure of a positive test, show stderr output.

- src/dev/flang/be/jvm/runtime/Runtime.java
On a stack overflow while executing compiled code, the Fuzion feature stack trace (using the mangled Java names) is printed instead of the Java stack trace.
Also, repeated entries in the stack trace are now summaries properly, the existing code for this was broken.
> jvm: Improve handling of stack overflow

- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
- src/dev/flang/be/jvm/runtime/Runtime.java
`fuzion_sys_env_vars_get0` does not return an `fzI_String` instance, which is expected by the intrinsic as a result.
> be/jvm: revert move of `fuzion.sys.env_vars.get0` in caf4b895

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
The original code could replace an outer value type resulting in wrong memory
accesses.
This patch essentially does
- prevent short-circuiting an outer relation in a clazz if outer is a ref
- remove unneded code aroung `wouldCreateCycleInOuters`
- removed too strict postCondition for Clazzz using `hasCycles`, this was too
strict since it ony checks cycles of features, which may happen
- adds special handling in Clazz.typeClazz to for the outer clazz of a type
clazz' type clazz: Since the type clazz of a type clazz is just the clazz of
feature Type.fz, the outer of this must alsway be universe and not Type.fz.
> air: Restrict replacing outer clazz to fix #2058

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/classfile/Expr.java
This count can easily be determined from the signature, so this patch replaces the count argument in `Expr.invokeInterface()` by logic to determine the count.
This enables removing wrong hard-coded values in the JVM backend.
> jvm: Fix code that writes count of arg slots for invokeInterface bytecode

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/classfile/ClassFileConstants.java
- src/dev/flang/be/jvm/classfile/Expr.java
This is based on #2068 and should hence be be reviewed / pulled after #2068.
No code was generated for a dynamically bound assignment since the wrong result clazz was used.
This patch moves the local var `rt` outside an `if` such that the result type is determined only once.
Also, the argument count for an assignment, which should always be 1, was wrong for a dynamically bound assignment.
> Fix jvm outer normalization test failure

- tests/inheritance/inheritance.fz
These are tricky cases using outer refs that were originally broken in the JVM and, for #2058, C backend.
> tests: add failing examples from #2058 and #2064 to tests/inheritance.fz

- tests/calls_on_ref_and_val_target/calls.fz
- tests/calls_on_ref_and_val_target/calls.fz.expected_out_c
- tests/calls_on_ref_and_val_target/calls.fz.expected_out_jvm
This changes the test such that it tests the desired behavior and not the wrong behavior currently implemented in the C backend (#2072).
The JVM backend is actually correct here and properly changes a mutable field in an outer instance.
This patch
- fixes the test to expect the correct behaviour when mutating outer fields
- updated the expected interpreter output that is correct for these cases, but still fails in 12 checks (#2073)
- adds expected JVM backend output that is correct in these cases
- updates the expected C backend output that is wrong in these cases
> tests: Fix calls_on_ref_and_val_target's cases not supported by C backend #2072

- src/dev/flang/be/jvm/Choices.java
Previously, this would just put an `ACONST_NULL` on the stack, which by default supplies `java.lang.Object` as its type. This caused a check-condition failure in `CodeGen.drop`. Supply the type of the choice to fix the problem.
> be/jvm: Choices: when tagging nullable choices, supply type information

- src/dev/flang/be/c/C.java
- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
This consists of three commits: 
1. add `cl` and `pre` parameters to some methods in `AbstractIntperpreter`
2. add error handling for unsupported value types in intrinsic for `compare_and_set`/`swap`
3. Support assignments of value types, fix `tests/assignments` failure
The last commit is the important one: 
Value types are allocated as instances of a Java class. So far, assignments of value types was done by assigning references to these instances. This is ok only if the value is immutable, which is not always the case.
This patch creates new instances on assigments of value types. Performance-wise, this is catastrophic since really many temporary instances are allocated on the heap.
To improve the performance, the goal is to avoid class instances for value types altogether and expand …
> jvm: fix assignments of value types

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractConstant.java
- src/dev/flang/ast/BoolConst.java
- src/dev/flang/ast/NumLiteral.java
- src/dev/flang/ast/StrConst.java
- src/dev/flang/me/MiddleEnd.java
- manually marking clazzes as called/instantiated
- marking i8 and other features as used
- move visit(s) to `AbstractConstant`
> air/me: mark clazzes/feature as instantiated/used/called programmatically

- src/dev/flang/ast/AbstractBlock.java
- src/dev/flang/ast/Block.java
Also `AbstractBlock.typeIfKown` always returned `unit` which is kind of odd...
> ast: move typeIfKnown from Block to AbstractBlock

- lib/fuzion/sys/fileio.fz
These will be turned into constants whereas `array n x->x` will not.
> lib/fileio: use inline array syntax

- lib/array.fz
- lib/fuzion/sys/internal_array.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
- src/dev/flang/be/jvm/runtime/Runtime.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
This turns the precondition failure in `test/stdin` into a nicer error saying `error 1: Attempt to modify immutable array`.
The way this works is that all internal array data that are put into an instance of an (immutable) array will be marked as frozen using a weak map of all frozen array data pointers. On modification, it will then be checked that the modified array is not in that map.
These checks are currently enabled only if CHECKS is set. In case debugging is disabled, eventually no code should be generated for this.
> jvm: add checks to trap accidental modifications of immutable array data

- lib/fuzion/sys/fileio.fz
- lib/fuzion/sys/internal_array.fz
- lib/fuzion/sys/net.fz
- lib/io/file/open.fz
- lib/io/file/stat.fz
- lib/io/stdin.fz
- lib/time/now.fz
- src/dev/flang/fuir/analysis/dfa/DFA.java
In general, the code pattern
```
arr := [0,0]
intrinsic_function arr.internal_array.data
result := arr
```
is changed into
```
iarr := fuzion.sys.internal_array_init T length
intrinsic_function iarr.add
result := iarr.as_array
```
This is a little clumsy, but in many cases the code should be change anyway once
we can return tuples from intrinsics.
Since this removes the code to initialize the array, the DFA no longer sees any
values assigned to these arrays. So this patch adds explicit handling in the DFA
to initialize these arrays.
>  lib/dfa: For intrinsics that write arrays, do this before creating immutable array

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Block.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Destructure.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/Impl.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/Loop.java
- src/dev/flang/fe/LibraryOut.java
- src/dev/flang/fe/Module.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/parser/Parser.java
- src/dev/flang/util/SourcePosition.java
- tests/free_types_negative/test_free_types_negative.fz.expected_err
- tests/nested_lazy/ex_nested_lazy.fz.expected_err
- tests/reg_issue1945_ambiguity_for_lambda_result_neg/issue1945neg.fz.expected_err
- tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
- tests/visibility_modules_negative/main.fz.expected_err
In error messages, use source text of expressions not a string representation of the expression like it was done before.
fixes #1670 
Blocks do not have a source position themselves anymore but return the range from beginning of first to end of last expression.
> Expr as string

- lib/concur/atomic.fz
- lib/effect.fz
- lib/f32.fz
- lib/f64.fz
- lib/fuzion/java.fz
- lib/fuzion/sys/env_vars.fz
- lib/fuzion/sys/fileio.fz
- lib/fuzion/sys/net.fz
- lib/i16.fz
- lib/i32.fz
- lib/i64.fz
- lib/i8.fz
- lib/quantor.fz
- lib/safety.fz
- lib/u16.fz
- lib/u32.fz
- lib/u64.fz
- lib/u8.fz
- src/dev/flang/ast/Call.java
- src/dev/flang/be/jvm/Choices.java
This fix actually required three changes, see the individual commits for details: 
1. ast: For actual type parameters, create all required type features
The problem was that for a type passed as an actual type parameter, the type
parameter of that type itself did not get its type feature created, resulting in
an error when finding all used features in the middle end.
This patch forces the creation of all type features for all features appearing
as outer features or as type parameters of an actual type parameter in a call.
2. jvm: Fix error message in case match is performed for void-like choice
The error message was hard to read, it lacked spaces and a hyphen.
Additionally, this now uses `Errors.fatal` instead of just throwing an `Error`.
3. lib: use intrinsic_constructor for instrinsics …
> fix #2114: add all type features for type pars, fix JVM error msg, use intrinsic_constructor for `bool` result

- lib/id.fz
- lib/void.fz
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Types.java
- tests/reg_issue356_check_condition_failure_in_call_inferGenericsFromArgs/issue356.fz.expected_err
This makes more sense than declaring it as an absurd constructor since you cannot call a choice at all and you cannot create a value by assigning one of the choice types since there are none.
> lib: define `void` as an empty `choice` type, add identity routine `id T x` and function `id T`

- lib/container/Buffer.fz
- lib/container/buffer.fz
- lib/fuzion/sys/fileio.fz
- lib/io/file/open.fz
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
- tests/lib_fileio_mmap/Makefile
- tests/lib_fileio_mmap/mmap_test.fz
This patch first introduced a new abstract feature `container.buffer` that is the basis of `io.file.open.mapped_buffer` that is no used for `mmap`.
The use of `mapped_buffer` instead of `marray` permits the JVM backand to chose a different impementation for mmapped memory: These are represented as `java.nio.ByteBuffer`, while `marray u8` internally use Java's `byte[]`.
All the other backends need to impement new intrinsics for `mapped_buffer`, but can use the original representation.
This patch removes te effect `io.file.open.mmap` and uses `io.file.open` instead.  Consequently, the code passed to `io.file.open.mmap` no longer needs to use `io.file.open.mmap` (no arguments) to access the mapped memory. Instead, I have added an argument `buf` to the lambda that gives access to the memory. …
> lib/jvm: Add support for mmap to JVM backend, cleanup of mmap implementation

- src/dev/flang/be/jvm/JVM.java
Now, an explicit `iconst 1` is added in this case since product types of no elements are always equal.
> jvm: atomic comparison of values with no surviving fields was incorrect

- src/dev/flang/ast/AstErrors.java
- tests/visibility_modules_negative/main.fz.expected_err
Errors such as wrong visibility modifiers gives a list of features that are invisible, but this was only a list of feature names.  This patch adds the source code position where these features are declared.
> fe: improve error messages that list a number of candidate features

- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/runtime/Runtime.java
The argument type and result type of `RUntime.fuzion_sys_env_varfs.get0` where wrong.  Result is now explicitly converted to `byte[]`.
Also added a new helper method `Runtime.stringToUtf8ByteArray` since this conversion is done at three different places now.
This fixes the JVM for `idiom10ex.fz`.
> jvm: Fix classfile VerifyError in intrinsic `fuzion.sys.env.vars.get0`

- src/dev/flang/be/jvm/runtime/Intrinsics.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
This was the reason why idiom115ex.fz failed with JVM backend, the DFA determined that there was no data in the array and so it stopped executing.
This patch also does two cleanups
- Add helper methods to DFA to set array elements for numeric arrays
- More consisent formatting of casts in jvm/runtime/Intrinsics.java: `(x[])y` ->
`(x[]) y`
> dfa/JVM: Add array initialization effect to intrinsic fuzion.std.date_time

- lib/fuzion/sys/net.fz
For some strange reason, this only fails occasionally when running tests/sockets on my machine.
> lib: fix mutation of array when calling intrinsic fuzion.sys.net.accept

- src/dev/flang/be/jvm/Choices.java
- src/dev/flang/be/jvm/classfile/Expr.java
The result type of the `Expr` returned by `Choices.tag` was not set in cas the original value was a unit type.  This cause class file verification errors if the created choice value is then `drop()`ed, e.g., due to an assignment to an unused variable.
This fixed the generation of broken byte code for examples from flang.dev like `content/tutorial/examples/fibint.fz`.
Also added a comment to `Expr.ENABLE_COMMENTS` since I was confused about my own code about how to enable this.
> jvm: fix result type of tagged unit type

- src/dev/flang/be/jvm/Choices.java
In very small tests that use type `bool` but do not use both `TRUE` and `FALSE`, the choice kind would get set to `unitlike` or even `voidlike` resulting in errors since bool is otherwise hard-coded as type `Z` in the JVM backend.
This patch hard-wires the choice kind for `bool` to `boollike` to avoid this.
This fixes failures of examples from flang.dev like `content/design/examples/tya_const.fz`.
> jvm: Fix `Choices.kind(bool)` to `boollike`

- lib/outcome.fz
- lib/state.fz
> lib: Fix visibility of `infix >>=` and other features in `outome` and `state`

- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/be/jvm/Intrinsix.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
- src/dev/flang/be/jvm/runtime/Runtime.java
previous to this change skipped test concur_simple did not work: 
```
RUN concur_simple.fz 0a1,26
> 
> error 1: java.lang.NullPointerException: Cannot invoke "java.lang.Thread.join()" because the return value of "dev.flang.be.interpreter.OpenResources.get(java.lang.Long)" is null
>       at dev.flang.be.jvm.runtime.Runtime.fuzion_sys_thread_join0(Runtime.java:717)
>       at fzC_concur__1thread__1spawned__join.fzRoutine(Unknown Source)
>       at fzC_concur_simple.fzRoutine(Unknown Source)
>       at fzC_universe.main(Unknown Source)
>       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>       at …
```
> be/jvm: fix `thread.join0`

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/parser/Lexer.java
- src/dev/flang/parser/Parser.java
- tests/free_types_negative/test_free_types_negative.fz.expected_err
- tests/reg_issue1945_ambiguity_for_lambda_result_neg/issue1945neg.fz.expected_err
- tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
- tests/visibility_modules_negative/main.fz.expected_err
This fixes the output in examples on flang.dev such as `ccontent/tutorial/examples/constants_string_example2.fz` and it gives more useful output in many other situation.
Updated expected error output for tests that are affected by this change.
> parser: For each `Expr`, store the whole source range with the Expr, fix #2109

- lib/container/ctrie.fz
- tests/ctrie_threads/ctrie_threads.fz
also used `fuzion.sys.misc.unique_id` to:
- change equality comparison of inodes and main-nodes.
- use as generation identifier
> ctrie: remove workaround for #1604

- bin/aspell.dict
- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractBlock.java
- src/dev/flang/ast/AbstractCurrent.java
- src/dev/flang/ast/AbstractMatch.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/ArrayConstant.java
- src/dev/flang/ast/BoolConst.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Env.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/Impl.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/NumLiteral.java
- src/dev/flang/ast/StrConst.java
- src/dev/flang/ast/Tag.java
- src/dev/flang/ast/This.java
- src/dev/flang/ast/Universe.java
- src/dev/flang/be/interpreter/Interpreter.java
- src/dev/flang/fuir/FUIR.java
Idea is that StrConst has type `Const_String`, but when a type is used for inferencing `String` is used instead of `Const_String`
> fix inconsistency of type of StrConst

- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractConstant.java
- src/dev/flang/ast/StrConst.java
- src/dev/flang/be/interpreter/Interpreter.java
- src/dev/flang/fe/LibraryOut.java
- src/dev/flang/fuir/FUIR.java
I found it inconsistent to have a difference in the type of type inference and for type checking, so I changed this back to return `String` just like `typeForInferencing`.
To create instances of `Const_String` for these constants in later phases, there used be be special handling in the interpreter, DFA, etc.  Now, instead, there is a new method `AbsractConstant.typeOfConstant` that is redefined by `StrConst` to return `Const_String`. This method is now used in later phases when the typeo the value to be created for a constant is required.
I will extend the tutorial on flang.dev to explain this a little better.
> ast: Set type of `StrConst` to `String` to avoid confusion

- src/dev/flang/ast/Feature.java
Feature lookup in the current scope via Feature.findFieldDefInScope failed to find the use of a field if that use was within a call that had an error such that the arguments where no longer iterated.
Now, in case of an existing error in a call the current scope, a failed feature lookup is no longer reported.
This removes additional errors that are currently reported by flang.dev's examples/examples/man_or_boy2.fz.
> ast: Suppress feature-not-found as subsequent error

- src/dev/flang/ast/UnresolvedType.java
- src/dev/flang/fe/SourceModule.java
Type parameters that are found are then handed down to get the actual type provided in the inheritance call.
> fe: Find inherited type parameters in `SourceModule.lookupType`, fix #2169

- src/dev/flang/be/jvm/runtime/Intrinsics.java
The original code was horribly expensive. Now, a value that is small enough to be a Java `long` is converted directly, larger values are shifted by one bit such that the sign bit is 0, converted and doubled.
> jvm: Better implementation of `Intrinsics.u64_as_f64`

- src/dev/flang/ast/FeatureAndOuter.java
I found this confusing when I used it for debugging.
> ast: Improve debug string produced by `FeatureAndOuter.toString()`

- src/dev/flang/ast/Feature.java
The example from #2167 still creates one subsequent error `Internally referenced feature 'Y' not found`, but this might be acceptable for now.
> ast: relax precondition of Feature.outer() for fix #2167

- src/dev/flang/be/jvm/CodeGen.java
The code for preconditions in inherits-calls works correctly, arguments are evaluated xactly once as desired.  So this comment is no longer needed.
> jvm: Remove outdated NYI-comment

- src/dev/flang/ast/AbstractMatch.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/Impl.java
- src/dev/flang/ast/InlineArray.java
before t_UNDEFINED was used in two ways:
- a failure of a union of two types
- type that was/is not inferred yet.
> return `t_ERROR` instead of `t_UNDEFINED` when `union` fails

- lib/Sequence.fz
- lib/list.fz
The name is inspired by Haskell, I am not fully happy with it but did not find a better name yet.  An example:
```
[1,2,3,4,5].scan i32.type.sum
```
results in
```
[1,3,6,10,15]
```
Also fixes a typo in the comment of `fold`.
> lib: add list/Sequence.scan to create list of folds or prefix lists

- src/dev/flang/be/c/C.java
`define _POSIX_C_SOURCE` always needs to be first
> be/c: fix `-useGC`

- tests/negative.mk
- tests/positive.mk
- tests/simple.mk
- tests/simple_inp.mk
saves a bit of typing when testing all backends at once.
Instead of:
`make int c jvm -C build/tests/some_test`
it now suffices to type:
`make -C build/tests/some_test`
> tests: add default `all` rule

- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/be/jvm/JVM.java
- src/dev/flang/be/jvm/Names.java
- src/dev/flang/be/jvm/Types.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- tests/unicode/skip_jvm
This reduces the code size significantly whenever a call can be bound statically to the static type, i.e., the precondition and the routine that is called come from the same clazz.
Since initialization of structured constants now uses the new combined method that checks the precondition as well, this fixes the missing preconditions checks for these constants. However, these checks are now performed earlier and the stack trace does not show the position of the faulty call.
This enhances #2159, but there is still room for improvement, in particular we should split up the static initializer of class `fzC_universe` in case of too many too large constants.
> jvm: reduce code size of calls by combining precondition and routine call

- src/dev/flang/ast/AstErrors.java
- src/dev/flang/ast/Call.java
This PR is slightly redundant since it adds code to prevent these subsequent errors at two locations, in AstErrors and and Call, just to make it more robust.
This fixs the jenkins failure of examples/examples/man_or_boy2.fz due to additional error output.
> ast: Avoid subsequent errors in case error is merged during type inference

- bin/aspell.dict
- src/dev/flang/ast/AbstractAssign.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Destructure.java
- src/dev/flang/ast/Feature.java
resultTypeRaw(res) is now called resultTypeIfPresent(res)
fixes #2198
> cleanup `resultTypeRaw` `resultTypeIfPresent`

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/ArrayConstant.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Function.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/ResolvedNormalType.java
- src/dev/flang/ast/Types.java
- src/dev/flang/ast/UnresolvedType.java
- src/dev/flang/fe/LibraryFeature.java
Types.intern was called all over the place. Now only in `ResolvedTypes.create()` and `ArtificialBuiltInType.resolveArtificialType`
> intern types at creation

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Case.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/FormalGenerics.java
- src/dev/flang/ast/OuterType.java
- src/dev/flang/ast/Resolution.java
- src/dev/flang/ast/ResolvedNormalType.java
- src/dev/flang/ast/SrcModule.java
- src/dev/flang/ast/Types.java
- src/dev/flang/ast/UnresolvedType.java
- src/dev/flang/fe/SourceModule.java
- tests/generics_negative/generics_negative.fz
- tests/reg_issue309_check_constraints_of_types/issue309.fz
- tests/visibility_modules_negative/main.fz.expected_err
This is a major cleanup of the spaghetti style code that performs type resolution.  Methods `findGenerics` and `resolveFeature` are now both part for `UnresolvedType.resolve` and no longer needed in `AbstractType`.
Other methods like `AbstractType.resolveThisType`, `AbstractType.ensureNotOpen`, `ResolvedNomralType.resolve`, `ResolvedNormalType.resolveGenerics` and one varaint of `SourceModule.lookupType` could also be removed.
One important special handling remains after this patch: For type inference within match cases, a `clone()` of a partially resolved `ResolvedNormalType` is created that later gets its actual type parameters resolved.
Tests were changed as follows:
- Added `a` and `b` to the error case `49` in `tests/generics_negative` since that case appeared twice.
- Fixed …
> ast/tests: join findGenerics with resolve in UnresolvedType

- src/dev/flang/be/c/CTypes.java
```
// for clazz#1: value Any
struct fzT_Any
{
};
// for clazz#0: Any
struct fzT__RAny
{
uint32_t clazzId;
fzT_Any fields;
};
// for clazz#5324: (exit.#type#1 exit).default_exit_handler#0
struct fzT__L5324exit_oHtyp__u_handler
{
};
...
```
> be/c: add clazz id in comment for structs

- src/dev/flang/ast/ResolvedNormalType.java
This prevents subsequent errors such as
-:14:21: error 4: Ambiguous assignment to 'list **error**' from 'nil'
test3 list foo := nil          # error!
--------------------^^^
'nil' is assignable to 'nil', '**error**'
which currently appears in flang.dev's `content/design/examples/typ_abstr.fz`.
Also removed some constructors form `ResolvedNormalType.java`.
> ast: Resolve a type as t_ERROR if any type arg is t_ERROR

- bin/run_tests.sh
This makes the runs more reproducable and helps finding the culprit in case one test runs very slowly (and ^C does not print the name of the running thread, only the previous ones).
> tests: When running the tests sequentially, sort them alphabetically

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/be/interpreter/Intrinsics.java
- src/dev/flang/be/interpreter/Layout.java
- src/dev/flang/util/List.java
- tests/reg_issue2214/Makefile
- tests/reg_issue2214/issue_2214.fz
- tests/reg_issue2214/issue_2214.fz.expected_out
The problem with `Clazz.actualClazz` was that it replaces all generics found in parents and in outer features.  This is a problem when a feature inherits from one of its outer features since there are two possible values of the actual generics and for the examplein #2214, the wrong one was used.
With this patch, `Clazzes.down` now hands down an inherted type along the inheritance change in each nesting level of features, so we have much better control how inherited types are replaced by the actual values provided in the inherts-call.
This patch also adds a test case with the code from #2214 plus the flang.dev example `primes6_broken_map.fz` that showed this problem since a long time.
> air: replace Clazz.actualClazz by Clazz.handDown(), fix #2214

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractType.java
Open type parameter select-indices might be wrong as a consequence of earlier compilation errors.
> air: harden code against previous errors

- src/dev/flang/be/c/C.java
- tests/reg_issue1835/Makefile
- tests/reg_issue1835/issue_1835.fz
- tests/reg_issue1835/issue_1835.fz.expected_out
fixes idiom82
fixes https://github.com/tokiwa-software/fuzion/issues/1835
> be/c: don't deref heap cloned result of call

- src/dev/flang/be/jvm/classfile/ClassFile.java
In newer jvm-specs:
"If the ACC_INTERFACE flag is set, the ACC_ABSTRACT flag must also be set, and the ACC_FINAL, ACC_SUPER, ACC_ENUM, and ACC_MODULE flags set must not be set."
> be/jvm: set flag abstract in case of interface

- src/dev/flang/ast/AbstractFeature.java
- src/dev/flang/ast/Feature.java
- src/dev/flang/ast/ResolvedNormalType.java
- src/dev/flang/fe/SourceModule.java
This ensures that free types have been identified and added to the type parameters of the outer feature.
fixes #1787
> call `addOuterRef` only once decl. of outer resolved

- src/dev/flang/ast/Block.java
- src/dev/flang/ast/Call.java
- tests/reg_issue874ff/issue874.fz
fixes #2266
because this then is later tagged to become a `choice unit ...`
> fe: empty block not resulting in `unit`, needs call to `unit` added.

- tests/typeinference_negative/typeinference_negative.fz
The tests produced a different error than the expected one, so this was not obvious: a declaration of the form
```
x => z; y => x; z => y
```
is equivalent to
```
x =>
z
y =>
x
z => y
```
while this test needs
```
x => {z}; y => {x}; z => {y}
```
which is equivalent to
```
x => z
y => x
z => y
```
> tests: fix syntax of single-line declarations

- lib/bool.fz
These correspond the the infix operators `&`, `|` and `^`.
> lib: Add monoids `all`, `any` and `parity` ot `bool.type`

- lib/option.fz
Inspired by AoC 2023/03, this permits concatenating option to an existing Sequence without pattern matching.
> lib: make option a Sequence

- src/dev/flang/ast/Call.java
The problem was that for a call without an explicit target, Call._target is originally null and the called feature was searched in all outer features. If found, _target is set to the corresponding `outerFeature.this` expression.
The code to check that there is no ambiguous partial application now must not restrict its search to this target, but use the null target.
In case of fields, using a specific target could even result in finding more fields due to scope checking that only happens for unqualified (i.e., w/o target) calls to fields.
This caused a failure in flang.dev's `design/examples/aborteffect.fz`.
> ast: Fix check if there is an ambiguous partial application

- src/dev/flang/ast/Call.java
sorry, I lost the test case to reproduce this, so no regression test...:-(
> ast: Also ran into this issue: sometime null gets propagated as expected type

- src/dev/flang/ast/Impl.java
- src/dev/flang/ast/Resolution.java
- src/dev/flang/parser/Parser.java
- tests/typeinference_for_formal_args/Makefile
- tests/typeinference_for_formal_args/typeinference_for_formal_args.fz
- tests/typeinference_for_formal_args/typeinference_for_formal_args.fz.expected_out
This fixes #2290 by first resolving everything else before we are resolving a feature whose argument types are inferred from actual arguments.
Since type inference can results in some awful circles here, I had to add a check for such circles to avoid type inference in case of such a circle.  For now, a circle is just ignored expecting this to occur only in case of recursion. Consequently, only types provided when entering this recursion will be considered for type inference for arguments.
This patch adds a number of tricky type inference tests that model the example from #2290 and indirect recursion.
Also, test scenarios were added where inference is used without any actual calls and the type ends up being `void`, which is wrong.  This should be revisited within #2308.
I also added code …
> ast/tests: Delay resolution of features with args whose types are inferred

- lib/time/duration.fz
This results in nicer output, e.g, in the example of #2323.
> lib: Made result of time.durations.as_string fixed with

- lib/Sequence.fz
- lib/array.fz
- lib/list.fz
- lib/uint.fz
These could habe been useful for today's AdventOfCode puzzle.
Renamed reverse in array and list as reverse_array and reverse_list, resp.
> AoC PR: lib: Add reverse, map_pairs, fold1 and foldf to Sequence

- src/dev/flang/util/Profiler.java
First, this filters out stacks that are empty and contain no information. Seems like they come from threads that do not execute any Java code.
Second, the stack frames were always missing the innermost entry, so this is added now.
> util: Fixes two issues with the stacks produced by -XjavaProf option

- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/cfg/CFG.java
- src/dev/flang/util/List.java
CFG was the deepest recursion when translating a small application, while DFA was at second position.  This significantly flattens recursion shown in -XjavaProf-generated flame graphs.  This might also improve performance by better memory access locality.
> me: Reduce recursion depth of CFG and DFA

- lib/io/buffered/reader.fz
- lib/io/stdin.fz
There are three changes in this patch:
1. big preformance improvements by avoiding list iteration
2. smaller performance improvements by reading several bytes at once
3. additioonal convenience APIs for reading a file fully
Replaced `while (mutate.flat_map_sequence u8 x->x).count < n` by `n_read < n`. This was by far the biggest performance issue when reading bytes since it required time in O(n²).
Replaced `drop` in `reader.discard` by `slice` which is O(1) and does not cause deep recursion.
Add a version of io.buffered.reader.read with an argument max_n that gives the desired number of bytes to be read.
io.stdin.read_provider.read no longer restrics the number of bytes to just one, but tries to read count bytes. This change currently breaks the C backend since the C intrinsic apparently …
> AoC PR: lib: performance and API improvements for stdin and reader

- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/ResolvedNormalType.java
- tests/call_with_ambiguous_result_type_negative/call.fz.expected_err
- tests/reg_issue1054_incompatible_contraint_generics/issue1054.fz.expected_err
- tests/reg_issue1216_precondition_box_constructor/test_issue1216.fz.expected_err
- tests/reg_issue7_genericConstraint/checkGenericConstraint.fz.expected_err
This was changed in the source code a while ago, so we have to change the error output accordingly.
> fe: When printing types, use "xyz.this" not "xyz.this.type"

- lib/pipes.fz
- src/dev/flang/ast/Call.java
- tests/partial_application_negative/partial_application_negative.fz.expected_err
First, this adds the ability to use partial application with functions that have type parameters.
Then, this adds `infix |>`, `infix ||>`, as functions with type parameters to the universe.
> fe/lib: Support partial application w/ type parameters, add `infix |>`,... fix #2354

- lib/float.fz
- lib/log.fz
> lib: add `log`, alternative to `say` that returns its argument

- lib/Sequence.fz
- lib/array.fz
- lib/mutate.fz
The redefinition of `count` in `Mutable_Array` now has O(1) performance.
Similarly, redefine `Sequence.drop` in `array` and result of `array.slice`. This improves the performance of `drop n` from O(n) to O(1).
I did not add a redefinition of `drop` to `Mutable_Array`, I am not sure if `Mutable_Array` should be a `Sequence` at all.
> lib: Redefine count and drop for array backed sequences

- lib/effect.fz
- lib/handles2.fz
removed unused `return` and `use0`
also removed `effect_mode.abort` which seems useless?
> lib: cleanup `effect.fz`

- src/dev/flang/be/c/C.java
Enable frame pointers as fedora and ubuntu decided to do. More information on why this might be a good idea: https://fedoraproject.org/wiki/Changes/fno-omit-frame-pointer and:
https://lobste.rs/s/avrfxz/ubuntu_24_04_lts_will_enable_frame
> be/c: `-fno-omit-frame-pointer`

- src/dev/flang/ast/Partial.java
- src/dev/flang/ast/Types.java
- src/dev/flang/be/c/C.java
- src/dev/flang/be/c/CTypes.java
- src/dev/flang/fuir/FUIR.java
- src/dev/flang/fuir/analysis/dfa/Call.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
- src/dev/flang/fuir/analysis/dfa/SysArray.java
- src/dev/flang/parser/OpExpr.java
In lib this renaming has been done a long time ago. It is now confusing to have it named Object in FUIR.
> rename: `clazzObject` -> `clazzAny`

- lib/fuzion/java.fz
- src/dev/flang/be/interpreter/Intrinsics.java
- tests/javaBase/javaHello.fz
- tests/javaBase/javaHello.fz.expected_out
- instead of the pointer pass whole `internal_array` to backend
- this will be needed for the c-backend since there we need to know the length of the array
> interpreter: change implementation `array_to_java_object0`

- src/dev/flang/air/Clazz.java
- src/dev/flang/air/Clazzes.java
- src/dev/flang/ast/AbstractAssign.java
- src/dev/flang/ast/AbstractCall.java
- src/dev/flang/ast/AbstractCase.java
- src/dev/flang/ast/AbstractMatch.java
- src/dev/flang/ast/Box.java
- src/dev/flang/ast/Case.java
- src/dev/flang/ast/Env.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/HasGlobalIndex.java
- src/dev/flang/ast/If.java
- src/dev/flang/ast/InlineArray.java
- src/dev/flang/ast/Tag.java
- src/dev/flang/be/interpreter/Interpreter.java
- src/dev/flang/fe/FrontEnd.java
- src/dev/flang/fe/LibraryCall.java
- src/dev/flang/fe/LibraryFeature.java
- src/dev/flang/fuir/FUIR.java
The use of unique ids for all AST elements that need runtime clazz information plus arrays large enough to hold all these ideas in every clazz instance results in memory demand quadratic to the code size resulting in the high memory demand for arrays used in ryu.fz and reported in #2408.
This patch replaces these large arrays by per-clazz TreeMaps that contain only those actual clazzes that are actually needed for that clazz.
This also adds some NYI-comments related to #2411 and #2412.
This removes caching of Callable created in the interpreter, so this might have a negative impact on interpreter performance.  We might to re-introduce a caching mechanism if this turns out to be very costly.
> me: Replace runtime clazzes by clazz-local map of actual clazzes, fix #2408

- lib/effect.fz
This fixes two earlier patches that broke tests on flang.dev: `return` is used in some tests and `return` seems to be conform better to the established terminology for algebraic effects.
`use` is documented to ignore an `abort`, but it did panic instead since it was implemented using `go`.
> lib: effect: restore `return` and fix `simple_effect.use`

- src/dev/flang/util/Errors.java
Since the JVM backend runs in a new thread we might run into concurrency issues when creating errors. This causes flaky jenkins test runs such as content.design.examples.res_intri.fz.
This patch synchronizes all methods that save, access or output warnings and errors.
> util: make error and warning output thread-safe

- src/dev/flang/air/Clazz.java
The problem was that intrinsic `effect.type.is_installed` was not found to be called since its outer feature was not found to be instantiated.  This patch changes this to treat all type features as implicitly instantiated.
This fixed the JVM and C backend failures for `idiom87ex.fz`: Here. the call to `effect.type.is_installed` was the only place that could create a bool values but was not found to be called, so `true` and `false` were both effectively `void` resutling in no code generatored for any case in a match of boolean (where an `if` is just syntax sugor for such a match).
> air: Consider all type features as instantiated

- src/dev/flang/be/interpreter/Interpreter.java
This fixes a precondition failure in flang.dev's
`tutorial/examples/assignment_example4.fz` since this example does not create a clazz for bool.
> be/interpreter: Replace `Clazz.bool.get` by `Clazz.bool.getIfCreated`

- src/dev/flang/fuir/analysis/AbstractInterpreter.java
The debug output enabled via
```
FUZION_JAVA_OPTIONS=-Ddev.flang.fuir.analysis.AbstractInterpreter.DEBUG=true
```
results in large amounts of output that could be hard to handle.
With this patch, one can now use a regex to print only abstract interpretation of those features whose name match a given regular expression.
> fuir: permit regular expressions to debug AbstractInterpreter

- Makefile
- doc/ref_manual/demo_rule.txt
- doc/ref_manual/fuzion_reference_manual.adoc
- doc/ref_manual/rule.adoc
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/util/Errors.java
- src/dev/flang/util/SourceFile.java
Rules of the Fuzion language may now be embedded in the source code, they will be wrapped by `rule.adoc` when generating the reference manual.
Rulese have an ID that consists of a domain and detail in that domain that is addressed by the rule.
Errors now may (and eventually will) have an ID that corresponds to the rule that is broken when this error is created.  Errors for the rule `SRCF_UTF8` have been changed to use their ID for error reporting.
Preliminary infrastructure to document the Unicode version Id in the reference manual was implemented.
> doc/util/fe: First intergration of rules, error ids and reference manual

- lib/pipes.fz
`<|` is not very useful since `f <| a` is the same as `f a`, but all the others are.
Also fixed a comment and removed `.values`  from comments.
> lib: Add `<|`, `<||`, etc. to establish symmetry with `|>` , `||>`, etc.

- .github/workflows/windows.yml
- .github/workflows/windows_c.yml
- README.md
- bin/windows_install_boehm_gc.sh
- src/dev/flang/be/c/C.java
also added a script to download and build `libgc`
Three tests seem to be failing on windows, currently:
./build/tests/atomic: failed
./build/tests/lock_free_stack: failed
./build/tests/sockets: failed
> workflow: windows builds, add step `build libgc`

- src/dev/flang/be/jvm/runtime/Intrinsics.java
HelloWorld_random.fz uses this.
Please describe your changes here.
> jvm: enable `env_vars.get` since this is required in the Fuzion tutorial

- src/dev/flang/air/Clazz.java
- src/dev/flang/ast/AbstractCurrent.java
- src/dev/flang/ast/AbstractType.java
- src/dev/flang/ast/Call.java
- src/dev/flang/ast/Expr.java
- src/dev/flang/ast/ResolvedNormalType.java
- src/dev/flang/fe/SourceModule.java
- src/dev/flang/fuir/FUIR.java
I find this to be significantly easier to read than `compareTo != 0`
Also removed a now unecessary string comparison checking for `void.absurd` feature.
> ast/type: add method `isVoid`

- src/dev/flang/be/jvm/JVM.java
fixes #2477
I did not add a regression test, since it would not terminate.
> fix VerifyError, returning result field that does not exist

- lib/composition.fz
Added links to Gabriel Lebec talk and Devid Kenan and Chris Rathman pages.
Added birds for identity: idiot / ibis
Added M/Mockingbird `\f.ff`, which is tough in a statically typed language, cannot be defined in Haskell and probably neither in Fuzion, but still playing around with it.  Also added ``M* which seems to be definable in JavaScript, need to check if that helps.
Added thrush and vireo.
Moved `before1`/`before2` closer to compose since they are all Bluebirds.
Added `Y` and `Z` combinator, but mostly as comments for now.
> lib: more links, comments and code for composition

- examples/javaGraphics/gfx.fz
Java 21 introduced a new method java.lang.Thread.sleep that takes a java.time.Duration in addition to the variant that takes a long. The fzjava mangling chooses this as a default variant now, making these calls lead to unexpected type errors. Fix this by explicitly selecting the version of the sleep method that takes a long.
> examples/javaGraphics: fix call to java.lang.Thread.sleep

- release_notes.md
> fix syntax in example

- src/dev/flang/be/jvm/runtime/Intrinsics.java
This can't do much harm and it is used in examples in `tutorial/void_type`.
> jvm: make `fuzion.std.exit` safe for use in fuzion-lang.dev

- lib/Sequence.fz
- lib/list.fz
This results in useful output as in
```
> echo "say [1,2,3].cycle" | ./build/bin/fz -
[1,2,3,1,2,3,1,2,3,1,…]
```
Instead of crashing with an out of memory or stack overflow error.
> lib: limit number of entries shown by `as_string` for non-finite Sequences

- src/dev/flang/ast/AstErrors.java
In case any of the branches in an if or a match results in `***error***` we do not want to report this unless there were no previous errors.
> ast: suppress subsequent error `Incompatible result on branches of ...`

- lib/Sequence.fz
- lib/Stream.fz
- tests/choice_mix/choice_mix.fz
- tests/partial_application_negative/partial_application_negative.fz.expected_err
- tests/qualified_declaration/qualified_declaration.fz
- tests/rosettacode_factors_of_an_integer/factors.fz
- tests/rosettacode_man_or_boy/man_or_boy.fz
- tests/rosettacode_primes/primes.fz
This seems more useful than the previous `for_each` this was an alias for. New alias for `for_each` is `infix !`.
Remove redefinition of `infix |` from `Stream`.
Replaced `list` by `Sequence` in a comment.
> lib: Make `Sequence.infix |` an alias for `map`

- lib/Sequence.fz
- lib/list.fz
Reverts tokiwa-software/fuzion#2520
Reverting this for now since this broke `test/lazy`.
Because of the following line of code in `as_string` Sequence is evaluated twice... 
```
if finite || ((map _->unit).drop max).is_empty
```
This leads to once being printed not ten but twenty times in this code:
```
lst(T type, h T, t Lazy (list T)) list T =>
ref : Cons T (list T)
head => h
tail => t
once => say "eval once!"; lst 1 once
say "x"
say (once.take 10)
say "y"
```
> Revert "lib: limit number of entries shown by `as_string` for non-finite Sequences"

- lib/Sequence.fz
- lib/list.fz
- tests/partial_application_negative/partial_application_negative.fz.expected_err
This results in useful output as in
```
> echo "say [1,2,3].cycle" | ./build/bin/fz -
[1,2,3,1,2,3,1,2,3,1,…]
```
Instead of crashing with an out of memory or stack overflow error.
Compared to #2520, this does not cause repeated evaluation of list elements and it also updated error output of one test.
> lib: limit number of entries shown by as_string for non-finite Sequences

- lib/container/Set.fz
- lib/container/ps_set.fz
- modules/lock_free/src/lock_free/map.fz
`Set.add` being `abstract` resulted in errors for heirs of `Set` that to not have `add` when running the idioms.
Eventually, `Set.add` should be removed and we should have a proper integration of mutable Sets with the `mutate` effect or some lock-free-concurrency effect.
Also removed `Set.remove` since this seems unused but could cause similar problem.s
> lib: implement `Set.add`

- src/dev/flang/be/jvm/CodeGen.java
This is related to #2325, #1686 and #1588, the lifetime analysis is probably still too conservative.
> be/jvm: Check lifetype of current instance on tail recursive call optimization

- Makefile
I sometimes find this to be helpful even though you will likely have to do some manual reverts after rerecording.
> makefile: add `rerecord_simple_tests`

- src/dev/flang/be/c/C.java
- src/dev/flang/be/jvm/CodeGen.java
- src/dev/flang/fuir/analysis/AbstractInterpreter.java
- src/dev/flang/fuir/analysis/dfa/DFA.java
This can be obtained via `_fuir.clazzChoice(newcl, tagNum)`.
> analysis: Remove `valuecl` arg from `AbstractInterpreter.ProcessorStatement.tag`

- src/dev/flang/be/jvm/JVM.java
- src/dev/flang/be/jvm/JVMOptions.java
- src/dev/flang/tools/Fuzion.java
This is useful when using -jar/-classes in scripts. E.g. for benchmarking
> be/jvm: -jar/-classes add option [-o=<outputName>]

- include/fz.h
- include/posix.c
- include/win.c
- lib/io/file/open.fz
- lib/io/file/read.fz
- lib/io/file/seek.fz
- lib/io/file/write.fz
- src/dev/flang/be/c/C.java
- src/dev/flang/be/c/CNames.java
- src/dev/flang/be/c/Intrinsics.java
- src/dev/flang/be/jvm/runtime/Intrinsics.java
- tests/fileio/fileiotests.fz
- tests/fileio/fileiotests.fz.expected_out
With this change all POSIX-only code is removed from the compiler and moved to external *.c-files.
It believe the compiler now emits code that only follows the C99 or C11 standard. The exception to this are the uses of `__atomic*` builtins.
> be/c: move posix code from intrinsics to posix.c

- src/dev/flang/parser/Parser.java
`is` can no longer be used with a return type. Added detail to explain this case.
> parser: Fix and clarify comment

- src/dev/flang/ast/AstErrors.java
These produced additional errors while I was working on fixing #149.
> ast: supress subsequent error caused by type `Types.t_ERROR`

- lib/Sequence.fz
- lib/String.fz
- lib/array.fz
- lib/array2.fz
- lib/array3.fz
- lib/codepoint.fz
- lib/container/searchable_sequence.fz
- lib/container/sorted_array.fz
- lib/i16.fz
- lib/i32.fz
- lib/i64.fz
- lib/integer.fz
- lib/num/ryu.fz
- lib/num/wrap_around.fz
- lib/num_option.fz
- lib/numeric.fz
- lib/option.fz
- lib/outcome.fz
- lib/time/date_time.fz
- src/dev/flang/ast/Cond.java
- src/dev/flang/parser/Parser.java
- tests/choice_mix/choice_mix.fz
Syntactially, the conditions in a pre/post condition or the (unused) invariant are now parsed as `exprs`, i.e. like an indented block in a feature declaration.
Conditions are no longer separated by commas, but by semicolons or non-indenting new lines.
The Fuzion grammar becomes slightly simpler with rules `cond` and `condList` removed.
Updated syntax of conditions in base lib and tests where `,` was used, added `debug:` qualifiers at some places and `(`/`)` for clarity, it is a bit unfortunate that, e.g., `debug: -a = b` is parsed as `((debug.postfix :) - a) = b`...
> parser: conditions are now syntactically the same as `exprs`, fix #149

- src/dev/flang/be/jvm/runtime/Runtime.java
This does not include all `fuzion.java` intrinsics, but the ones which seem the most likely to cause damage.
Related: #2590
> be/jvm: mark the most dangerous `fuzion.java` intrinsics unsafe
