tokiwa-software/fuzion

src/dev/flang/ast/FeatureName.java
=> FIX FeatureName.java: error: illegal character: '\u2039'

src/dev/flang/ast/Resolution.java
- ...go to step 11... should be ... go to step 10...
=> correct minor mistake in doc comment of class resolution

README.md
=> Readme.md: improve windows build instructions

examples/complex/pythagoreanTriple.fz, lib/complex.fz, tests/generics/genericstest.fz, tests/lists/lists.fz, tests/redef_args/redef_args.fz
1) renamed i=>imag, r=>real
2) added definition of i
=> Stdlib complex

.github/workflows/release.yml, Makefile
example result can be seen here:
https://github.com/michaellilltokiwa/fuzion
=> add github workflow for github releases

Makefile
- name of folder: fuzion_$(VERSION)
=> Makefile, release: put everything in tar file in one parent folder

bin/ebnf.sh, bin/fz, bin/fzjava, bin/run_tests.sh, tests/_cur_dir.sh, tests/check_simple_example.sh, tests/check_simple_example_c.sh, tests/record_simple_example.sh, tests/record_simple_example_c.sh
shellcheck -f diff [files] | git apply
=> shellscripts: aplly suggested fixes of shellcheck

Makefile
- analyze shell scripts in the repository for potential problems
=> Makefile: add phony target shellcheck

lib/Sequence.fz
does basically the same as:
- Stream.reduce() in Java
- [].reduce in Javascript
- Enumerable.Aggregate in C#
- ...
=> stdlib: Sequence, add feature reduce

lib/string.fz
- returns true if string is empty or contains whitespace only
=> stdllib: string, implement feature isBlank

Makefile, bin/run_tests.sh
This change is in preparation of running the tests on CI.
=> Run tests exit code 1 on error

lib/f32s.fz, lib/f64s.fz, lib/floats.fz, lib/u32.fz, lib/u64.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, tests/floating_point_math/Makefile, tests/floating_point_math/err.txt, tests/floating_point_math/floating_point_math.fz, tests/floating_point_numbers/floating_point_numbers.fz
- math (sin,cos,log,...)
- minExp, maxExp, minPositive, epsilon, max
- casts from and to f32/f64
=> basic floating point operations

lib/float.fz, lib/integer.fz, lib/numeric.fz, tests/floating_point_math/floating_point_math.fz
- from_u32
- to_u32
- highest
- two
- ten
=> lib: move generic features from integer to numeric

lib/psSet.fz
Another possible solution without the need for a for-loop.
=> lib/psSet: implemented addAll via reduce

tests/floating_point_math/floating_point_math.fz
result type of round was changed to float
=> tests: fix test floating point math

lib/Sequence.fz
I think with "may" the description is more accurate.
=> lib/Sequence: revise comment on element calculation

src/dev/flang/be/c/C.java
fixes failing test concur_simple
=> be/c: link libpthread

lib/io/in.fz
Made line_feed a routine, moved it to stdins and let stdin inherit from stdins.
=> lib: Workaround for #317

lib/fuzion/std/fileio.fz, src/dev/flang/be/interpreter/Intrinsics.java
readFile intrinsic reads a byte in a specified position from a file and returns it
=> readFile implementation

lib/io/file/stat.fz
io.file.stat effect will contain operations to retrieve file stats such as size, modification date etc
stats operations will return info that are similar to the content of a C stat struct regarding files
=> io.file.stat effect

src/dev/flang/ast/AbstractType.java
All I did was move the for-loop into the else-block.
Unfortunately the github diff is hard to read, vscode is better:
=> ast: must not call generics() on generic argument

lib/floatSequence.fz
this is basically idiom 201:
https://www.programming-idioms.org/idiom/201/euclidean-norm
=> lib: float sequence, get euclidean norm

lib/fuzion/std/fileio.fz, lib/io/file/write.fz, src/dev/flang/be/interpreter/Intrinsics.java
I am not sure whether I need to make the return type as outcome or just bool
=> adding error handling to the fileio.write feature

lib/time/stopwatch.fz
The idea for this is from idiom 132:
https://www.programming-idioms.org/idiom/132/measure-duration-of-procedure-execution
=> lib/stopwatch: feature to measure execution duration of function

.github/workflows/linux.yml
This should allow test runs using GitHub Actions. This workflow is triggered manually for the time being.
=> GitHub Actions: Add Linux workflow

src/dev/flang/tools/Fuzion.java
Simplified nested conditionals, made naming more consistent.
=> tools: Cleanup application argument parsing

lib/i128.fz, lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/integer.fz, lib/u128.fz, lib/u16.fz, lib/u32.fz, lib/u64.fz, lib/u8.fz, lib/wrappingInteger.fz
=> lib/wrappingInteger: implement bitwise NOT

Makefile
=> Makefile: do not IGNORE test run errors

src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/tools/Fuzion.java
FrontEndOptions._moduleDirs is now never null.
=> fe/tools: Fix NullPointerException when 'base.fum' is missing, fix #571

src/dev/flang/ast/If.java, src/dev/flang/fuir/analysis/Escape.java, tests/reg_issue536_if_statement_missing_default_else_branch/Makefile, tests/reg_issue536_if_statement_missing_default_else_branch/issue536.fz, tests/reg_issue536_if_statement_missing_default_else_branch/issue536.fz.expected_out
=> ast/If: issue 536, default else branch returns `unit`

lib/ctrie.fz
=> lib/ctrie: remove unnecessary feature set_prev, remove false NYI comment

lib/io/file/write.fz
Changed the indentation from 4 spaces to 2 spaces.
Also added shorthand to create and install write effect.
=> adding `create_dir` feature to `write` effect

Makefile
=> Makefile: allow building without java modules

bin/run_tests.sh, bin/run_tests_parallel.sh
=> bin/run_tests.sh: be noisy, fix shellcheck issues

tests/reg_issue175_int_crash/Makefile, tests/reg_issue175_int_crash/issue175.fz
=> tests: add reg test for issue 175

.devcontainer/devcontainer.json
=> github: add devcontainer config

src/dev/flang/air/Clazzes.java
=> air: add Clazzes.reset, a method to clear statically held things

src/dev/flang/ast/Function.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/tools/Tool.java, src/dev/flang/util/Errors.java, src/dev/flang/util/FatalError.java, src/dev/flang/util/unicode/ParseUnicodeData.java
=> Errors: add ability to prevent System.exit

tests/reg_issue119/Makefile, tests/reg_issue119/issue119.fz
=> tests: add regression test for issue 119

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Match.java, src/dev/flang/parser/Parser.java, tests/reg_issue662_match_cases_missing/Makefile, tests/reg_issue662_match_cases_missing/issue662.fz, tests/reg_issue662_match_cases_missing/issue662.fz.expected_err
Cases will be checked during resolveTypes.
=> ast: Allow match with empty cases in parser.

lib/ctrie.fz
eventually this should use an atomic compare and set operation but for now `mut` will do
=> lib/ctrie: use mut instead of set

lib/Set.fz, lib/setOf.fz
This is probably not optimal, I suppose it would be better using CTrie's remove operation, but this would mutate the Set inplace.
=> set_of: add remove feature

lib/Sequence.fz
a variant of reduce that is abortable with success or error
=> lib/Sequence: add reduce_or_error

src/dev/flang/ast/FeaturesAndOuter.java
=> ast: fix #364 IndexOutOfBoundsException in Call.splitOffTypeArgs

src/dev/flang/air/Clazzes.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Impl.java, src/dev/flang/tools/Fuzion.java, tests/reg_issue350_x_ref_produces_strange_error_message/Makefile, tests/reg_issue350_x_ref_produces_strange_error_message/issue350.fz, tests/reg_issue350_x_ref_produces_strange_error_message/issue350.fz.expected_err
=> ast: `x ref=>`, fix strange error and NP-exception

.github/workflows/windows.yml
The underlying reason is unknown to me but using openjdk 17 seems to fix the problem...
See:
https://github.com/michaellilltokiwa/fuzion/actions/runs/3547622307/jobs/5957941482
=> tests: fix windows tests

src/dev/flang/air/Clazzes.java
=> air: fix #451, require condition failure in case of errors.

src/dev/flang/ast/Feature.java, tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/Makefile, tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/issue698.fz, tests/reg_issue698_np_excep_in_choice_with_call_to_outer_ref/issue698.fz.expected_err
=> ast: show error for closure access in choice via anonymous feature

src/dev/flang/ast/AstErrors.java
See <https://github.com/tokiwa-software/fuzion/pull/699#issuecomment-1331842251>.
=> ast: suggest a solution when accessing surrounding scope from choice

src/dev/flang/be/c/C.java
some warnings are excluded though
=> be/c: enable -Wall -Werror by default

src/dev/flang/util/List.java
Every once in a while I felt like I could have used this.
=> util: list, add collector

lib/numeric.fz, lib/wrappingInteger.fz
Link: https://english.stackexchange.com/a/3642
=> lib: substraction => subtraction

lib/outcome.fz
=> lib/outcome: turn into a monad

lib/numeric.fz, src/dev/flang/ast/Consts.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, tests/covariance/test_covariance.fz
This keyword no longer has any effect.
=> lib/parser/ast/tests: Remove 'dyn' keyword

src/dev/flang/parser/Parser.java
So in a call, 'x.this.type' can be evaluated as value parameter. Currently missing is support for this value to represent the actual outer feature.
=> parser: Adding 'thistype' to be parsable as an expression, fix #817

lib/fuzion/std/fileio.fz, lib/io/file/stat.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java, tests/fileio/fileiotests.fz
Superseded by the stats/lstats intrinsics and the stat effect.
=> lib: io: remove exists effect and intrinsics

lib/Sequence.fz, lib/list.fz
See also: <https://github.com/tokiwa-software/fuzion/pull/789#discussion_r1049523594>
=> list, Sequence: clarify behaviour of first, last and forceTail when empty

src/dev/flang/air/Clazzes.java, tests/reg_issue459_choice_elment_tagged_that_is_never_instantiated/Makefile, tests/reg_issue459_choice_elment_tagged_that_is_never_instantiated/issue459.fz, tests/reg_issue459_choice_elment_tagged_that_is_never_instantiated/issue459.fz.expected_out
=> air: fix #459 choice element being tagged that is never instantiated

src/dev/flang/air/Clazzes.java
And a minor simplification of the code
=> air: cleanup: consistent indentation

src/dev/flang/ast/Call.java, src/dev/flang/fe/SourceModule.java
Fix argss in example call and use new syntax. Fix upper/lower case error.
=> ast/fe: Minor fixes in comments

lib/cache.fz
This also makes use of the new functionality that allows code to be added to the comments of features, which will be executable on flang.dev.
=> lib/cache: improve documentation using better example

src/dev/flang/tools/docs/Html.java, src/dev/flang/tools/docs/Util.java
And drop redundant copy of comments of redefined features.
=> docs: link to redefined features

src/dev/flang/tools/fzjava/FZJava.java
=> fzjava: fill existing features list on demand

src/dev/flang/ast/Type.java, tests/reg_issue874ff/issue874.fz
Also added corresponding test code tests/reg_issue874ff
=> ast: ignore generics for types of the form x.this.type, fix #930

lib/Sequence.fz, lib/Set.fz, lib/array.fz, lib/comparable_sequence.fz, lib/ctrie.fz, lib/fuzion/java.fz, lib/integer.fz, lib/marray.fz, lib/numeric_sequence.fz, lib/searchable_list.fz, lib/searchable_sequence.fz
Also added `Sequence.finite` and redefined it to avoid endless recursion in precondition of `count`.
=> Add infix w/o args to sequence

src/dev/flang/ast/Call.java
This is in preparation of working on #961.
=> ast: Cleanup constructors in Call.java

src/dev/flang/util/Errors.java
=> Errors: reduce default maximum error count to 10

src/dev/flang/ast/Visi.java, src/dev/flang/fe/LibraryFeature.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/util/DataOut.java, src/dev/flang/util/FuzionConstants.java
=> Docs ignore feature based on visibility

src/dev/flang/air/Clazz.java, src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/SrcModule.java, src/dev/flang/fe/SourceModule.java
Reverts tokiwa-software/fuzion#983
=> Revert "fe/air: Don't lookup internal features that were added late, fix #978"

lib/local_mutate.fz
This works now, so no need for code duplication.
=> lib: Use mutable_element for new mutable vars

src/dev/flang/ast/Call.java
The result of a call to a type feature via a type parametere, e.g., `T.one` for numeric, was not properly replaced by `T`, now it is.
Since this replacement is needed also for formal argument types, moved it into a separate method.
=> ast: Fix handling of 'this.type' result of call to type feature, fix #1019

lib/f32.fz, lib/f64.fz, lib/fraction.fz, lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/u16.fz, lib/u32.fz, lib/u64.fz, lib/u8.fz
These are needed for examples in my FOSDEM'23 talks.
=> lib: Add type.zero and type.one to some numeric features

src/dev/flang/be/c/CStmnt.java, src/dev/flang/be/c/Intrinsics.java, tests/envir_vars/envir_vars.fz
This is ugly but fixes the tests on windows. 
Any ideas how to make this less ugly?
=> be/c: fix tests on windows

bin/run_tests.sh, bin/run_tests_parallel.sh
Also changed how tests are discovered. Any dir in tests with a Makefile is considered a test.
=> tests: show count of found tests

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Impl.java, src/dev/flang/parser/Parser.java
example output:
```
local redef has_next bool : Any is routine
local redef has_next bool : Any is routine
invisible #loop5stream0 i32.infix ...as_stream is field definition
invisible #loop5stream0 i32.infix ...as_stream is field definition
private #^array.#loop5 --ADDRESS-- is field
private #^array.#loop5 --ADDRESS-- is field
local redef next hasInterval.H : Any is routine
local redef next hasInterval.H : Any is routine
invisible #loop5stream0 i32.infix ...as_stream is field definition
invisible #loop5stream0 i32.infix ...as_stream is field definition
private #^array.#loop5 --ADDRESS-- is field
private #^array.#loop5 --ADDRESS-- is field
invisible #loop5(invisible x ***not yet known*** is actual argument) unit : Any is routine definition
invisible #loop5(invisible x ***not yet known*** is …
```
=> ast: move Feature.toString to AbstractFeature

src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/util/FuzionOptions.java
was in FrontEndOptions.
I will need this to be able to include files in the c backend.
=> util: move fuzionHome to FuzionOptions,

Makefile, include/fz.h, src/dev/flang/be/c/C.java, src/dev/flang/be/c/CStmnt.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/util/FuzionOptions.java
=> Move ifdef code to header file

src/dev/flang/be/c/CExpr.java, src/dev/flang/be/c/Intrinsics.java
- extract errno identifier
- allow indexing array by java int
=> be/c: two minor cleanups

src/dev/flang/air/Clazz.java
=> air: Fix some preconditions and checks that caused failures during debugging

lib/Entry.fz, lib/mutable_tree_map.fz
mutable_tree_map implements a mutable map based on AVL trees.
=> lib: introduce mutable_tree_map

lib/Lazy.fz, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/Types.java, tests/lazy/Makefile, tests/lazy/ex_lazy.fz, tests/lazy/ex_lazy.fz.expected_out
=> add syntax sugar for lazy evaluation

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/FeatureAndOuter.java, src/dev/flang/ast/FeatureName.java
=> ast: propose solution if feature is called with the wrong number of args

src/dev/flang/parser/Parser.java
The goal of this patch is to be able to parse code like
```
ints(i i32) =>
i : ints i+1
```
This currently fails since `i :` would be parsed as a feature declaration `i : parent is ..`, which is fixed by no longer basing this decisions on the `:`, but on the `is` or `=>`.
Then, `i :` would be parseed as an `anonymous`, which has very ugly syntax anyway.  This patch changes the grammar for `anonymous` to accept only `ref :` at the beginning, which is the way it is currently used and the only way that actually makes sense since the result will can only be assigned to a `ref` type of any of its ancestors.
What remains for the parser is to treat `i : ints i+1` as an infix operator call, which is what we want!
**NOTE** github messed up the display of this patch, so do not get confused. I …
=> parser: Improve grammar and parser for `:` used in inherits and anonymous

src/dev/flang/ast/AbstractType.java
AbstractType.replaceGenerics no longer performs
replace_this_type_by_actual_outer. This is needed in choiceGenerics() only and performed explicitly now.
isChoiceMatch now uses AbstractType.choiceGenerics() to avoid code duplication.
actualTypes is now private and no longer performs replace_this_type_by_actual_outer (which was needed only by choiceGenerics() and is done there explicitly now).
=> ast: Cleanup in `AbstractType.replaceGenerics` and related methods

src/dev/flang/air/Clazz.java
This requires some somewhat ugly special handling in the middle end, but I do not see a nicer solution right now.
This patch is also required as a basis for another patch for #1236.
=> air: Support for `this.type` in type parameters of type features fix #1260

src/dev/flang/ast/Tag.java
=> ast: check whether choice types are disjoint when tagging

src/dev/flang/parser/Parser.java
=> grammar: fix issue #1298, 'implicit definition of token Block'

tests/nested_options/Makefile, tests/nested_options/ex_nested_options.fz
=> add tests for nested options

lib/String.fz, tests/functions/functions.fz, tests/rosettacode_factors_of_an_integer/factors.fz, tests/rosettacode_man_or_boy/man_or_boy.fz, tests/visibility_negative/visibility_negative.fz
This does not change any comments that include refer to `fun`.
=> change occurrences of `fun` to lambdas

.github/workflows/release.yml
The workflow file was not valid:
> The workflow is not valid. .github/workflows/release.yml (Line: 4, Col: 13): Unexpected value 'read'
=> fix release yaml

src/dev/flang/fe/SourceModule.java, tests/reg_issue1380_execute_single_field_declaration/Makefile, tests/reg_issue1380_execute_single_field_declaration/issue1380.fz
=> fe: execute universe's code when single field declaration given to `fz`

lib/map_of_total_order.fz, lib/net/channel.fz
reason of breakage was incongruous merges
=> fix build of stdlib

.github/workflows/syntax_check_fuzion.yml, Makefile
- runs frontend on examples yielding any errors
- added github action for weekly checking of examples
=> make: add target syntaxcheck

Makefile
- this makes it unecessary to install bash in alpine docker container
=> Makefile: replace /bin/bash by /bin/sh

tests/sockets/sockets_test_client.fz, tests/sockets/sockets_test_server.fz
- ... explaining the number chosen for how many bytes to read
=> test/socket: add comments

tests/local_mutate/test_local_mutate.fz
- changed identifiers according to naming convention
=> tests/local_mutate: remove some NYI

src/dev/flang/util/Profiler.java
To get a classic profile, use -XjavaProf=file.prof. To create a flamegraph, use -XjavaProf=file.svg, to create input for flamegraph tool, use -XjavaProf=file.txt or -XjavaProf=- to print to stdout.
=> tools: Automatically display flame graph if -XjavaProf is set

lib/concur/thread.fz, lib/fuzion/sys/thread.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java, tests/concur_simple/concur_simple.fz
I implemented this mainly because of the ctrie tests.
=> lib: concur.threads, add `join`

lib/mutate.fz
=> remove workaround from issue #1129

src/dev/flang/ast/InlineArray.java, tests/reg_issue169_backward_type_propagation_array/Makefile, tests/reg_issue169_backward_type_propagation_array/issue169.fz
=> improve backward type propagation for arrays

src/dev/flang/fuir/analysis/AbstractInterpreter.java
=> Comment cosmetics

src/dev/flang/fuir/FUIR.java, src/dev/flang/ir/IR.java
=> fuir: codeAtAsString now shows comments

src/dev/flang/fuir/analysis/AbstractInterpreter.java
In the abstract interpreter, Pop is no longer a nop but actively pops the value from the stack and drops it.  A new method `AbstractInterpreter.drop()` gives the backend the chance to do this.
This will be required by the JVM backend where values can have side-effects, so they cannot be discarded without notice.
Also added parent `ANY` to `AbstractInterpreter.ProcessStatements`.
=> analysis: Adding JVM backend infrastructure

src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/DFA.java
Also clarified comment and removed wrong NYI-comment.
=> rename `clazzHasUniqueValue` as `ignoredOnStack`

src/dev/flang/ast/ResolvedNormalType.java
Also slight improvement in a comment.
=> ast: Fix a NullPointerException I ran into while working on fuzion.sys.Pointer

bin/aspell.dict, lib/container/searchable_sequence.fz, src/dev/flang/ast/Call.java, src/dev/flang/fuir/FUIR.java
=> lib: simplify code of count_matches_overlapping

src/dev/flang/air/Clazzes.java
not necessary anymore since #1869
=> remove workaround for marking all choice elements as instantiated.

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Generic.java, src/dev/flang/ast/ResolvedNormalType.java
also improve readability of AbstractType.compareToIgnoreOuter
=> ast: implement Comparable for Generic

README.md
Before, it looked as if we had a requirement for Windows.
=> Added Linux sub directory

tests/contracts_negative/SquareRoot.fz.expected_err_jvm, tests/reg_issue270/issue270.fz.expected_err_jvm
=> tests: fixed expected error output in case of contract failure

lib/String.fz, lib/container/ctrie.fz, lib/container/hash_map.fz, lib/f32.fz, lib/f64.fz, lib/hash.fz, lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/u128.fz, lib/u16.fz, lib/u32.fz, lib/u64.fz, lib/u8.fz
And introduce the `hash` feature in the universe, which works similar to the `equals` and `infix =` features for `type.equality`.
=> lib/property/hashable: move `hash` feature to `hash_code` type feature

src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/runtime/Runtime.java
#1904 needs to be merged first
=> be/jvm: fileio intrinsics

src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/runtime/Runtime.java
=> jvm/be: intrinsics sys.env_vars, std.nano

src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/runtime/FuzionThread.java, src/dev/flang/be/jvm/runtime/Runtime.java, tests/contracts_negative/SquareRoot.fz.expected_err_jvm, tests/reg_issue270/issue270.fz.expected_err_jvm
(based on #2036, please review/merge after #2036).
This adds a new class FuzionThread.  Static fields that hold effects are moved to instance fields FuzionThread such that we have thread local values.
=> jvm: Implement fuzion.sys.thread.spawn0

src/dev/flang/ast/AbstractType.java, tests/reg_issue1054_incompatible_contraint_generics/Makefile, tests/reg_issue1054_incompatible_contraint_generics/issue1054.fz, tests/reg_issue1054_incompatible_contraint_generics/issue1054.fz.expected_err
=> constraintAssignableFrom, check if generics are assignable

src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/JVM.java
For this, we first have to make sure that the Java stack is empty when executing cases in a choice since otherwise a tail call that performs a `goto start` would be performed with a non-empty stack resulting in classfile verification to fail.
Then, we can replace a tailcall with re-assigning the argument variables and just performing a `goto`.
=> jvm: Support tail recursion

tests/positive.mk
Getting this right is awfully hard...
=> tests: Fix use of bash variables in makefile postivie.mk

src/dev/flang/ast/Feature.java
fixes #2103
This `if` is a bit ugly IMHO... Maybe there is a better way?
=> fix #2103, non-disjoint types in choice are reported twice

src/dev/flang/ast/AstErrors.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/jvm/runtime/Runtime.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/Errors.java
Avoids ugly messages of the form "repeated 1 times" and use "repeated once" instead.
=> util: Add convenience methods to create Strings "once", "twice", "3 times", etc.

lib/array2.fz, lib/array3.fz
fixes idiom188ex.fz and possibly others:
error 1: Attempt to modify immutable array
Call stack:
fuzion__sys__2internal_array_i32__2index___coloneq_ 3array2_i32__1INTERN_loop14__1INTERN_loop13
3array2_i32__1INTERN_loop14
3array2_i32
ex188
universe
=> lib: array2, array3 initialization yielded attempt to modify immutable array

tests/reg_issue1604_cmp_swap_choice/Makefile, tests/reg_issue1604_cmp_swap_choice/test_issue1604.fz
=> add regression test for issue 1604

lib/array3.fz
=> lib/array3: fix copy-paste mistake

src/dev/flang/be/jvm/JVM.java
When cloning a value instance with value field instances that were not initialized yet, maybe fields for local variables that were never used anyways, these fields need to be checked if they are null before they are cloned.
A similar check existed already for unused fields for unused values in a choice type, so this patch moves this functionality into a helper method.
This fixes the failures when running flang.dev's tests
-  content/design/examples/monadiclifting_hello3.fz
-  content/design/examples/monadiclifting_hello4.fz
-  content/design/examples/monadiclifting_hello5.fz
-  content/design/examples/monadiclifting_helloabort.fz
=> jvm: uninitialized value fields in a product type may be null

src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java
=> fix contract failure when inheriting from operator

lib/array.fz, lib/fuzion/sys.fz, lib/fuzion/sys/err.fz, lib/fuzion/sys/internal_array.fz, lib/fuzion/sys/out.fz, lib/fuzion/sys/stdin.fz, src/dev/flang/ast/InlineArray.java, src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/util/FuzionConstants.java, src/dev/flang/util/SourceFile.java, src/dev/flang/util/SourcePosition.java
=> change visibility of `fuzion.sys` to module

tests/doubledeclaration_negative/doubledeclaration2.fz, tests/doubledeclaration_negative/doubledeclaration_negative.fz
I realized this test is not as intended anymore when working on #2156
=> test double decl., add visibilities

src/dev/flang/be/jvm/Names.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/runtime/FuzionThread.java, src/dev/flang/be/jvm/runtime/Main.java, src/dev/flang/be/jvm/runtime/Runtime.java, tests/contracts_negative/SquareRoot.fz.expected_err_jvm, tests/reg_issue270/issue270.fz.expected_err_jvm
This avoids the need for special handling of the main thread when accessing thread local data.
=> jvm: Run all Fuzion code within the context of a FuzionThread

src/dev/flang/be/c/C.java
also access CLAZZ_ID in a static way.
=> remove unused code,

src/dev/flang/tools/Fuzion.java, tests/check_simple_example_int.sh, tests/negative.mk, tests/positive.mk, tests/record_simple_example_int.sh, tests/simple.mk, tests/simple_inp.mk, tests/sockets/Makefile, tests/visibility_modules/Makefile, tests/visibility_modules_negative/Makefile
#231 in repo flang.dev needs to be merged first.
=> make jvm-backend the default backend.

lib/codepoint.fz, lib/container/ctrie.fz, lib/f64.fz, lib/num/fraction.fz, lib/num/sign.fz, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/fe/SourceModule.java, tests/atomic/test_atomic.fz, tests/equals/test_equals.fz, tests/reg_issue293_confusion_of_type_and_value_params/issue293.fz, tests/type_feature/test_type_feature.fz, tests/visibility_modules_negative/main.fz, tests/visibility_modules_negative/main.fz.expected_err
=> fe: check visibility of redefining features

src/dev/flang/ast/Call.java, tests/reg_issue2249/Makefile, tests/reg_issue2249/issue2249.fz, tests/reg_issue2249/issue2249.fz.expected_out
=> improve inference for anonymous features

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Call.java, tests/reg_issue2114/Makefile, tests/reg_issue2114/issue_2114.fz, tests/reg_issue2213/Makefile, tests/reg_issue2213/issue_2213.fz
=> fe: fix require condition failure in `calledFeature`

src/dev/flang/ast/Match.java, tests/reg_issue2252/Makefile, tests/reg_issue2252/issue_2252.fz, tests/reg_issue2252/issue_2252.fz.expected_err
=> fix require-condition while resolving type of match subject

src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java, tests/reg_issue2237/Makefile, tests/reg_issue2237/issue_2237.fz, tests/reg_issue2237/mod/mod.fz
=> look for declared features in modules source module depends on

src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Cond.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/If.java, src/dev/flang/ast/InlineArray.java, tests/reg_issue1838/Makefile, tests/reg_issue1838/test_issue1838.fz, tests/reg_issue1838/test_issue1838.fz.expected_err
=> fe: add error message if contracts expression does not result in bool

lib/codepoint.fz
These were useful in this year`s Advent of Code puzzle from 1 Dec.
=> lib: make ranges in `codepoint.type` public, fix #2285

lib/list.fz
=> change impl of `list.as_string sep` as suggested by Max

tests/reg_issue2034/Makefile, tests/reg_issue2034/issue2034.fz, tests/reg_issue2034/issue2034.fz.expected_err
=> add reg test #2034

src/dev/flang/ast/Call.java, src/dev/flang/be/c/C.java, tests/reg_issue1490/Makefile, tests/reg_issue1490/issue1490.fz, tests/reg_issue1490/issue1490.fz.expected_err
=> fix precondition failure when result type is an error

tests/reg_issue1109/Makefile, tests/reg_issue1109/src/a.fz
=> add reg test issue #1109

src/dev/flang/util/ANY.java
Used this to check performence of Fuzion using Advent-Of-Code examples.  An important was missing.
=> util: Fixed commented-out code for allocation statistics

src/dev/flang/ast/Function.java
I do not have the test code any longer...
=> ast: I ran into this check failing after previous errors

src/dev/flang/be/jvm/JVM.java
These are Java classes not Fuzion clazzes.
=> jvm: For the `-classes` backend, now use directory `fuzion_generated_classes`

lib/Sequence.fz, lib/Stream.fz, lib/String.fz, lib/array.fz, lib/array2.fz, lib/container/Map.fz, lib/container/float_sequence.fz, lib/container/hash_map.fz, lib/container/map_of.fz, lib/container/mutable_tree_map/Entry.fz, lib/container/numeric_sequence.fz, lib/container/ordered_map.fz, lib/container/searchable_sequence.fz, lib/has_interval.fz, lib/io/buffered/reader.fz, lib/list.fz, lib/mutate.fz, lib/option.fz, lib/uint.fz, modules/lock_free/src/lock_free/map.fz, modules/lock_free/src/lock_free/stack.fz, tests/choice/choicetest.fz, tests/ctrie_threads/ctrie_threads.fz, tests/lock_free_stack/test.fz, tests/partial_application_negative/partial_application_negative.fz.expected_err, tests/reg_issue1918/test_issue1918.fz, tests/reg_issue238_array_index_out_of_bounds/issue238.fz, tests/typeinference_for_formal_args/typeinference_for_formal_args.fz
=> lib: rename `map`, `flat_map`

lib/has_interval.fz
This helped simplifying the code of AoC solution for day 16.
=> AoC PR: lib: make `upper` in `has_interval.infix ..` public.

src/dev/flang/air/Clazz.java, src/dev/flang/ast/AbstractType.java, tests/reg_issue1391/Makefile, tests/reg_issue1391/reg_issue1391.fz, tests/reg_issue1628/Makefile, tests/reg_issue1628/reg_issue1628.fz
=> me: fix `findOuter` in case of feature is ThisRef

src/dev/flang/ast/NumLiteral.java, tests/reg_issue2358/Makefile, tests/reg_issue2358/reg_issue2358.fz
=> fix inference when wrapping numliteral in lazy

Makefile, bin/add_simple_test.fz, lib/String.fz, lib/io/file.fz
Using `make add_simple_test` will create a new template test in tests.
=> add utility `add_simple_test`

Makefile
=> Makefile: fix `run_tests_jar` target

Makefile, doc/ref_manual/fuzion_reference_manual.adoc
Not much real content for the reference manual yet, but the infrastructure using asciidoc seams to be ok.
=> doc: Add infrastructure for reference manual creation

src/dev/flang/ast/AstErrors.java, src/dev/flang/parser/Parser.java, src/dev/flang/tools/fzjava/ForClass.java, tests/constructor_with_return_type/Makefile, tests/constructor_with_return_type/constructor_with_return_type.fz, tests/constructor_with_return_type/constructor_with_return_type.fz.expected_err
=> parser: error on constructor with return type

Makefile, doc/ref_manual/fuzion_reference_manual.adoc
Also fixed a bug in the Makefile, $(BUILD_DIR)/doc/jvm.html does not exist.
=> ref manual: Work on the glossary

CODE_OF_CONDUCT.md, CONTRIBUTING.md, CONTRIBUTOR_LICENSE_AGREEMENT.md
First version of contributor license agreement, contributing and code of conduct.
=> Contributor agreement

CONTRIBUTOR_LICENSE_AGREEMENT.md
Also fixed a small typo: `Unported`.
=> license: Added links to Contributor License Agreement Chooser and  CCSA

tests/lazy/ex_lazy.fz, tests/lazy/ex_lazy.fz.expected_out
=> eval stars to avoid confusion

lib/String.fz, lib/codepoint.fz
=> lib: add `String.is_ascii`

src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/classfile/ClassFile.java, src/dev/flang/be/jvm/classfile/ClassFileConstants.java, src/dev/flang/be/jvm/classfile/Expr.java, src/dev/flang/be/jvm/classfile/Label.java, src/dev/flang/be/jvm/classfile/StackMapFullFrame.java, src/dev/flang/be/jvm/classfile/VerificationType.java
=> add support for stackmap table attribute.

.github/PULL_REQUEST_TEMPLATE.md
This make sure we do not accidentally leave this text in a PR.
=> github: comment out instructions in the PR template

bin/windows_install_boehm_gc.sh, src/dev/flang/be/c/C.java
=> be/c: fix windows tests

.github/workflows/windows.yml, .github/workflows/windows_c.yml
=> windows: fix emoji output in test javaBase

.github/workflows/windows.yml, .github/workflows/windows_c.yml
my text editor highlights this the wrong way...
=> yaml: fix indentation

src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/JVM.java, tests/reg_issue2478/Makefile, tests/reg_issue2478/reg_issue2478.fz
=> be/jvm: fix init of const void-like array

lib/interval.fz, lib/option.fz
=> fix merge incongruence

src/dev/flang/be/c/C.java, src/dev/flang/be/c/CExpr.java, src/dev/flang/fuir/FUIR.java
=> be/c: `CExpr.this.` must be `super.`

bin/aspell.dict, lib/array.fz
=> correct spelling

src/dev/flang/be/interpreter/DynamicBinding.java, tests/compile_time_constants/compile_time_constants.fz, tests/compile_time_constants/compile_time_constants.fz.expected_out, tests/rosettacode_factors_of_an_integer/factors.fz, tests/sockets/sockets_test_server.fz
=> tests: remove some old NYI

src/dev/flang/ast/AbstractFeature.java
=> fe: remove string comparison in `isTypeFeature`

lib/universe.fz, src/dev/flang/tools/docs/Util.java
=> lib: add file universe, describing universe and how it may be used

src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/Html.java, src/dev/flang/tools/docs/Util.java
=> docs: add type features

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/Loop.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/parser/Parser.java
=> fe: attempt to improve readability of code of `Impl`

.github/workflows/release.yml
=> action: set-output will be deprecated

src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, tests/reg_issue2687/Makefile, tests/reg_issue2687/reg_issue2687.fz, tests/reg_issue2687/skip_int
=> fe: fix type feature created before inheritance resolved

src/dev/flang/util/SourcePosition.java
=> util: SourceRange, fix showInSource if start=end

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/FUIR.java
Somewhat nicer than the manual comparison or ordinals.
=> jvm/C/fuir: Add FUIR.LifeTime.maySurviveCall() convenience method

Makefile, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/util/Version.java.in
Produce a better error message.
=> util/C: Add Java version to Version.java, use it in C backend intrinsics

tests/javaBase/Makefile
I did not test this.
[ci skip]
=> macOS: try fix finding libjvm.dylib

src/dev/flang/be/jvm/JVM.java
the special case:
the result field does not exist, the java return type is void and fuzions type is also void.
fixes #2744
=> be/jvm: fix `epilog` code gen for special case

src/dev/flang/util/Map2Int.java
The original comment was wrong and confused me.
=> util: Fix comment of Map2Int

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Feature.java, src/dev/flang/fe/LibraryFeature.java
=> spelling: four -> for

src/dev/flang/ast/AstErrors.java, tests/reg_issue2775/Makefile, tests/reg_issue2775/reg_issue2775.fz, tests/reg_issue2775/reg_issue2775.fz.expected_err
=> ast: fix require-condition2 calling `asRef` on void type

include/shared.c
=> be/c: add getJNIEnv() to enable per-thread jni-env

README.md
=> readme: add macos section

src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fuir/analysis/dfa/Env.java, src/dev/flang/fuir/analysis/dfa/NumericValue.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/tools/docs/Util.java
found most of these by using: https://pmd.github.io/
=> various code cleanups

tests/reg_issue2321/Makefile, tests/reg_issue2321/reg_issue2321.fz, tests/reg_issue2321/reg_issue2321.fz.expected_err
=> add regression test for issue #2321

lib/composition.fz
=> lib: cosmetics: fix typo in comment

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, tests/reg_issue2878/Makefile, tests/reg_issue2878/reg_issue2878.fz, tests/reg_issue2878/reg_issue2878.fz.expected_err
=> ast: show warning if -> is used in operator

src/module-info.java
=> module-info: remove  "NYI remove this dependency?" comment

src/dev/flang/fuir/analysis/AbstractInterpreter.java
I don't think this NYI-comment is still up to date?
=> fuir: remove old NYI comment

lib/Any.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java
=> lib: remove intrinsic Any.as_string

src/dev/flang/ast/Function.java
=> ast/Function: improve comments

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/UnresolvedType.java
- grouped abstract features
- reduced visibility where applicable
- renamed generic->asGeneric, genericType->asGenericType
=> ast: cleanups in abstract features

README.md
=> readme: add section for installing fuzion from package manger

lib/choice.fz
=> lib: choice remove orphaned comment

lib/fuzion/java.fz
It does not seem necessary anymore
=> lib: remove feature fuzion.java.Java_Object._ignore_

tests/reg_issue2346/Makefile, tests/reg_issue2346/reg_issue2346.fz
=> add test #2346

src/dev/flang/be/interpreter/Interpreter.java
In my tests this brings roughly +25% in performance in longer running tests.
=> be/interpreter: getField performance

src/dev/flang/util/Map2Int.java
=> util: fix a comment

include/shared.c, lib/fuzion/java.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/tools/fzjava/ForClass.java, tests/javaBase/javaHello.fz
currently only c-backend evalutes this
=> be: java intrinsics, add parameter: signature

src/dev/flang/ast/Loop.java
=> ast/Loop: fix visi_loop example

src/dev/flang/air/Clazz.java, src/dev/flang/be/c/CTypes.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/FUIR.java, tests/reg_issue2224/Makefile, tests/reg_issue2224/reg_issue2224.fz
=> issue/2224: precondition of abstract features

lib/container/Persistent_Map.fz
We currently have Map (which is immutable) and Mutable_Map. Persistent_Map is kind of in between those two. It should allow efficient adding of elements while keeping the immutable property of Map.
=> lib: add container.Persistent_Map

src/dev/flang/ast/Call.java, tests/reg_issue3007/Makefile, tests/reg_issue3007/reg_issue3007.fz
=> ast: type inference for arguments for feature with generics

tests/argumentcount_negative/argumentcount_negative.fz, tests/assignment_negative/illegal_assignment.fz, tests/generics_negative/generics_negative.fz, tests/this_type_negative/test_this_type_negative.fz
=> tests: a few `is` by `=>` replacements

lib/Sequence.fz
=> lib: remove as_stream in comment

lib/fuzion/java.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/classfile/ClassFileConstants.java, src/dev/flang/tools/fzjava/FZJava.java, src/dev/flang/tools/fzjava/ForClass.java, tests/javaBase/javaHello.fz, tests/javaBase/javaHello.fz.expected_err, tests/javaBase/javaHello.fz.expected_out, tests/reg_issue2740/Makefile, tests/reg_issue2740/reg_issue2740.fz
for sequences of none-primitives the following helper was added:
```
public Java.as_java_object(T type : Java.java.lang.Object, seq Sequence T) =>
res := (Java.java.lang.reflect.Array.newInstance T.get_java_class seq.count).val
for idx := 0, idx+1
el in seq
do
Java.java.lang.reflect.Array.__k__set res idx el
fuzion.java.Array T res.Java_Ref
```
This is used by fzjava to allow passing Sequences of Java_Objects.
=> java intrinsics: fix creation and access of java arrays of none-primitive values

tests/reg_issue2380/Makefile, tests/reg_issue2380/reg_issue2380.fz
=> add regression test issue #2380

src/dev/flang/util/SourceFile.java, tests/reg_issue3015/Makefile, tests/reg_issue3015/reg_issue3015.fz, tests/reg_issue3015/reg_issue3015.fz.expected_err
=> util: determine codepoint width for calculating indentation

tests/reg_issue624/Makefile, tests/reg_issue624/reg_issue624.fz
=> add regression test #624

tests/reg_issue1491/Makefile, tests/reg_issue1491/reg_issue1491.fz
=> tests: add regression test #1491

src/dev/flang/ast/Expr.java, tests/nested_lazy/ex_nested_lazy.fz.expected_err, tests/reg_issue2275/Makefile, tests/reg_issue2275/reg_issue2275.fz, tests/reg_issue2275/reg_issue2275.fz.expected_err
=> ast: assignment, apply boxing only if type assignable

lib/Sequence.fz
=> lib: fix typo

tests/javaBase/Makefile
=> tests: set LANGUAGE to en_US

tests/tuple_negative/tuple_negative.fz
=> test: fix syntax error, expected `is` or `=>`

src/dev/flang/ast/Call.java, src/dev/flang/ast/Types.java, src/dev/flang/ast/Universe.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/parser/Parser.java, tests/reg_issue2682/Makefile, tests/reg_issue2682/reg_issue2682.fz, tests/reg_issue2682/reg_issue2682.fz.expected_out
=> parser/ast: use `universe` in type qualifier

src/dev/flang/air/Clazz.java, src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/AbstractCurrent.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Case.java, src/dev/flang/ast/FeatureName.java, src/dev/flang/ast/Generic.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/fe/LibraryCall.java, src/dev/flang/tools/docs/Html.java, tests/free_types_negative/test_free_types_negative.fz.expected_err, tests/nested_lazy/ex_nested_lazy.fz.expected_err, tests/reg_issue1559_post_condition/test_issue1559.fz.expected_err, tests/reg_issue1771/Makefile, tests/reg_issue1771/reg_issue1771.fz, tests/reg_issue1771/reg_issue1771.fz.expected_err, tests/reg_issue776/reg_issue776.fz.expected_err, tests/reg_issue8_optionFalse/bugOptionFalse.fz.expected_err
=> fe: fix cryptic feature names in err output

lib/property/hashable.fz, lib/property/orderable.fz, lib/property/partially_orderable.fz, src/dev/flang/ast/AbstractCurrent.java
=> lib: change inheritance of properties

tests/reg_issue1698/Makefile, tests/reg_issue1698/reg_issue1698.fz, tests/reg_issue1698/reg_issue1698.fz.expected_err, tests/reg_issue1698/reg_issue1698.fz.expected_err_c, tests/reg_issue1698/reg_issue1698.fz.expected_err_jvm
=> add reg test #1698

lib/process/spawn.fz, tests/process/test_process.fz
These install buffered readers that can then be used for reading stdout/stderr of process.
=> lib: process, add `with_out/`with_err`

src/dev/flang/tools/docs/Html.java
=> docs: fix use `=>` vs `is`

.github/workflows/apple.yml
seems like the path was changed...
[ci skip]
=> action: macos fix path of sed/make

include/shared.c
With previous PR and this, I now get a response from the webserver.
=> be/c: fix switch-expr in fzE_call_v0/fzE_call_s0

tests/atomic/Makefile
this is a workaround for windows where test atomic fails currently
=> tests/atomic: increase stack size

src/dev/flang/ast/AstErrors.java, tests/reg_issue3102/Makefile, tests/reg_issue3102/reg_issue3102.fz, tests/reg_issue3102/reg_issue3102.fz.expected_err
also add regression test for #3102
fixes #3102
=> ast: change error message when defining _choice routine_

tests/compile.mk, tests/concur_simple/Makefile, tests/reg_issue2380/Makefile, tests/reg_issue2381/Makefile
we can go one step further and compile the code for jvm and c backend.
=> tests: change dfa.mk to compile.mk

src/dev/flang/ast/Block.java, tests/reg_issue3233/Makefile, tests/reg_issue3233/reg_issue3233.fz
logic was slightly too strict, change from
`r.resultType().compareTo(Types.resolved.t_unit) != 0` to
`!r.resultType().isAssignableFrom(Types.resolved.t_unit)`
fixes #3233
=> ast: fix unjustified "Block must end with a result expression"

tests/reg_issue2860/Makefile, tests/reg_issue2860/reg_issue2860.fz, tests/reg_issue2860/reg_issue2860.fz.expected_err
=> tests: add regression test #2860

Makefile, tests/fz_cmd/Makefile, tests/fz_cmd/skip_jvm
=> tests: remove skip file from test fz_cmd

.github/workflows/apple.yml, .github/workflows/linux.yml
macOS runs in less than 40 min.
the linux machines need about an hour.
(windows ~70min.)
=> actions: change PR test runner from linux to macOS

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/fe/LibraryFeature.java
=> ast: update some comments

lib/Lazy.fz
=> lib: add comment on `Lazy`

lib/id.fz, src/dev/flang/ast/Call.java, src/dev/flang/ast/Contract.java, src/dev/flang/ast/Impl.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/util/Errors.java
=> spelling fixes

bin/run_tests.sh, bin/run_tests_parallel.sh
Reason why linux tests do not run. I missed those in the previous PR.
=> scripts: fix more shellcheck issues

lib/io/buffered/reader.fz, lib/io/stdin.fz, lib/net/client.fz, lib/net/server.fz, lib/process/spawn.fz, tests/process/test_process.fz, tests/process_buffered_writer/test_process.fz, tests/reg_issue2280/reg_issue2280.fz, tests/reg_issue2380/reg_issue2380.fz, tests/reg_issue2381/reg_issue2381.fz, tests/sockets/sockets_test.fz, tests/stdin/stdintest.fz
Installing the effect inside the reader was a hack.
=> lib/io/buffered/reader: pass mutate effect as argument

tests/fallible/test_fallible.fz, tests/fallible/test_fallible.fz.expected_out
=> spelling: expetcing -> expecting

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, src/dev/flang/fe/SourceModule.java, tests/inherit_postcondition/inherit_postcondition.fz, tests/inherit_postcondition/module_src/mod.fz, tests/reg_issue3108/Makefile, tests/reg_issue3108/reg_issue3108.fz, tests/reg_issue3108/reg_issue3108.fz.expected_err
=> ast: raise error on redefining field

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/FeatureName.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/runtime/Runtime.java, src/dev/flang/fe/FeErrors.java, src/dev/flang/parser/Lexer.java, src/dev/flang/parser/Parser.java, src/dev/flang/util/Errors.java, src/dev/flang/util/StringHelpers.java, tests/reg_issue627/reg_issue627.fz.expected_err
=> util: move non Error specific helper methods to StringHelper

src/dev/flang/tools/docs/Html.java
=> docs: use `cursor:pointer` on complete `<details>` element.

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/DotType.java, src/dev/flang/ast/Env.java, src/dev/flang/parser/Parser.java, tests/reg_issue3151/Makefile, tests/reg_issue3151/reg_issue3151.fz, tests/reg_issue3151/reg_issue3151.fz.expected_err
=> parser: show error on wrong target for env/type expressions

src/dev/flang/util/ANY.java
When this code is activated (by uncommenting it), you can now do, e.g.,
> ./build/bin/fz tests/hello/HelloWorld.fz | tail
ALLOCS: 27387	: class dev.flang.fuir.analysis.dfa.DFA$Analyze
ALLOCS: 27388	: class dev.flang.fuir.analysis.AbstractInterpreter
ALLOCS: 29082	: class dev.flang.fuir.analysis.dfa.ValueSet
ALLOCS: 31003	: class dev.flang.fe.NormalType
ALLOCS: 81557	: class dev.flang.fuir.analysis.dfa.Call
ALLOCS: 87057	: class dev.flang.fuir.analysis.dfa.Instance
ALLOCS: 127913	: class dev.flang.ast.ResolvedNormalType
ALLOCS: 206002	: class dev.flang.fuir.analysis.dfa.EmbeddedValue
ALLOCS: 262034	: class dev.flang.air.FeatureAndActuals
ALLOCS: 336198	: class dev.flang.fuir.analysis.dfa.Site
>
=> util: sort allocation statistics output

src/dev/flang/util/SourcePosition.java
some cleanup, it seems that an `if` instead of the `while` is sufficient
=> util: cleanup `showInSource()` in `SourcePosition`

lib/f32.fz, lib/f64.fz, lib/float.fz, tests/floating_point_numbers/floating_point_numbers.fz
=> fix spelling: comparison

doc/ref_manual/fuzion_reference_manual.adoc
=> doc: Add definition of braces, brackets and parentheses to ref manual.

lib/Sequence.fz, lib/String.fz, lib/concur/atomic.fz, lib/container/Circular_Buffer.fz, lib/container/Set.fz, lib/exit.fz, lib/float.fz, lib/fuzion/sys/args.fz, lib/fuzion/sys/internal_array.fz, lib/handles.fz, lib/handles2.fz, lib/i16.fz, lib/i32.fz, lib/i64.fz, lib/i8.fz, lib/int.fz, lib/integer.fz, lib/io/Read_Provider.fz, lib/io/buffered/reader.fz, lib/io/file/open.fz, lib/num/ryu.fz, lib/process/spawn.fz, lib/random.fz, lib/time/date_time.fz, lib/u128.fz, lib/u64.fz, lib/uint.fz
unsure about some of them, e.g.
* int.fz as_uXX
* integer.fz prefix ~
* ...
resolve #3410
=> lib: add qualifiers to pre- and postconditions

src/dev/flang/air/AirErrors.java, src/dev/flang/air/Clazz.java, src/dev/flang/air/Clazzes.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/me/MiddleEnd.java
=> air: make fields in Clazzes non static

src/dev/flang/util/SourceFile.java, tests/reg_issue3506_a/Makefile, tests/reg_issue3506_a/reg_issue3506_a.fz, tests/reg_issue3506_a/reg_issue3506_a.fz.expected_err, tests/reg_issue3506_b/Makefile, tests/reg_issue3506_b/reg_issue3506_b.fz, tests/reg_issue3506_b/reg_issue3506_b.fz.expected_err
=> util: fix cut-off code in error message

tests/reg_issue1518/Makefile, tests/reg_issue1518/reg_issue1518.fz, tests/reg_issue1518/reg_issue1518.fz.expected_err
=> tests: add regression test for #1518

src/dev/flang/util/SourcePosition.java
=> util: fix error position at line end not underlined with ansi enabled

src/dev/flang/ast/Function.java, tests/reg_issue3576/Makefile, tests/reg_issue3576/reg_issue3576.fz, tests/reg_issue3576/reg_issue3576.fz.expected_err
=> ast: fix null pointer exception in Function.java

.github/workflows/apple.yml, .github/workflows/linux.yml, Makefile, bin/ebnf.fz
=> action: always generate docs

.github/workflows/linux.yml
=> action: linux, add missing package `ruby-asciidoctor-pdf`

lib/Sequence.fz, lib/String.fz, lib/container/ordered_map.fz, lib/container/searchable_sequence.fz, lib/container/sorted_array.fz, modules/lock_free/src/lock_free/map.fz, tests/compile_time_type_casts/compile_time_type_casts.fz, tests/lib_container_sorted_array/lib_container_sorted_array.fz
Sequence.fz
* `is_prefix_of` -> `starts_with`
* `find_first` -> `find`
* `replace_all` -> `replace`
* `replace_n` -> `replace`
* `split_` -> `split0`
=> lib: resolve NYIs from #3524 by renameing features as specified

src/dev/flang/be/c/Intrinsics.java
There were two problems that are fixed by this:
- the assignment `e.assign(ev)` with a long NYI-comment was completely useless since it assigns a value to a local var just before this function returns. Apparantly, I was confused when I originally wrote this code.
- for event values of unit type, useless assignment of empty struct values were generated.
This fixed the C backend failures of jenkins/flang_dev tests fosdem23_aijd_01_max_exc.fz, fosdem24_draw2.fz, fosdem24_draw1.fz.
=> C: fix code for `effect.type.instate0` intrinsic for unit type effect

tests/check_simple_example_c.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
=> tests: limit stack size and cpu time for executing test

lib/internationalization/provide.fz
allows to internationalize by default, e.g based on location
=> lib: add default effect for internationalization

src/dev/flang/air/Clazz.java, src/dev/flang/ast/Tag.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, tests/reg_issue1638/Makefile, tests/reg_issue1638/reg_issue1638.fz, tests/reg_issue1638/reg_issue1638.fz.expected_out
=> fuir: tagged values, use same tag numbers as frontend

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/fe/SourceModule.java, tests/redef_with_type_parameters/redef_test.fz, tests/redef_with_type_parameters/redef_test.fz.expected_out, tests/reg_issue1932/Makefile, tests/reg_issue1932/reg_issue1932.fz, tests/reg_issue1932/reg_issue1932.fz.expected_err
=> fe: show error on choice constraint

lib/eff/fallible.fz, tests/catch_postcondition/catch_postcondition.fz.expected_err
=> lib/fallible: cleanup NYI which are now working

src/dev/flang/air/Clazz.java, src/dev/flang/tools/CheckIntrinsics.java, tests/reg_issue3199/Makefile, tests/reg_issue3199/reg_issue3199.fz, tests/reg_issue3199/reg_issue3199.fz.expected_err
i.e. mark their results as instantiated
=> air: treat all intrinsics as intrinsic constructors

src/dev/flang/be/c/CNames.java, tests/reg_issue1840/skip_c
=> be/c: fix name clash

src/dev/flang/air/Clazz.java, tests/reg_issue3507/Makefile, tests/reg_issue3507/reg_issue3507.fz, tests/reg_issue3507/reg_issue3507.fz.expected_err
fixes #3507
typeClazz must not be created if type is generic argument
=> air: fix require condition

tests/reg_issue3352/Makefile, tests/reg_issue3352/reg_issue3352.fz, tests/reg_issue3352/reg_issue3352.fz.expected_err_c, tests/reg_issue3352/reg_issue3352.fz.expected_err_int, tests/reg_issue3352/reg_issue3352.fz.expected_err_jvm
does not fix the underlying issue, but the test works now due to recent changes to effects
=> tests: add regression test for #3352

lib/try.fz
=> lib: spelling fixes in `try`

src/dev/flang/air/Clazzes.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/analysis/dfa/Env.java, src/dev/flang/util/FuzionOptions.java
=> fix spelling

src/dev/flang/util/SourcePosition.java, tests/reg_issue3683/Makefile, tests/reg_issue3683/reg_issue3683.fz, tests/reg_issue3683/reg_issue3683.fz.expected_err
=> util: fix crash of non ascii-7-codepoint

tests/negative.mk
Clearly display the result (pass/fail) of negative tests.
=> tests: improve negative tests to clearly display result

src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/Html.java
=> docs: annotate features which are or contain abstract features

tests/reg_issue2340/Makefile, tests/reg_issue2340/reg_issue2340.fz
=> tests: add regression test #2340

src/dev/flang/tools/docs/Html.java, src/dev/flang/tools/docs/Util.java
fix #3637
some issues remain, see #3716
=> docs: show features inherited from `Type` as type features

tests/negative.mk
=> makefile: replace echo by printf for better compatibility

tests/reg_issue3369/child.fz
=> tests: remove confusing NYI

src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/CodeGen.java
TCO is done regardless of lifetime now.
=> be/jvm: remove unused debug code

src/dev/flang/ast/Resolution.java, tests/reg_issue3648/Makefile, tests/reg_issue3648/reg_issue3648.fz, tests/reg_issue3648/reg_issue3648.fz.expected_err
=> ast: Resolution.resolveTypes, relax post condition

src/dev/flang/ast/AstErrors.java, src/dev/flang/fe/SourceModule.java, tests/reg_issue3693/Makefile, tests/reg_issue3693/reg_issue3693.fz, tests/reg_issue3693/reg_issue3693.fz.expected_err
=> fe: flag error on illegal `.this` type

src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java
This is preparatory work to be able to compile SourceModule to fum file load it as LibraryModule and then compile based on this.
=> fe: createMIR from library module

tests/calls_on_ref_and_val_target_negative/Makefile, tests/calls_on_ref_and_val_target_negative/calls.fz, tests/calls_on_ref_and_val_target_negative/calls.fz.expected_err
=> tests: fix `calls_on_ref_and_val_target_negative` and change to simple_and_negative

tests/reg_issue3730_1/Makefile, tests/reg_issue3730_1/reg_issue3730_1.fz, tests/reg_issue3730_2/Makefile, tests/reg_issue3730_2/reg_issue3730_2.fz, tests/reg_issue3730_2/reg_issue3730_2.fz.expected_out
=> tests: add reg tests for #3730

src/dev/flang/fuir/analysis/AbstractInterpreter.java
=> ai: add check to access of env, site should not always result in void

tests/choice_negative2/Makefile, tests/choice_negative2/choice_negative.fz.expected_err, tests/doubledeclaration_negative/Makefile, tests/doubledeclaration_negative/doubledeclaration_negative.fz.expected_err, tests/generics_negative/Makefile, tests/generics_negative/generics_negative.fz, tests/generics_negative/generics_negative.fz.expected_err, tests/loop_negative/Makefile, tests/loop_negative/looptest_negative.fz, tests/loop_negative/looptest_negative.fz.expected_err, tests/nested_choice_negative/Makefile, tests/nested_choice_negative/nested_choice_negative.fz.expected_err, tests/tuple_negative/Makefile, tests/tuple_negative/tuple_negative.fz.expected_err
part of #3714
fix broken tests
=> tests: replace negative tests with simple_and_negative tests (batch 3)

src/dev/flang/ast/Feature.java, tests/reg_issue3749/Makefile, tests/reg_issue3749/reg_issue3749.fz, tests/reg_issue3749/reg_issue3749.fz.expected_err
=> ast: avoid duplicate error with source position 'built-in'

src/dev/flang/be/jvm/Intrinsix.java
=> be/jvm: fix verify error #3778

.github/workflows/apple.yml, .github/workflows/apple_c.yml, .github/workflows/apple_int.yml, .github/workflows/apple_jvm.yml, bin/run_tests.sh, bin/run_tests_parallel.sh
=> tests: kill after 600s

src/dev/flang/fe/LibraryModule.java, src/dev/flang/fuir/AirFUIR.java, src/dev/flang/fuir/FUIR.java
=> remove unused imports

src/dev/flang/tools/fzjava/ForClass.java
previous PR failed because of this...
=> fzjava: improve determinism of short-hands

tests/reg_issue2274/Makefile, tests/reg_issue2274/reg_issue2274.fz
=> tests: add reg test #2274

src/dev/flang/ast/Call.java, tests/reg_issue2378/Makefile, tests/reg_issue2378/reg_issue2378.fz, tests/reg_issue2378/reg_issue2378.fz.expected_err
=> ast: raise error on selecting sth on open generic

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Call.java, tests/reg_issue2647/Makefile, tests/reg_issue2647/reg_issue2647.fz, tests/reg_issue2647/reg_issue2647.fz.expected_err
=> ast: show error when trying to call open type parameter

lib/outcome.fz, lib/switch.fz
=> lib: switch, add as_outcome, as_option

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/ResolvedNormalType.java, tests/reg_issue2307/Makefile, tests/reg_issue2307/reg_issue2307.fz, tests/reg_issue2307/reg_issue2307.fz.expected_err
=> ast: fix require condition for `void` constraint

bin/aspell.dict, src/dev/flang/be/c/CTypes.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/GeneratingFUIR.java
=> fuir: remove clazz_fuzionJavaObject from clazzNeedsCode

lib/switch.fz
=> remove workaround, #3355

tests/reg_issue3905/Makefile, tests/reg_issue3905/reg_issue3905.fz
=> tests: add reg tests #3905

src/dev/flang/fuir/GeneratingFUIR.java
This function requires about 15% of the execution time of interpreted tests/basicIntegers/basicIntegers.fz, so caching helps signficantly here.
Not sure if this is the issue causing the slowdown reported in #3990.
=> fuir: cache result of boxResultClazz(), improve #3990

tests/reg_issue3769/Makefile, tests/reg_issue3769/reg_issue3769.fz, tests/reg_issue3769/reg_issue3769.fz.expected_err
=> tests: add reg test #3769

tests/reg_issue3160/Makefile, tests/reg_issue3160/reg_issue3160.fz
=> tests: add reg test #3160

src/dev/flang/fuir/GeneratingFUIR.java
This should fix the four remaining jenkins failures.
=> fuir: fix abstract missing not recorded

tests/reg_issue1741/Makefile, tests/reg_issue1741/reg_issue1741.fz, tests/reg_issue1741/reg_issue1741.fz.expected_err
=> tests: add reg test #1741

lib/container/Set.fz, lib/net/connections.fz, tests/ctrie/ctrie_test.fz
=> lib: rename `Set.except` to `Set.difference`

tests/choice_negative/Makefile, tests/choice_negative/choice_negative.fz, tests/choice_negative/choice_negative.fz.expected_err, tests/indentation_negative/Makefile, tests/indentation_negative/indentation_negative.fz, tests/indentation_negative/indentation_negative.fz.expected_err, tests/inheritance_negative2/Makefile, tests/inheritance_negative2/inheritance_negative2.fz, tests/inheritance_negative2/inheritance_negative2.fz.expected_err, tests/visibility_negative/Makefile, tests/visibility_negative/visibility_negative.fz, tests/visibility_negative/visibility_negative.fz.expected_err
=> tests: replace negative tests with simple_and_negative tests (batch 4/4)

include/fz.h, include/shared.c, lib/fuzion/java.fz, src/dev/flang/be/c/C.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/runtime/Runtime.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java
=> be: java intrinsics, support for `set_field`, complement of `get_field`

lib/container/ps_map.fz, lib/mutate/array.fz, src/dev/flang/parser/Parser.java, tests/floating_point_numbers/floating_point_numbers.fz, tests/generics/genericstest.fz, tests/if_negative/iftest_negative.fz, tests/loop/looptest.fz, tests/redef_args/redef_args.fz, tests/reg_issue1158_type_of_type_parameters/test_type_of.fz, tests/reg_issue2691_a/Makefile, tests/reg_issue2691_a/reg_issue2691_a.fz, tests/reg_issue2691_a/reg_issue2691_a.fz.expected_out, tests/reg_issue2691_b/Makefile, tests/reg_issue2691_b/reg_issue2691_b.fz, tests/reg_issue2691_b/reg_issue2691_b.fz.expected_err, tests/reg_issue2691_c/Makefile, tests/reg_issue2691_c/reg_issue2691_c.fz, tests/reg_issue2691_c/reg_issue2691_c.fz.expected_err, tests/strings/stringstest.fz, tests/typeinference/typeinference.fz, tests/unicode/unicodetest.fz
setMinIndent for `if` that are not part of an `else if`, treat `elseBlock`s of loops and ifs differently
fix #2691
=> parser: fix outer `else` falsely matched with inner `if`

tests/reg_issue1666/Makefile, tests/reg_issue1666/reg_issue1666.fz, tests/reg_issue1666/reg_issue1666.fz.expected_err
=> tests: add reg test #1666

src/dev/flang/fuir/analysis/AbstractInterpreter.java
Added new Option to print debug output after processing of each command.
Removed early returns in main processing method.
=> fuir: cleanup and better debugging in abstract interpreter

lib/concur/thread_pool.fz, lib/container/hash_map.fz, lib/effect.fz, lib/handles.fz, lib/handles2.fz, lib/io/buffered/reader.fz, lib/io/dir/use.fz, lib/io/file.fz, lib/io/file/use.fz, lib/net/connection.fz
This PR is meant as a suggestion.
=> lib: add infix version of instate_self

lib/container/ordered_map.fz
=> lib: fix order_map index

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/UnresolvedType.java
=> ast: add method `constraintIfGeneric` for common pattern

lib/auto_unwrap.fz, lib/io/buffered/reader.fz, lib/io/file/open.fz, lib/os/process.fz, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Loop.java, src/dev/flang/parser/Parser.java
=> ast: check effect signatures for existance of types

src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, tests/effect_signature/Makefile, tests/effect_signature/effect_signature_test.fz, tests/effect_signature/effect_signature_test.fz.expected_err
=> ast: flag error if type in effect signature is not an effect

src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java
=> fix flaws in asciidoc

tests/reg_issue37_inhGenericOuter/inheritGenericOuter.fz
=> update syntax of test #37

src/dev/flang/ast/Resolution.java
=> ast: cleanup: put `if (DEBUG) ...` in single line

src/dev/flang/util/SourcePosition.java, tests/reg_issue4180/Makefile, tests/reg_issue4180/reg_issue4180.fz, tests/reg_issue4180/reg_issue4180.fz.expected_err
=> util: fix require condition failure #4180

lib/String.fz, lib/array2.fz, lib/array3.fz, lib/container/Set.fz, tests/reg_issue238_array_index_out_of_bounds/issue238.fz
=> lib: rename String.concat1 as String.concat

README.md, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Resolution.java, src/dev/flang/util/Errors.java
-  change static field fieldUsages to intance field
- move unusedFieldErrCount, reset it
- corrected Readme example
=> ast: cleanups, change static field to instance field etc.

Makefile, src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/be/jvm/classfile/ClassFile.java, src/dev/flang/be/jvm/classfile/Expr.java
=> be/jvm: add invoke static for interface method

lib/monad.fz, src/dev/flang/ast/AbstractType.java, tests/reg_issue1294/issue1294.fz, tests/reg_issue1294/issue1294.fz.expected_out, tests/reg_issue3773/Makefile, tests/reg_issue3773/reg_issue3773.fz, tests/reg_issue3773/reg_issue3773.fz.expected_err
=> ast: apply type pars when checking actual type pars

tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz
=> tests:  mix_inheritance_and_outer, update naming

src/dev/flang/fuir/analysis/dfa/DFA.java
=> dfa: cleanup unused field

Makefile
=> makefile: add NYI comment for Java version hack

.github/workflows/windows.yml, .github/workflows/windows_c.yml, .github/workflows/windows_int.yml, .github/workflows/windows_jvm.yml
=> win: github action, try fix setting env variables

.github/workflows/windows.yml, .github/workflows/windows_c.yml, .github/workflows/windows_int.yml, .github/workflows/windows_jvm.yml
=> win: try fix actions

tests/reg_issue3649/Makefile, tests/reg_issue3649/reg_issue3649.fz, tests/reg_issue3649/reg_issue3649.fz.expected_err
=> tests: add reg test #3649

.github/workflows/windows.yml, .github/workflows/windows_c.yml, .github/workflows/windows_int.yml, .github/workflows/windows_jvm.yml, include/win.c
=> win: fix github action

src/dev/flang/be/interpreter/Executor.java, tests/reg_issue4281/Makefile, tests/reg_issue4281/reg_issue4281.fz, tests/reg_issue4281/reg_issue4281.fz.expected_out
=> be/int: fix set casefield in case result type is unittype

bin/add_simple_test.fz
=> add_simple_test: remove workaround

Makefile
=> fix dependency on boehm-gc

src/dev/flang/ast/AbstractFeature.java
Ran into this during debugging.
=> ast: relax check that `finInheritanceChain` is successful

src/dev/flang/ast/AstErrors.java, src/dev/flang/parser/Parser.java, tests/reg_issue2452_abstract_constructor/Makefile, tests/reg_issue2452_abstract_constructor/reg_issue2452_abstract_constructor.fz, tests/reg_issue2452_abstract_constructor/reg_issue2452_abstract_constructor.fz.expected_err
=> parser: show error for `abstract`, `intrinsic` and `native` constructors

src/dev/flang/ast/AbstractCall.java, tests/choice_negative/choice_negative.fz.expected_err
don't record usage for fields that don't exist
fix  #4342
=> ast: fix error when recording usage of fields

tests/reg_issue1591/Makefile, tests/reg_issue1591/reg_issue1591.fz, tests/reg_issue1591/reg_issue1591.fz.expected_out
=> tests: add reg test #1591

include/fz.h, include/posix.c, include/win.c
In the future this might be a HANDLE in case of windows.
=> be/c: remove FILE from header file

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Call.java, tests/reg_issue4332/Makefile, tests/reg_issue4332/reg_issue4332.fz, tests/reg_issue4332/reg_issue4332.fz.expected_err
=> ast: robustness of setActualResultType in case of errors

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/NumLiteral.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/ast/Partial.java
isFunctionType => isFunctionTypeExcludingLazy
isAnyFunctionType => isFunctionType
=> ast: rename isFunctionType/isAnyFunctionType

src/dev/flang/tools/docs/Html.java
=> docs: add `...` for open types

Makefile, src/dev/flang/be/jvm/JVM.java
fixes #4364
Also added a test to run_tests_jar to execute the generated output and validate result.
=> be/jvm: -jar,-classes fix `UnsupportedClassVersionError`

include/win.c
=> be/c: win.c, replace some posix code by native windows

src/dev/flang/parser/Parser.java, tests/reg_issue4348/Makefile, tests/reg_issue4348/reg_issue4348.fz, tests/reg_issue4348/reg_issue4348.fz.expected_err
=> parser: fix require-condition in setSourceRange

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/SrcModule.java, src/dev/flang/fe/FrontEnd.java, src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/tools/Fuzion.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/fzjava/FZJava.java
=> fe: fix name clash of type features in different modules

src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/docs/Html.java
=> docs: replace all non-ascii in urls and paths

modules/base/src/Sequence.fz, modules/base/src/encodings/base32.fz, modules/base/src/fuzion/sys/net.fz, modules/base/src/list.fz, modules/base/src/net/channel.fz, tests/reg_issue2280/reg_issue2280.fz, tests/reg_issue2304/reg_issue2304.fz.expected_err_int, tests/reg_issue2304/reg_issue2304.fz.expected_err_jvm
=> lib: return Sequence instead of list

Makefile, bin/fz, bin/fzjava
I installed another jdk and λ was suddenly printed as ?. This solves this problem for me.
=> set: -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8

src/dev/flang/fuir/analysis/dfa/Value.java
=> dfa: cleanup, remove unused ADDRESS

tests/reg_issue4220/Makefile, tests/reg_issue4220/reg_issue4220.fz, tests/reg_issue4220/reg_issue4220.fz.expected_out
=> tests: add reg test #4220

modules/base/src/Sequence.fz, src/dev/flang/ast/Context.java, src/dev/flang/ast/Contract.java, src/dev/flang/ast/Feature.java
=> ast: fix type parameter constraints in pre/post features

src/dev/flang/ast/Contract.java
=> ast: fix indentation

modules/base/src/net/ip_address.fz
To be extended with more features in the future…
=> base/net: add `ip_address` feature

src/dev/flang/fe/LibraryOut.java, src/dev/flang/util/DataOut.java
The names confused me a little.
=> naming: enhance naming, writeName->writeString, write->writeBytes

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/Interpreter.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/fuir/cfg/CFG.java
Drop id to make consistent with firstClazz() and lastClazz(). Id does not add valuable info here.
=> naming: mainClazzId -> mainClazz

src/dev/flang/parser/Parser.java
=> parser: fix indent

modules/base/src/Sequence.fz, modules/base/src/list.fz, tests/reg_issue3178/reg_issue3178.fz.expected_err_jvm
=> lib: add Sequence.count_by

tests/reg_issue4426/Makefile, tests/reg_issue4426/reg_issue4426.fz, tests/reg_issue4426/reg_issue4426.fz.expected_err
=> tests: add reg test #4426

modules/base/src/Sequence.fz, modules/base/src/container/Mutable_Linked_List.fz, modules/base/src/list.fz, tests/base16/base16_test.fz, tests/base32/base32_test.fz, tests/base32hex/base32hex_test.fz, tests/base64/base64_test.fz, tests/base64url/base64url_test.fz
=> lib: rename Sequence.concat_sequences -> Sequence.concat

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Impl.java, tests/free_types_negative/test_free_types_negative.fz.expected_err, tests/reg_issue2347/reg_issue2347.fz.expected_err, tests/reg_issue4419/Makefile, tests/reg_issue4419/reg_issue4419.fz, tests/reg_issue4419/reg_issue4419.fz.expected_err, tests/typeinference_for_formal_args_negative/typeinference_for_args_negative.fz.expected_err
fixes #4419
see also #4455 and #4456 for a follow up issues.
=> ast: fix result type once inferred

src/dev/flang/ast/Impl.java
since this confused me when I read this.
[ci skip]
=> ast: typeInferable, add comment

modules/base/src/container/Mutable_Map.fz
=> lib: add `set []` to `Mutable_Map` as alias for `add`

include/win.c
=> win: fix compilation of win.c

src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/dfa/DFA.java
return NO_CLAZZ if we are assigning unit type or target of assignment is unit.
=> dfa: override accessedClazz

include/fz.h, include/shared.c, modules/base/src/fuzion/sys/err.fz, modules/base/src/fuzion/sys/fileio.fz, modules/base/src/fuzion/sys/out.fz, tests/javaBase/javaHello.fz.expected_out, tests/javaBase/javaHello.fz.expected_out_c
=> io: flush buffers on every say/yak etc.

src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, tests/asParsedType_negative/test_asParsedType_negative.fz.expected_err, tests/catch_postcondition/catch_postcondition.fz.expected_err_int, tests/compile_time_type_casts_negative2/compile_time_type_casts_negative2.fz.expected_err_int, tests/contracts_negative/SquareRoot.fz.expected_err_int, tests/effect_installed_negative/test_effect_neg.fz.expected_err, tests/generics_negative/generics_negative.fz.expected_err, tests/partial_application_negative/partial_application_negative.fz.expected_err, tests/reg_issue118/issue118.fz.expected_err, tests/reg_issue1559_post_condition/test_issue1559.fz.expected_err, tests/reg_issue1741/reg_issue1741.fz.expected_err, tests/reg_issue1886_option_void/issue1886.fz.expected_err_int, tests/reg_issue2194/reg_issue2194.fz.expected_err_int, tests/reg_issue2231/reg_issue2231.fz.expected_err_int, tests/reg_issue2273/reg_issue2273.fz.expected_err, tests/reg_issue2304/reg_issue2304.fz.expected_err_int, tests/reg_issue2325/reg_issue2325.fz.expected_err_int, tests/reg_issue2386/reg_issue2386.fz.expected_err, tests/reg_issue2564/reg_issue2564.fz.expected_err, tests/reg_issue270/issue270.fz.expected_err_int, tests/reg_issue2745/reg_issue2745.fz.expected_err_int, tests/reg_issue3337/reg_issue3337.fz.expected_err, tests/reg_issue3352/reg_issue3352.fz.expected_err_int, tests/reg_issue348/reg_issue348.fz.expected_err, tests/visibility_modules_negative/main.fz.expected_err
=> ast: replace `$MODULE` in error message with name of fum file

modules/base/src/io/buffered/reader.fz, tests/reg_issue4486/Makefile, tests/reg_issue4486/reg_issue4486.fz, tests/reg_issue4486/reg_issue4486.fz.expected_out
=> lib/io: don't return line for final newline in `io.buffered.read_lines`

bin/spell_check_java.sh
=> spelling: UNKOWN_WORDS -> UNKNOWN_WORDS

include/fz.h, include/shared.c, modules/base/src/ffi.fz
While working on a jextract like tool for fuzion, I realized that these will be needed to conveniently work with c-code.
=> lib: add ffi convenience features: null, is_null

include/fz.h, include/posix.c, include/win.c, modules/base/src/fuzion/sys/fileio.fz, modules/base/src/io/dir/read.fz
Note that I did not test the windows code, yet
=> posix.c: remove telldir/seekdir which are not POSIX

.github/workflows/apple.yml, .github/workflows/linux.yml, tests/check_simple_example_effect.sh, tests/record_simple_example_effect.sh
also added shellcheck to apple workflow
=> actions: fix linux workflow

src/dev/flang/ast/If.java, src/dev/flang/ast/Match.java, tests/reg_issue4516/Makefile, tests/reg_issue4516/reg_issue4516.fz, tests/reg_issue4516_1/Makefile, tests/reg_issue4516_1/reg_issue4516_1.fz
=> ast: fix field for result not added in nested match/if expr

tests/outerNormalization/outerNormalization.fz
=> tests: fix typo

include/win.c
=> be/win: fix compilation of fuzion.dll

README.md
=> readme: update example

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/DFA.java, tests/reg_issue4592/Makefile, tests/reg_issue4592/reg_issue4592.fz, tests/reg_issue4592/reg_issue4592.fz.expected_err
=> dfa: error when replacing effect that is not installed

src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
=> fuir: remove lookupCall with 2 args

tests/reg_issue4250/Makefile, tests/reg_issue4250/reg_issue4250.fz, tests/reg_issue4250/reg_issue4250.fz.expected_err
=> tests: add test #4250

src/dev/flang/be/c/C.java, src/dev/flang/be/c/CTypes.java, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/ChoiceIdAsRef.java, src/dev/flang/be/interpreter/Layout.java, src/dev/flang/be/jvm/Choices.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Names.java, src/dev/flang/fuir/FUIR.java, src/dev/flang/fuir/GeneratingFUIR.java
This makes clazzChoiceCount and  clazzFieldCount consistent with clazzArgCount and matchCaseCount
=> naming: use <name>Count instead of Num<names>

src/dev/flang/ast/AbstractAssign.java, tests/reg_issue4479/Makefile, tests/reg_issue4479/reg_issue4479.fz, tests/reg_issue4479/reg_issue4479.fz.expected_err
=> ast: fix strange errors reported

src/dev/flang/ast/AbstractType.java, tests/reg_issue4542/Makefile, tests/reg_issue4542/reg_issue4542.fz, tests/reg_issue4542/reg_issue4542.fz.expected_err
=> ast: fix crash when failing to infer generic argument

tests/reg_issue4518/Makefile, tests/reg_issue4518/reg_issue4518.fz, tests/reg_issue4518/reg_issue4518.fz.expected_err
=> tests: add reg test #4518

src/dev/flang/fe/SourceModule.java, tests/reg_issue4529/Makefile, tests/reg_issue4529/reg_issue4529.fz, tests/reg_issue4529/reg_issue4529.fz.expected_err
A bit unsatisfying to have another special case here but I did not find a better way.
fixes #4529
=> fe: fix index out of bounds in SourceModule.inScope

src/dev/flang/ast/Partial.java, tests/reg_issue4621/Makefile, tests/reg_issue4621/reg_issue4621.fz, tests/reg_issue4621/reg_issue4621.fz.expected_err
=> ast: fix calling type on partial not resulting in error

modules/base/src/container/Map.fz, modules/base/src/container/Mutable_Map.fz, modules/base/src/container/hash_map.fz, modules/base/src/container/mutable_tree_map.fz, modules/base/src/container/ordered_map.fz, modules/base/src/container/ps_map.fz, modules/base/src/memoize.fz, modules/lock_free/src/lock_free/Map.fz, modules/lock_free/src/lock_free/Sieve_Cache.fz, modules/lock_free/src/lock_free/group_by.fz, modules/lock_free/src/lock_free/set_of_hashable.fz, tests/mod_lock_free_Map/ctrie_test.fz, tests/mod_lock_free_Map_threads/ctrie_threads.fz
=> lib: let `mutable_tree_map` inherit form `Mutable_Map` and add features

modules/base/src/Sequence.fz, modules/base/src/list.fz
=> lib: add `Sequence.scan` that takes a function

src/dev/flang/fuir/GeneratingFUIR.java
This information will be used when serializing the FUIR.
=> fuir: record which sites and code where used by DFA

tests/reg_issue2301/Makefile, tests/reg_issue2301/reg_issue2301.fz
=> tests: add regression test for issue #2301

include/shared.c
=> be/c: shared.c fix comment

modules/base/src/property/orderable.fz
=> lib: orderable provide implementation for type.equality

src/dev/flang/ast/AbstractType.java, tests/mix_inheritance_and_outer/Makefile, tests/mix_inheritance_and_outer/mix_inheritance_and_outer.fz.expected_out
=> ast: fix applyTypePars for this-types

tests/reg_issue4248/Makefile, tests/reg_issue4248/reg_issue4248.fz, tests/reg_issue4248/reg_issue4248.fz.expected_err
=> tests: add regression test #4248

src/dev/flang/tools/docs/DocsOptions.java, src/dev/flang/tools/docs/Html.java
required by [flangdev/#477](https://git.tokiwa.software/tokiwa/flang_dev/pulls/477)
=> docs: fix links to fuzion source files

tests/lib_io_utf8/Makefile, tests/lib_io_utf8/lib_io_utf8.fz, tests/lib_io_utf8/lib_io_utf8.fz.expected_out
=> tests: test file io using unicode

tests/reg_issue659/Makefile, tests/reg_issue659/reg_issue659.fz
=> tests: add reg test #659

Makefile, include/fz.h, include/posix.c, include/win.c, modules/base/src/native.fz, modules/base/src/os/processes.fz, src/dev/flang/be/c/Intrinsics.java, tests/process/test_process.fz, tests/process/test_process.fz.expected_out
This is for getting the last error number. For now only used in process.start.
=> native: add `fzE_errno`

include/fz.h, include/posix.c, include/win.c, modules/base/src/native.fz, modules/base/src/os/processes.fz
=> cleanups, related to `fzE_last_error`

src/dev/flang/ast/Call.java
This will make it easier to return something else than t_void in case of recursion in resolveTypes.
=> ast: change control flow in getActualResultType

tests/process_utf8/Makefile, tests/process_utf8/process_utf8.fz, tests/process_utf8/process_utf8.fz.expected_out, tests/process_utf8/unicode_feature.fz
=> tests: test starting process using unicode

src/dev/flang/tools/docs/Util.java
=> docs: fix comments in api docs missing

src/dev/flang/ast/Box.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, tests/reg_issue4745/Makefile, tests/reg_issue4745/reg_issue4745.fz, tests/reg_issue4745/reg_issue4745.fz.expected_err
=> ast: suppress error if type of actual is error

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Types.java, src/dev/flang/fe/LibraryFeature.java
=> fe: rename `createThisType` -> `createSelfType`

tests/lib_monad/Makefile, tests/lib_monad/lib_monad.fz, tests/lib_monad/lib_monad.fz.expected_out
The NYI comments where outdated so I removed them
=> lib: update monad, add test for monad

modules/base/src/option.fz, modules/base/src/outcome.fz, modules/base/src/switch.fz, src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/ResolvedNormalType.java
=> fe: fix choice-this-types

tests/reg_issue4555/Makefile, tests/reg_issue4555/reg_issue4555.fz, tests/reg_issue4555/reg_issue4555.fz.expected_out
=> tests: #4555

.github/workflows/apple.yml, .github/workflows/linux.yml, .github/workflows/windows.yml, src/dev/flang/be/c/C.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/ClazzRecord.java, src/dev/flang/fuir/DfaFUIR.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/LibraryFuir.java, src/dev/flang/fuir/SiteRecord.java, src/dev/flang/fuir/analysis/dfa/DFA.java, src/dev/flang/tools/Fuzion.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/tools/fzjava/FZJava.java
currently behind feature flag:
`dev_flang_tools_serializeFUIR`
=> fuir: add serialization

Dockerfile
=> enable fuir serialization for jenkins builds

src/dev/flang/ast/Function.java, tests/reg_issue4251/Makefile, tests/reg_issue4251/reg_issue4251.fz, tests/reg_issue4251/reg_issue4251.fz.expected_err
=> ast: suppress subsequent error referencing type `--UNDEFINED--`

src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch
=> update java patch

src/dev/flang/ast/ResolvedNormalType.java
This is the reason #4781 fails currently.
=> ast: ResolvedNormalType.asThis do not create this type of universe

Makefile, bin/ebnf.fz
=> Make add ebnf

src/dev/flang/fe/Module.java, src/dev/flang/fe/SourceModule.java, tests/argumentcount_negative/argumentcount_negative.fz.expected_err
=> fe: set _declaredOrInheritedFeatures in only one place

src/dev/flang/fe/SourceModule.java, tests/reg_issue932/Makefile, tests/reg_issue932/reg_issue932.fz, tests/reg_issue932/reg_issue932.fz.expected_out
=> fe: fix redefinition for features added to library features

Makefile
=> remove `__marker_for_make__` for fuzion rt

modules/base/src/container/expanding_array.fz, modules/base/src/os/process.fz, tests/fallible/test_fallible.fz, tests/reg_issue3619/reg_issue3619.fz, tests/this_type/test_this_type.fz
=> lib/tests: `redef fixed` => `fixed redef`

Dockerfile
=> try fix question mark output in jenkins

modules/base/src/option.fz
=> lib: cleanup new lines in option

modules/base/src/fuzion/sys/fileio.fz
=> lib: fix spelling

src/dev/flang/fuir/analysis/dfa/Call.java, src/dev/flang/fuir/analysis/dfa/SysArray.java
=> dfa: SysArray._clazz, use FUIR.NO_CLAZZ instead of clazzAny

modules/base/src/fuzion/sys/fileio.fz, modules/base/src/internal.fz, modules/base/src/io/file/open.fz, modules/base/src/io/file/seek.fz, modules/base/src/io/file/use.fz, modules/base/src/native.fz, src/dev/flang/ast/Feature.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/interpreter/JavaInterface.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/SpecialClazzes.java, src/dev/flang/fuir/analysis/dfa/Call.java
This PR introduces a distinction of file pointers and other pointers.
=> lib/be:  add `file descriptor ref`

src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/Names.java, src/dev/flang/be/jvm/Types.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/SpecialClazzes.java
also cleanups and code simplifications
=> fuir: add `Native_Ref` to SpecialClazzes

src/dev/flang/tools/docs/Html.java
* in signature show constraints other than `Any`
* in list of type parameters also show `Any` if type parameter has no constraint
fix #4806
looks like this now:
=> docs: fix display of constraint for type parameters

modules/base/src/container/sorted_array.fz, src/dev/flang/ast/AbstractType.java
=> fe: fix type inference for inheritance call

modules/base/src/container/Mutable_Hash_Map.fz, modules/base/src/container/Mutable_Map.fz, modules/base/src/container/mutable_hash_map.fz, tests/mutable_hash_map/mutable_hash_map_test.fz, tests/mutable_hash_map/mutable_hash_map_test.fz.expected_out
=> lib: add `mutable_hash_map`

modules/base/src/Sequence.fz, modules/base/src/array2.fz, modules/base/src/array3.fz, modules/base/src/fuzion/runtime/contract_fault.fz, modules/base/src/fuzion/runtime/fault.fz, modules/base/src/fuzion/runtime/post_fault.fz, src/dev/flang/ast/Resolution.java, src/dev/flang/ast/SrcModule.java, src/dev/flang/fe/SourceModule.java
force coTypeOrigin to be resolved before the cotype
fixes #4015
=> fe: fix issue with type inference of inheritance call

include/fz.h, include/shared.c
definition of these features is:
`... i32 => native`
=> include: fix result types fzE_file_read/write

src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/Block.java, tests/visibility_negative/visibility_negative.fz.expected_err
=> ast: `Match.typeForInferencing` return `null` on error

src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/Types.java
brings about 5% in my measurements on base.fum
=> ast: resolveSyntacticSugar2, performance enhancements

src/dev/flang/ast/Call.java, src/dev/flang/ast/Function.java, tests/free_types_negative/test_free_types_negative.fz.expected_err, tests/partial_application_negative/partial_application_negative.fz.expected_err, tests/reg_issue4549/reg_issue4549.fz.expected_err, tests/reg_issue4645/Makefile, tests/reg_issue4645/reg_issue4645.fz, tests/reg_issue4645/reg_issue4645.fz.expected_err, tests/visibility_scoping/visibility_scoping.fz.expected_err
=> ast: suppress type inference of lambda error

modules/base/src/io/buffered/reader.fz, src/dev/flang/parser/Parser.java, tests/else_indentation_reference/Makefile, tests/else_indentation_reference/else_indentation_reference.fz, tests/else_indentation_reference/else_indentation_reference.fz.expected_err
=> Restrict possibilities for indentation of `else`

src/dev/flang/fe/SourceModule.java, tests/reg_issue4961/Makefile, tests/reg_issue4961/reg_issue4961.fz, tests/reg_issue4961/reg_issue4961.fz.expected_err
=> fe: fix class cast exception

src/dev/flang/parser/Parser.java, tests/catch_postcondition/catch_postcondition.fz, tests/catch_postcondition/catch_postcondition.fz.expected_err_int, tests/reg_issue1777/reg_issue1777.fz, tests/reg_issue293_confusion_of_type_and_value_params/issue293.fz, tests/reg_issue4964/Makefile, tests/reg_issue4964/reg_issue4964.fz, tests/reg_issue4964/reg_issue4964.fz.expected_err
=> Anonymous indentation reference point issue4964

include/win.c
=> win: fix error: 'poll.h' file not found

src/dev/flang/ast/Call.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, tests/reg_issue4457/Makefile, tests/reg_issue4457/reg_issue4457.fz, tests/reg_issue4457/reg_issue4457.fz.expected_err
=> ast: avoid errors caused by additional lambda argument

src/dev/flang/tools/docs/Html.java
fix [flang_dev#508](https://git.tokiwa.software/tokiwa/flang_dev/issues/508)
=> docs: fix broken links for inheritance if feature is from other module

src/dev/flang/ast/Call.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/Types.java, tests/reg_issue5018/Makefile, tests/reg_issue5018/reg_issue5018.fz, tests/reg_issue929/reg_issue929.fz.expected_err
=> ast: fix inference of lambda with no arguments

src/dev/flang/ast/AstErrors.java, src/dev/flang/fe/FrontEndOptions.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/tools/Fuzion.java, src/dev/flang/tools/docs/Docs.java, src/dev/flang/util/FuzionConstants.java
=> fe: raise error when adding field without parent in module

include/posix.c
>   //"In  multithreaded programs, using fcntl() F_SETFD to set the close-on-exec flag
>   // at the same time as another thread performs a fork(2) plus execve(2) is vulnerable
>   // to a race condition that may unintentionally leak the file descriptor to the
>   // program executed in the child process.  See the discussion of the O_CLOEXEC flag in open(2)
>   // for details and a remedy to the problem."
>
=> fuzion runtime: fix possible descriptor leak

tests/reg_issue1726/Makefile, tests/reg_issue1726/reg_issue1726.fz, tests/reg_issue1726/reg_issue1726.fz.expected_out
=> tests add reg. test #1726

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/ParsedCall.java, src/dev/flang/ast/Partial.java, tests/reg_issue4252/Makefile, tests/reg_issue4252/reg_issue4252.fz, tests/reg_issue4252/reg_issue4252.fz.expected_err, tests/reg_issue4621/reg_issue4621.fz.expected_err
=> ast: improve error when failing to resolve partial application

tests/reg_issue4422/Makefile, tests/reg_issue4422/reg_issue4422.fz
=> tests: add test #4422

modules/base/src/Lazy.fz
=> lib: make Lazy inherit from monad

Makefile, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/JVM.java, src/dev/flang/be/jvm/runtime/Runtime.java
I think this might be the better name in the long run...
=> rename libfuzion -> libfuzion_rt

.devcontainer/devcontainer.json
=> fix devcontainer

.github/workflows/linux.yml
=> fix linux workflow

src/dev/flang/ast/Call.java, tests/reg_issue4988/Makefile, tests/reg_issue4988/reg_issue4988.fz, tests/reg_issue4988/reg_issue4988.fz.expected_err, tests/reg_issue4988_1/Makefile, tests/reg_issue4988_1/reg_issue4988_1.fz, tests/reg_issue4988_1/reg_issue4988_1.fz.expected_err
=> fe: fix crash when failing to infer generics of call

tests/nested_choice/nested_choice.fz, tests/reg_issue2242/reg_issue2242.fz, tests/reg_issue960_npe_resolve_syntactic_sugar2/test_issue960.fz, tests/reg_issue960_npe_resolve_syntactic_sugar2/test_issue960.fz.expected_err, tests/tuple/tupletest.fz
Things have changed since those NYI comments...
=> tests: cleanup of NYI comments

src/dev/flang/tools/fzjava/ForClass.java
=> fzjava: avoid unnecessary parentheses in generated code

include/win.c
=> be/c: convert some functions to windows native

include/fz.h
=> fz.h: update outdated comment

src/dev/flang/ast/Block.java, tests/lib_concur_sync/lib_concur_sync.fz
=> ast: fix `DFA reading uninitialized field`

include/fz.h, include/posix.c, include/win.c, modules/base/src/native.fz, modules/base/src/os/Process_Handler.fz, modules/base/src/os/processes.fz, tests/check_simple_example_c.sh, tests/check_simple_example_effect.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh, tests/process/test_process.fz, tests/process_utf8/Makefile, tests/process_utf8/process_utf8.fz, tests/process_utf8/process_utf8.fz.expected_out
=> win: fix problems related to tests/process_utf8

tests/check_simple_example_c.sh, tests/check_simple_example_effect.sh, tests/check_simple_example_int.sh, tests/check_simple_example_jvm.sh
=> windows: readd workaround for unicode problem

modules/base/src/exception.fz, modules/base/src/try.fz, tests/fallible/test_fallible.fz, tests/javaBase/javaHello.fz, tests/reg_issue1561_incompatible_types/test_issue1561.fz, tests/reg_issue1698/reg_issue1698.fz, tests/reg_issue459_choice_elment_tagged_that_is_never_instantiated/issue459.fz, tests/resource_cleanunp/resource_cleanunp.fz, tests/unwrap/test_unwrap.fz
Fix #3356 by renaming `try` as `exception`
=> lib: rename `try` as `exception`

bin/run_tests.fz
consider this work in progress
=> port run_tests to fuzion

modules/base/src/String.fz
I'm unsure about the API design...
What do you think? @tokiwa-software/developers
=> lib: String add write_to, writing String to installed writer

.github/workflows/windows.yml
Now that windows is green again...
=> run windows tests every workday

Makefile
=> makefile: add helper to rerecord effects

Makefile, src/dev/flang/tools/Fuzion.java, tests/compile.mk, tests/fe.mk, tests/fz_cmd/fz_cmd.fz.expected_err, tests/inherit_postcondition/Makefile, tests/modules/Makefile, tests/reg_issue1109/Makefile, tests/reg_issue2237/Makefile, tests/reg_issue3772/Makefile, tests/visibility_modules/Makefile, tests/visibility_modules_negative/Makefile
=> fz: change all options to camelCase

src/dev/flang/ast/AstErrors.java, src/dev/flang/parser/Parser.java, tests/reg_issue5156/reg_issue5156.fz, tests/reg_issue5156/reg_issue5156.fz.expected_err
Also extend test case for #5156.
=> parser: Further improve error output in `AstErrors.qualifierExpectedForDotThis`

modules/base/src/order.fz
fix #5122
Added predicates with all 6 combinations.
=> Added predicate functions for order

modules/base/src/container/mutable_tree_map.fz, modules/base/src/container/ordered_map.fz, modules/base/src/container/ps_map.fz
=> lib: change `mutable_tree_map.type.from_array` to `.from_sequence`

include/win.c
Set file pointer to end if mode is append.
[ci skip]
=> win: fzE_file_open fix semantics of append

include/fz.h, include/posix.c, include/win.c, modules/base/src/fuzion/sys/fileio.fz, modules/base/src/io/file/use.fz, modules/base/src/native.fz
=> runtime: fzE_file_open, change arg type of mode

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Function.java, tests/reg_issue5188/Makefile, tests/reg_issue5188/reg_issue5188.fz, tests/reg_issue5188/reg_issue5188.fz.expected_err
=> fe: AbstractType, fix NPE in applyTypePars

assets/docs/style.css, src/dev/flang/tools/docs/Html.java
=> docs: right align src button in api docs

src/dev/flang/be/c/C.java, src/dev/flang/be/interpreter/Executor.java, src/dev/flang/be/jvm/CodeGen.java, src/dev/flang/fuir/analysis/AbstractInterpreter.java, src/dev/flang/fuir/analysis/AbstractInterpreter2.java.patch, src/dev/flang/fuir/analysis/dfa/DFA.java
=> ai: simplify assignStatic

src/dev/flang/ast/AbstractCall.java, src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/ArtificialBuiltInType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Case.java, src/dev/flang/ast/FunctionReturnType.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/ResolvedParametricType.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/FeatureAndActuals.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/tools/docs/Html.java, tests/local_mutate/test_local_mutate.fz.expected_out, tests/reg_issue2111/reg_issue2111.fz.expected_err, tests/reg_issue2402/reg_issue2402.fz.expected_out
- remove implementations of toString in resolved types.
=> fe: merge AbstractType toString/asString

src/dev/flang/ast/AbstractCase.java, src/dev/flang/ast/Case.java, src/dev/flang/ast/FeatureVisitor.java, src/dev/flang/fe/SourceModule.java
- visit Case was unused
- removed actionBefore/After with one arg since I felt these are more confusing than helpful
=> ast: cleanup visitation of Case/AbstractCase

modules/base/src/concur/Channel.fz, modules/base/src/concur/Iterator.fz, modules/base/src/concur/Receiving_Channel.fz, modules/base/src/concur/Sending_Channel.fz, tests/lib_concur_Channel/Makefile, tests/lib_concur_Channel/lib_concur_Channel.fz, tests/lib_concur_Channel/lib_concur_Channel.fz.expected_out
a Channel can be used to send values to another thread
=> lib: add `concur.Channel`

modules/base/src/net/client.fz
not everything was fixed in #5290
=> lib: client, fix example in comment

src/dev/flang/ast/AbstractAssign.java, src/dev/flang/ast/AbstractMatch.java, src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/Block.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/Expr.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/Function.java, src/dev/flang/ast/InlineArray.java, src/dev/flang/ast/Tag.java, src/dev/flang/fe/SourceModule.java, src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/lsp/feature/Commands.java, src/dev/flang/util/YesNo.java, tests/reg_issue3648/reg_issue3648.fz.expected_err
...to reflect that types may contain error.
fixes #5305
=> fe: isAssignable return YesNo instead of bool

modules/base/src/realtime.fz
nothing there yet, just a new _namespace_
=> lib: add feature realtime

src/dev/flang/tools/docs/Html.java
=> docs: for function features hide inner (inherited) functions and fields

examples/gtk/Makefile, examples/gtk/gtk.fz
=> examples/gtk: add test for pkg-config and gtk, documentation

src/dev/flang/tools/docs/Util.java
somehow, the regex stopped working
=> docs: fix missing comments in API docs

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/ArtificialBuiltInType.java, src/dev/flang/ast/Feature.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/Types.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fe/LibraryModule.java, src/dev/flang/fe/LibraryOut.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/lsp/shared/FeatureTool.java, src/dev/flang/tools/docs/Docs.java
I think this is not needed anymore.
=> fe: remove `t_ADDRESS`

bin/ebnf.fz, src/dev/flang/parser/Lexer.java
Turns out grammar was broken... rule QUESTION was duplicated.
=> ebnf: raise error on grammar error

src/dev/flang/ast/AbstractType.java, src/dev/flang/ast/AstErrors.java, src/dev/flang/ast/ParsedType.java, src/dev/flang/ast/ResolvedNormalType.java, src/dev/flang/ast/ResolvedParametricType.java, src/dev/flang/ast/ThisType.java, src/dev/flang/ast/UnresolvedType.java, src/dev/flang/fe/GenericType.java, src/dev/flang/fe/NormalType.java, src/dev/flang/fe/ThisType.java, src/dev/flang/fuir/Clazz.java
no need that these methods are abstract
98 insertions(+), 305 deletions(-)
=> ast: cleanup AbstractType asValue/asRef/asThis

src/dev/flang/be/jvm/runtime/Runtime.java
=> be/jvm: add error message for missing library

src/dev/flang/ast/AbstractType.java, src/dev/flang/fuir/Clazz.java, src/dev/flang/fuir/GeneratingFUIR.java
Just a small step for cleaning this up.
=> remove second iteration in handDown

src/dev/flang/ast/AbstractFeature.java, src/dev/flang/ast/Call.java, src/dev/flang/ast/FormalGenerics.java, src/dev/flang/ast/Resolution.java, src/dev/flang/ast/UnresolvedType.java
goal is to eventually get rid of FormalGenerics altogether
=> ast: move FormalGenerics.resolve to Resolution

src/dev/flang/ast/Case.java
Seems to me it is unnecessary.
=> ast: Case, don't visit _types

src/dev/flang/ast/Feature.java, src/dev/flang/ast/Match.java, tests/reg_issue5353/Makefile, tests/reg_issue5353/reg_issue5353.fz, tests/reg_issue5353/reg_issue5353.fz.expected_err
=> ast: fix #5353, require condition in Call

modules/base/src/oneway_monad.fz
=> lib: fix minor typo

Makefile
=> make: syntaxcheck, add module terminal

include/fz.h, include/shared.c, modules/base/src/fuzion/jvm.fz, src/dev/flang/be/c/Intrinsics.java, src/dev/flang/be/interpreter/Intrinsics.java, src/dev/flang/be/jvm/Intrinsix.java, src/dev/flang/fuir/analysis/dfa/DFA.java
This PR is due to linux pipeline currently failing
=> lib: show error code when jvm fails to start

src/dev/flang/ast/Feature.java
resolveArgumentTypes is done in earlier phase already
=> ast: remove unecessary code

README.md, bin/ebnf.fz
=> bin/ebnf: make pcregrep/antlr a soft dependency

tests/sockets/sockets_test.fz, tests/sockets/sockets_test.fz.expected_out, tests/sockets_thread_pool/sockets_test.fz, tests/sockets_thread_pool/sockets_test.fz.expected_out
Now tries a hundred ports starting at 30000 instead of using specific ports.
=> tests: reduce flakiness of sockets test

modules/base/src/concur/Blocking_Queue.fz, modules/base/src/concur/Channel.fz, modules/base/src/concur/sync.fz, modules/base/src/concur/thread_pool.fz
an attempt to fix spurious test failures by enlarging the critical sections in `enque` and `dequeue`
=> lib: Blocking_Queue fix attempt

src/dev/flang/ast/AstErrors.java, src/dev/flang/fe/SourceModule.java, tests/function_argument_visibility/function_argument_visibility.fz.expected_err, tests/reg_issue5704/Makefile, tests/reg_issue5704/reg_issue5704.fz, tests/reg_issue5704/reg_issue5704.fz.expected_err
=> forbid defining intrinsics outside of base library

tests/reg_issue5690/Makefile, tests/reg_issue5690/reg_issue5690.fz, tests/reg_issue5690/reg_issue5690.fz.expected_err
=> tests: add reg test #5690

src/dev/flang/tools/docs/Html.java
=> docs: fix display of type constraint in api docs

tests/native_outerref_pass_through/native_outerref_pass_through.fz, tests/native_value/fz.h
=> tests: add comment to native_outerref_pass_through

modules/base/src/time/histogram.fz
=> base: time.histogram: improve comment to refer to period and cycle jitter

include/win.c
=> win: add missing include direct.h

src/dev/flang/tools/docs/Html.java
=> docs: don't show non public features in inheritance or annotations

src/dev/flang/parser/Lexer.java, tests/reg_issue1022/Makefile, tests/reg_issue1022/reg_issue1022.fz, tests/reg_issue1022/reg_issue1022.fz.expected_err
=> fix #1022, confusing indentation related error

modules/base/src/container/Set.fz, modules/base/src/f128.fz, modules/base/src/f16.fz, modules/base/src/net/socket_type.fz, modules/base/src/panic.fz, modules/base/src/tuple.fz
=> lib: add compile_time_panic

Makefile
=> Makefile: compile `run_tests.fz` in a separate target

modules/base/src/universe.fz, src/dev/flang/tools/docs/Util.java
I'm not sure if it is nice to have this big code box at the top of each root module page
=> allow code in universe comment

bin/run_tests.fz, include/posix.c, include/win.c, modules/base/src/native.fz, modules/base/src/os/process.fz, modules/base/src/os/processes.fz
Currently implemented via polling with increasing timeout 1ms, 2ms, 4ms, 8ms ...
=> lib: process.wait add timeout parameter

modules/base/src/bitset.fz
=> lib: improve comment in bitset

src/dev/flang/ast/Function.java, tests/reg_issue5854/Makefile, tests/reg_issue5854/reg_issue5854.fz, tests/reg_issue5854/reg_issue5854.fz.expected_err
=> fe: fix check condition failure in man_or_boy2

src/dev/flang/be/jvm/runtime/Runtime.java
=> be/jvm: add missing space in error string

modules/base/src/container/expanding_array.fz
=> lib: exanding_array, fix comment

src/dev/flang/fuir/GeneratingFUIR.java, src/dev/flang/fuir/OptimizedFUIR.java
This reduces the time for tests/mod_http_message by more than 40%. About 35s before, now ~20s.
=> fuir: use Bitset for _accessedSites

src/dev/flang/ast/Call.java
This reduces the enormous argument count by one, but the code is stall awfull with too many arguments.
=> ast: cleanup in `inferGenericLambdaResult`: avoid `boolean[] result` argument

doc/ref_manual/fuzion_reference_manual.adoc
=> doc: fix header levels in reference manuals
